// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/marketdata/v2/crypto_trades.proto

package marketdatav2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CryptoTrade represents a crypto trade.
type CryptoTrade struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp (RFC 3339).
	T string `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	// Trade price.
	P float64 `protobuf:"fixed64,2,opt,name=p,proto3" json:"p,omitempty"`
	// Trade size.
	S float64 `protobuf:"fixed64,3,opt,name=s,proto3" json:"s,omitempty"`
	// Trade ID.
	I int64 `protobuf:"varint,4,opt,name=i,proto3" json:"i,omitempty"`
	// Taker side (B = buy, S = sell).
	Tks           string `protobuf:"bytes,5,opt,name=tks,proto3" json:"tks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoTrade) Reset() {
	*x = CryptoTrade{}
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoTrade) ProtoMessage() {}

func (x *CryptoTrade) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoTrade.ProtoReflect.Descriptor instead.
func (*CryptoTrade) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_crypto_trades_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoTrade) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

func (x *CryptoTrade) GetP() float64 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *CryptoTrade) GetS() float64 {
	if x != nil {
		return x.S
	}
	return 0
}

func (x *CryptoTrade) GetI() int64 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *CryptoTrade) GetTks() string {
	if x != nil {
		return x.Tks
	}
	return ""
}

// GetCryptoTradesRequest is the request to get historical crypto trades.
type GetCryptoTradesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Crypto location (us).
	Loc string `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	// Comma-separated list of symbols.
	Symbols string `protobuf:"bytes,2,opt,name=symbols,proto3" json:"symbols,omitempty"`
	// Start timestamp (RFC 3339 or YYYY-MM-DD).
	Start string `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	// End timestamp (RFC 3339 or YYYY-MM-DD).
	End string `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	// Maximum number of trades to return (1-10000, default 1000).
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Page token for pagination.
	PageToken string `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Sort order (asc, desc).
	Sort          string `protobuf:"bytes,7,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCryptoTradesRequest) Reset() {
	*x = GetCryptoTradesRequest{}
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCryptoTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoTradesRequest) ProtoMessage() {}

func (x *GetCryptoTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoTradesRequest.ProtoReflect.Descriptor instead.
func (*GetCryptoTradesRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_crypto_trades_proto_rawDescGZIP(), []int{1}
}

func (x *GetCryptoTradesRequest) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

func (x *GetCryptoTradesRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

func (x *GetCryptoTradesRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetCryptoTradesRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetCryptoTradesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCryptoTradesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetCryptoTradesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

// CryptoTradesList is a list of trades for a single symbol.
type CryptoTradesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*CryptoTrade         `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoTradesList) Reset() {
	*x = CryptoTradesList{}
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoTradesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoTradesList) ProtoMessage() {}

func (x *CryptoTradesList) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoTradesList.ProtoReflect.Descriptor instead.
func (*CryptoTradesList) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_crypto_trades_proto_rawDescGZIP(), []int{2}
}

func (x *CryptoTradesList) GetTrades() []*CryptoTrade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// GetCryptoTradesResponse is the response containing crypto trades.
type GetCryptoTradesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to trades.
	Trades map[string]*CryptoTradesList `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Next page token.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCryptoTradesResponse) Reset() {
	*x = GetCryptoTradesResponse{}
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCryptoTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoTradesResponse) ProtoMessage() {}

func (x *GetCryptoTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoTradesResponse.ProtoReflect.Descriptor instead.
func (*GetCryptoTradesResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_crypto_trades_proto_rawDescGZIP(), []int{3}
}

func (x *GetCryptoTradesResponse) GetTrades() map[string]*CryptoTradesList {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *GetCryptoTradesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetLatestCryptoTradesRequest is the request to get the latest crypto trades.
type GetLatestCryptoTradesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Crypto location (us).
	Loc string `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	// Comma-separated list of symbols.
	Symbols       string `protobuf:"bytes,2,opt,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestCryptoTradesRequest) Reset() {
	*x = GetLatestCryptoTradesRequest{}
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestCryptoTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestCryptoTradesRequest) ProtoMessage() {}

func (x *GetLatestCryptoTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestCryptoTradesRequest.ProtoReflect.Descriptor instead.
func (*GetLatestCryptoTradesRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_crypto_trades_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestCryptoTradesRequest) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

func (x *GetLatestCryptoTradesRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

// GetLatestCryptoTradesResponse is the response containing the latest crypto trades.
type GetLatestCryptoTradesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to latest trade.
	Trades        map[string]*CryptoTrade `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestCryptoTradesResponse) Reset() {
	*x = GetLatestCryptoTradesResponse{}
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestCryptoTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestCryptoTradesResponse) ProtoMessage() {}

func (x *GetLatestCryptoTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestCryptoTradesResponse.ProtoReflect.Descriptor instead.
func (*GetLatestCryptoTradesResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_crypto_trades_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestCryptoTradesResponse) GetTrades() map[string]*CryptoTrade {
	if x != nil {
		return x.Trades
	}
	return nil
}

var File_alpaca_marketdata_v2_crypto_trades_proto protoreflect.FileDescriptor

const file_alpaca_marketdata_v2_crypto_trades_proto_rawDesc = "" +
	"\n" +
	"(alpaca/marketdata/v2/crypto_trades.proto\x12\x14alpaca.marketdata.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"\xb1\x01\n" +
	"\vCryptoTrade\x12/\n" +
	"\x01t\x18\x01 \x01(\tB!\xba\xb5\x18\x1d\n" +
	"\x1b2024-01-15T10:30:00.123456ZR\x01t\x12\x1c\n" +
	"\x01p\x18\x02 \x01(\x01B\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b42000.00R\x01p\x12\x17\n" +
	"\x01s\x18\x03 \x01(\x01B\t\xba\xb5\x18\x05\n" +
	"\x030.5R\x01s\x12\x1f\n" +
	"\x01i\x18\x04 \x01(\x03B\x11\xba\xb5\x18\r\n" +
	"\v12345678901R\x01i\x12\x19\n" +
	"\x03tks\x18\x05 \x01(\tB\a\xba\xb5\x18\x03\n" +
	"\x01BR\x03tks\"\x8b\x03\n" +
	"\x16GetCryptoTradesRequest\x12\x1a\n" +
	"\x03loc\x18\x01 \x01(\tB\b\xba\xb5\x18\x04\n" +
	"\x02usR\x03loc\x12B\n" +
	"\asymbols\x18\x02 \x01(\tB(\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x11\n" +
	"\x0fBTC/USD,ETH/USDµ\x18\t\n" +
	"\asymbolsR\asymbols\x12;\n" +
	"\x05start\x18\x03 \x01(\tB%\xba\xb5\x18\x16\n" +
	"\x142024-01-15T00:00:00Zµ\x18\a\n" +
	"\x05startR\x05start\x125\n" +
	"\x03end\x18\x04 \x01(\tB#\xba\xb5\x18\x16\n" +
	"\x142024-01-15T23:59:59Zµ\x18\x05\n" +
	"\x03endR\x03end\x125\n" +
	"\x05limit\x18\x05 \x01(\x05B\x1f\xbaH\a\x1a\x05\x18\x90N(\x01\xba\xb5\x18\x06\n" +
	"\x041000µ\x18\a\n" +
	"\x05limitR\x05limit\x12=\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tB\x1e\xba\xb5\x18\n" +
	"\n" +
	"\btoken123µ\x18\f\n" +
	"\n" +
	"page_tokenR\tpageToken\x12'\n" +
	"\x04sort\x18\a \x01(\tB\x13\xba\xb5\x18\x05\n" +
	"\x03ascµ\x18\x06\n" +
	"\x04sortR\x04sort\"M\n" +
	"\x10CryptoTradesList\x129\n" +
	"\x06trades\x18\x01 \x03(\v2!.alpaca.marketdata.v2.CryptoTradeR\x06trades\"\x87\x02\n" +
	"\x17GetCryptoTradesResponse\x12Q\n" +
	"\x06trades\x18\x01 \x03(\v29.alpaca.marketdata.v2.GetCryptoTradesResponse.TradesEntryR\x06trades\x126\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\bYWJjZGVmR\rnextPageToken\x1aa\n" +
	"\vTradesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.alpaca.marketdata.v2.CryptoTradesListR\x05value:\x028\x01\"~\n" +
	"\x1cGetLatestCryptoTradesRequest\x12\x1a\n" +
	"\x03loc\x18\x01 \x01(\tB\b\xba\xb5\x18\x04\n" +
	"\x02usR\x03loc\x12B\n" +
	"\asymbols\x18\x02 \x01(\tB(\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x11\n" +
	"\x0fBTC/USD,ETH/USDµ\x18\t\n" +
	"\asymbolsR\asymbols\"\xd6\x01\n" +
	"\x1dGetLatestCryptoTradesResponse\x12W\n" +
	"\x06trades\x18\x01 \x03(\v2?.alpaca.marketdata.v2.GetLatestCryptoTradesResponse.TradesEntryR\x06trades\x1a\\\n" +
	"\vTradesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.alpaca.marketdata.v2.CryptoTradeR\x05value:\x028\x01B\xea\x01\n" +
	"\x18com.alpaca.marketdata.v2B\x11CryptoTradesProtoP\x01ZIgithub.com/sebastienmelki/alpaca-go/api/alpaca/marketdata/v2;marketdatav2\xa2\x02\x03AMX\xaa\x02\x14Alpaca.Marketdata.V2\xca\x02\x14Alpaca\\Marketdata\\V2\xe2\x02 Alpaca\\Marketdata\\V2\\GPBMetadata\xea\x02\x16Alpaca::Marketdata::V2b\x06proto3"

var (
	file_alpaca_marketdata_v2_crypto_trades_proto_rawDescOnce sync.Once
	file_alpaca_marketdata_v2_crypto_trades_proto_rawDescData []byte
)

func file_alpaca_marketdata_v2_crypto_trades_proto_rawDescGZIP() []byte {
	file_alpaca_marketdata_v2_crypto_trades_proto_rawDescOnce.Do(func() {
		file_alpaca_marketdata_v2_crypto_trades_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_crypto_trades_proto_rawDesc), len(file_alpaca_marketdata_v2_crypto_trades_proto_rawDesc)))
	})
	return file_alpaca_marketdata_v2_crypto_trades_proto_rawDescData
}

var file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_alpaca_marketdata_v2_crypto_trades_proto_goTypes = []any{
	(*CryptoTrade)(nil),                   // 0: alpaca.marketdata.v2.CryptoTrade
	(*GetCryptoTradesRequest)(nil),        // 1: alpaca.marketdata.v2.GetCryptoTradesRequest
	(*CryptoTradesList)(nil),              // 2: alpaca.marketdata.v2.CryptoTradesList
	(*GetCryptoTradesResponse)(nil),       // 3: alpaca.marketdata.v2.GetCryptoTradesResponse
	(*GetLatestCryptoTradesRequest)(nil),  // 4: alpaca.marketdata.v2.GetLatestCryptoTradesRequest
	(*GetLatestCryptoTradesResponse)(nil), // 5: alpaca.marketdata.v2.GetLatestCryptoTradesResponse
	nil,                                   // 6: alpaca.marketdata.v2.GetCryptoTradesResponse.TradesEntry
	nil,                                   // 7: alpaca.marketdata.v2.GetLatestCryptoTradesResponse.TradesEntry
}
var file_alpaca_marketdata_v2_crypto_trades_proto_depIdxs = []int32{
	0, // 0: alpaca.marketdata.v2.CryptoTradesList.trades:type_name -> alpaca.marketdata.v2.CryptoTrade
	6, // 1: alpaca.marketdata.v2.GetCryptoTradesResponse.trades:type_name -> alpaca.marketdata.v2.GetCryptoTradesResponse.TradesEntry
	7, // 2: alpaca.marketdata.v2.GetLatestCryptoTradesResponse.trades:type_name -> alpaca.marketdata.v2.GetLatestCryptoTradesResponse.TradesEntry
	2, // 3: alpaca.marketdata.v2.GetCryptoTradesResponse.TradesEntry.value:type_name -> alpaca.marketdata.v2.CryptoTradesList
	0, // 4: alpaca.marketdata.v2.GetLatestCryptoTradesResponse.TradesEntry.value:type_name -> alpaca.marketdata.v2.CryptoTrade
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_alpaca_marketdata_v2_crypto_trades_proto_init() }
func file_alpaca_marketdata_v2_crypto_trades_proto_init() {
	if File_alpaca_marketdata_v2_crypto_trades_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_crypto_trades_proto_rawDesc), len(file_alpaca_marketdata_v2_crypto_trades_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_marketdata_v2_crypto_trades_proto_goTypes,
		DependencyIndexes: file_alpaca_marketdata_v2_crypto_trades_proto_depIdxs,
		MessageInfos:      file_alpaca_marketdata_v2_crypto_trades_proto_msgTypes,
	}.Build()
	File_alpaca_marketdata_v2_crypto_trades_proto = out.File
	file_alpaca_marketdata_v2_crypto_trades_proto_goTypes = nil
	file_alpaca_marketdata_v2_crypto_trades_proto_depIdxs = nil
}
