// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/marketdata/v2/crypto_snapshots.proto

package marketdatav2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CryptoSnapshot represents a point-in-time crypto market data snapshot.
type CryptoSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latest trade.
	LatestTrade *CryptoTrade `protobuf:"bytes,1,opt,name=latest_trade,json=latestTrade,proto3" json:"latest_trade,omitempty"`
	// Latest quote.
	LatestQuote *CryptoQuote `protobuf:"bytes,2,opt,name=latest_quote,json=latestQuote,proto3" json:"latest_quote,omitempty"`
	// Minute bar.
	MinuteBar *CryptoBar `protobuf:"bytes,3,opt,name=minute_bar,json=minuteBar,proto3" json:"minute_bar,omitempty"`
	// Daily bar.
	DailyBar *CryptoBar `protobuf:"bytes,4,opt,name=daily_bar,json=dailyBar,proto3" json:"daily_bar,omitempty"`
	// Previous daily bar.
	PrevDailyBar  *CryptoBar `protobuf:"bytes,5,opt,name=prev_daily_bar,json=prevDailyBar,proto3" json:"prev_daily_bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoSnapshot) Reset() {
	*x = CryptoSnapshot{}
	mi := &file_alpaca_marketdata_v2_crypto_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoSnapshot) ProtoMessage() {}

func (x *CryptoSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_crypto_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoSnapshot.ProtoReflect.Descriptor instead.
func (*CryptoSnapshot) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoSnapshot) GetLatestTrade() *CryptoTrade {
	if x != nil {
		return x.LatestTrade
	}
	return nil
}

func (x *CryptoSnapshot) GetLatestQuote() *CryptoQuote {
	if x != nil {
		return x.LatestQuote
	}
	return nil
}

func (x *CryptoSnapshot) GetMinuteBar() *CryptoBar {
	if x != nil {
		return x.MinuteBar
	}
	return nil
}

func (x *CryptoSnapshot) GetDailyBar() *CryptoBar {
	if x != nil {
		return x.DailyBar
	}
	return nil
}

func (x *CryptoSnapshot) GetPrevDailyBar() *CryptoBar {
	if x != nil {
		return x.PrevDailyBar
	}
	return nil
}

// GetCryptoSnapshotsRequest is the request to get crypto snapshots.
type GetCryptoSnapshotsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Crypto location (us).
	Loc string `protobuf:"bytes,1,opt,name=loc,proto3" json:"loc,omitempty"`
	// Comma-separated list of symbols.
	Symbols       string `protobuf:"bytes,2,opt,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCryptoSnapshotsRequest) Reset() {
	*x = GetCryptoSnapshotsRequest{}
	mi := &file_alpaca_marketdata_v2_crypto_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCryptoSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoSnapshotsRequest) ProtoMessage() {}

func (x *GetCryptoSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_crypto_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*GetCryptoSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *GetCryptoSnapshotsRequest) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

func (x *GetCryptoSnapshotsRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

// GetCryptoSnapshotsResponse is the response containing crypto snapshots.
type GetCryptoSnapshotsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to snapshot.
	Snapshots     map[string]*CryptoSnapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCryptoSnapshotsResponse) Reset() {
	*x = GetCryptoSnapshotsResponse{}
	mi := &file_alpaca_marketdata_v2_crypto_snapshots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCryptoSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoSnapshotsResponse) ProtoMessage() {}

func (x *GetCryptoSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_crypto_snapshots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*GetCryptoSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDescGZIP(), []int{2}
}

func (x *GetCryptoSnapshotsResponse) GetSnapshots() map[string]*CryptoSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_alpaca_marketdata_v2_crypto_snapshots_proto protoreflect.FileDescriptor

const file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDesc = "" +
	"\n" +
	"+alpaca/marketdata/v2/crypto_snapshots.proto\x12\x14alpaca.marketdata.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a&alpaca/marketdata/v2/crypto_bars.proto\x1a(alpaca/marketdata/v2/crypto_trades.proto\x1a(alpaca/marketdata/v2/crypto_quotes.proto\"\xe1\x02\n" +
	"\x0eCryptoSnapshot\x12D\n" +
	"\flatest_trade\x18\x01 \x01(\v2!.alpaca.marketdata.v2.CryptoTradeR\vlatestTrade\x12D\n" +
	"\flatest_quote\x18\x02 \x01(\v2!.alpaca.marketdata.v2.CryptoQuoteR\vlatestQuote\x12>\n" +
	"\n" +
	"minute_bar\x18\x03 \x01(\v2\x1f.alpaca.marketdata.v2.CryptoBarR\tminuteBar\x12<\n" +
	"\tdaily_bar\x18\x04 \x01(\v2\x1f.alpaca.marketdata.v2.CryptoBarR\bdailyBar\x12E\n" +
	"\x0eprev_daily_bar\x18\x05 \x01(\v2\x1f.alpaca.marketdata.v2.CryptoBarR\fprevDailyBar\"{\n" +
	"\x19GetCryptoSnapshotsRequest\x12\x1a\n" +
	"\x03loc\x18\x01 \x01(\tB\b\xba\xb5\x18\x04\n" +
	"\x02usR\x03loc\x12B\n" +
	"\asymbols\x18\x02 \x01(\tB(\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x11\n" +
	"\x0fBTC/USD,ETH/USDµ\x18\t\n" +
	"\asymbolsR\asymbols\"\xdf\x01\n" +
	"\x1aGetCryptoSnapshotsResponse\x12]\n" +
	"\tsnapshots\x18\x01 \x03(\v2?.alpaca.marketdata.v2.GetCryptoSnapshotsResponse.SnapshotsEntryR\tsnapshots\x1ab\n" +
	"\x0eSnapshotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.alpaca.marketdata.v2.CryptoSnapshotR\x05value:\x028\x01B\xed\x01\n" +
	"\x18com.alpaca.marketdata.v2B\x14CryptoSnapshotsProtoP\x01ZIgithub.com/sebastienmelki/alpaca-go/api/alpaca/marketdata/v2;marketdatav2\xa2\x02\x03AMX\xaa\x02\x14Alpaca.Marketdata.V2\xca\x02\x14Alpaca\\Marketdata\\V2\xe2\x02 Alpaca\\Marketdata\\V2\\GPBMetadata\xea\x02\x16Alpaca::Marketdata::V2b\x06proto3"

var (
	file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDescOnce sync.Once
	file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDescData []byte
)

func file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDescGZIP() []byte {
	file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDescOnce.Do(func() {
		file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDesc), len(file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDesc)))
	})
	return file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDescData
}

var file_alpaca_marketdata_v2_crypto_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_alpaca_marketdata_v2_crypto_snapshots_proto_goTypes = []any{
	(*CryptoSnapshot)(nil),             // 0: alpaca.marketdata.v2.CryptoSnapshot
	(*GetCryptoSnapshotsRequest)(nil),  // 1: alpaca.marketdata.v2.GetCryptoSnapshotsRequest
	(*GetCryptoSnapshotsResponse)(nil), // 2: alpaca.marketdata.v2.GetCryptoSnapshotsResponse
	nil,                                // 3: alpaca.marketdata.v2.GetCryptoSnapshotsResponse.SnapshotsEntry
	(*CryptoTrade)(nil),                // 4: alpaca.marketdata.v2.CryptoTrade
	(*CryptoQuote)(nil),                // 5: alpaca.marketdata.v2.CryptoQuote
	(*CryptoBar)(nil),                  // 6: alpaca.marketdata.v2.CryptoBar
}
var file_alpaca_marketdata_v2_crypto_snapshots_proto_depIdxs = []int32{
	4, // 0: alpaca.marketdata.v2.CryptoSnapshot.latest_trade:type_name -> alpaca.marketdata.v2.CryptoTrade
	5, // 1: alpaca.marketdata.v2.CryptoSnapshot.latest_quote:type_name -> alpaca.marketdata.v2.CryptoQuote
	6, // 2: alpaca.marketdata.v2.CryptoSnapshot.minute_bar:type_name -> alpaca.marketdata.v2.CryptoBar
	6, // 3: alpaca.marketdata.v2.CryptoSnapshot.daily_bar:type_name -> alpaca.marketdata.v2.CryptoBar
	6, // 4: alpaca.marketdata.v2.CryptoSnapshot.prev_daily_bar:type_name -> alpaca.marketdata.v2.CryptoBar
	3, // 5: alpaca.marketdata.v2.GetCryptoSnapshotsResponse.snapshots:type_name -> alpaca.marketdata.v2.GetCryptoSnapshotsResponse.SnapshotsEntry
	0, // 6: alpaca.marketdata.v2.GetCryptoSnapshotsResponse.SnapshotsEntry.value:type_name -> alpaca.marketdata.v2.CryptoSnapshot
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_alpaca_marketdata_v2_crypto_snapshots_proto_init() }
func file_alpaca_marketdata_v2_crypto_snapshots_proto_init() {
	if File_alpaca_marketdata_v2_crypto_snapshots_proto != nil {
		return
	}
	file_alpaca_marketdata_v2_crypto_bars_proto_init()
	file_alpaca_marketdata_v2_crypto_trades_proto_init()
	file_alpaca_marketdata_v2_crypto_quotes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDesc), len(file_alpaca_marketdata_v2_crypto_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_marketdata_v2_crypto_snapshots_proto_goTypes,
		DependencyIndexes: file_alpaca_marketdata_v2_crypto_snapshots_proto_depIdxs,
		MessageInfos:      file_alpaca_marketdata_v2_crypto_snapshots_proto_msgTypes,
	}.Build()
	File_alpaca_marketdata_v2_crypto_snapshots_proto = out.File
	file_alpaca_marketdata_v2_crypto_snapshots_proto_goTypes = nil
	file_alpaca_marketdata_v2_crypto_snapshots_proto_depIdxs = nil
}
