// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/marketdata/v2/option_quotes.proto

package marketdatav2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OptionQuote represents an option bid/ask quote.
type OptionQuote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp (RFC 3339).
	T string `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	// Ask exchange code.
	Ax string `protobuf:"bytes,2,opt,name=ax,proto3" json:"ax,omitempty"`
	// Ask price.
	Ap float64 `protobuf:"fixed64,3,opt,name=ap,proto3" json:"ap,omitempty"`
	// Ask size.
	As int64 `protobuf:"varint,4,opt,name=as,proto3" json:"as,omitempty"`
	// Bid exchange code.
	Bx string `protobuf:"bytes,5,opt,name=bx,proto3" json:"bx,omitempty"`
	// Bid price.
	Bp float64 `protobuf:"fixed64,6,opt,name=bp,proto3" json:"bp,omitempty"`
	// Bid size.
	Bs int64 `protobuf:"varint,7,opt,name=bs,proto3" json:"bs,omitempty"`
	// Quote condition.
	C             string `protobuf:"bytes,8,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionQuote) Reset() {
	*x = OptionQuote{}
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionQuote) ProtoMessage() {}

func (x *OptionQuote) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionQuote.ProtoReflect.Descriptor instead.
func (*OptionQuote) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_option_quotes_proto_rawDescGZIP(), []int{0}
}

func (x *OptionQuote) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

func (x *OptionQuote) GetAx() string {
	if x != nil {
		return x.Ax
	}
	return ""
}

func (x *OptionQuote) GetAp() float64 {
	if x != nil {
		return x.Ap
	}
	return 0
}

func (x *OptionQuote) GetAs() int64 {
	if x != nil {
		return x.As
	}
	return 0
}

func (x *OptionQuote) GetBx() string {
	if x != nil {
		return x.Bx
	}
	return ""
}

func (x *OptionQuote) GetBp() float64 {
	if x != nil {
		return x.Bp
	}
	return 0
}

func (x *OptionQuote) GetBs() int64 {
	if x != nil {
		return x.Bs
	}
	return 0
}

func (x *OptionQuote) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

// GetOptionQuotesRequest is the request to get historical option quotes.
type GetOptionQuotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Comma-separated list of option symbols.
	Symbols string `protobuf:"bytes,1,opt,name=symbols,proto3" json:"symbols,omitempty"`
	// Start timestamp (RFC 3339 or YYYY-MM-DD).
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// End timestamp (RFC 3339 or YYYY-MM-DD).
	End string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	// Maximum number of quotes to return (1-10000, default 1000).
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Page token for pagination.
	PageToken string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Sort order (asc, desc).
	Sort          string `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOptionQuotesRequest) Reset() {
	*x = GetOptionQuotesRequest{}
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptionQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptionQuotesRequest) ProtoMessage() {}

func (x *GetOptionQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptionQuotesRequest.ProtoReflect.Descriptor instead.
func (*GetOptionQuotesRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_option_quotes_proto_rawDescGZIP(), []int{1}
}

func (x *GetOptionQuotesRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

func (x *GetOptionQuotesRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetOptionQuotesRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetOptionQuotesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOptionQuotesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetOptionQuotesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

// OptionQuotesList is a list of quotes for a single option symbol.
type OptionQuotesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotes        []*OptionQuote         `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionQuotesList) Reset() {
	*x = OptionQuotesList{}
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionQuotesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionQuotesList) ProtoMessage() {}

func (x *OptionQuotesList) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionQuotesList.ProtoReflect.Descriptor instead.
func (*OptionQuotesList) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_option_quotes_proto_rawDescGZIP(), []int{2}
}

func (x *OptionQuotesList) GetQuotes() []*OptionQuote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

// GetOptionQuotesResponse is the response containing option quotes.
type GetOptionQuotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to quotes.
	Quotes map[string]*OptionQuotesList `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Next page token.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOptionQuotesResponse) Reset() {
	*x = GetOptionQuotesResponse{}
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOptionQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOptionQuotesResponse) ProtoMessage() {}

func (x *GetOptionQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOptionQuotesResponse.ProtoReflect.Descriptor instead.
func (*GetOptionQuotesResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_option_quotes_proto_rawDescGZIP(), []int{3}
}

func (x *GetOptionQuotesResponse) GetQuotes() map[string]*OptionQuotesList {
	if x != nil {
		return x.Quotes
	}
	return nil
}

func (x *GetOptionQuotesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetLatestOptionQuotesRequest is the request to get the latest option quotes.
type GetLatestOptionQuotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Comma-separated list of option symbols.
	Symbols string `protobuf:"bytes,1,opt,name=symbols,proto3" json:"symbols,omitempty"`
	// Data feed (indicative, opra).
	Feed          string `protobuf:"bytes,2,opt,name=feed,proto3" json:"feed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestOptionQuotesRequest) Reset() {
	*x = GetLatestOptionQuotesRequest{}
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestOptionQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestOptionQuotesRequest) ProtoMessage() {}

func (x *GetLatestOptionQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestOptionQuotesRequest.ProtoReflect.Descriptor instead.
func (*GetLatestOptionQuotesRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_option_quotes_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestOptionQuotesRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

func (x *GetLatestOptionQuotesRequest) GetFeed() string {
	if x != nil {
		return x.Feed
	}
	return ""
}

// GetLatestOptionQuotesResponse is the response containing the latest option quotes.
type GetLatestOptionQuotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to latest quote.
	Quotes        map[string]*OptionQuote `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestOptionQuotesResponse) Reset() {
	*x = GetLatestOptionQuotesResponse{}
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestOptionQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestOptionQuotesResponse) ProtoMessage() {}

func (x *GetLatestOptionQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_option_quotes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestOptionQuotesResponse.ProtoReflect.Descriptor instead.
func (*GetLatestOptionQuotesResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_option_quotes_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestOptionQuotesResponse) GetQuotes() map[string]*OptionQuote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

var File_alpaca_marketdata_v2_option_quotes_proto protoreflect.FileDescriptor

const file_alpaca_marketdata_v2_option_quotes_proto_rawDesc = "" +
	"\n" +
	"(alpaca/marketdata/v2/option_quotes.proto\x12\x14alpaca.marketdata.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"\xf3\x01\n" +
	"\vOptionQuote\x12/\n" +
	"\x01t\x18\x01 \x01(\tB!\xba\xb5\x18\x1d\n" +
	"\x1b2024-01-15T10:30:00.123456ZR\x01t\x12\x17\n" +
	"\x02ax\x18\x02 \x01(\tB\a\xba\xb5\x18\x03\n" +
	"\x01CR\x02ax\x12\x1a\n" +
	"\x02ap\x18\x03 \x01(\x01B\n" +
	"\xba\xb5\x18\x06\n" +
	"\x045.30R\x02ap\x12\x18\n" +
	"\x02as\x18\x04 \x01(\x03B\b\xba\xb5\x18\x04\n" +
	"\x0250R\x02as\x12\x17\n" +
	"\x02bx\x18\x05 \x01(\tB\a\xba\xb5\x18\x03\n" +
	"\x01PR\x02bx\x12\x1a\n" +
	"\x02bp\x18\x06 \x01(\x01B\n" +
	"\xba\xb5\x18\x06\n" +
	"\x045.20R\x02bp\x12\x18\n" +
	"\x02bs\x18\a \x01(\x03B\b\xba\xb5\x18\x04\n" +
	"\x0230R\x02bs\x12\x15\n" +
	"\x01c\x18\b \x01(\tB\a\xba\xb5\x18\x03\n" +
	"\x01RR\x01c\"\xf3\x02\n" +
	"\x16GetOptionQuotesRequest\x12F\n" +
	"\asymbols\x18\x01 \x01(\tB,\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x15\n" +
	"\x13AAPL240119C00150000µ\x18\t\n" +
	"\asymbolsR\asymbols\x12;\n" +
	"\x05start\x18\x02 \x01(\tB%\xba\xb5\x18\x16\n" +
	"\x142024-01-15T09:30:00Zµ\x18\a\n" +
	"\x05startR\x05start\x125\n" +
	"\x03end\x18\x03 \x01(\tB#\xba\xb5\x18\x16\n" +
	"\x142024-01-15T16:00:00Zµ\x18\x05\n" +
	"\x03endR\x03end\x125\n" +
	"\x05limit\x18\x04 \x01(\x05B\x1f\xbaH\a\x1a\x05\x18\x90N(\x01\xba\xb5\x18\x06\n" +
	"\x041000µ\x18\a\n" +
	"\x05limitR\x05limit\x12=\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tB\x1e\xba\xb5\x18\n" +
	"\n" +
	"\btoken123µ\x18\f\n" +
	"\n" +
	"page_tokenR\tpageToken\x12'\n" +
	"\x04sort\x18\x06 \x01(\tB\x13\xba\xb5\x18\x05\n" +
	"\x03ascµ\x18\x06\n" +
	"\x04sortR\x04sort\"M\n" +
	"\x10OptionQuotesList\x129\n" +
	"\x06quotes\x18\x01 \x03(\v2!.alpaca.marketdata.v2.OptionQuoteR\x06quotes\"\x87\x02\n" +
	"\x17GetOptionQuotesResponse\x12Q\n" +
	"\x06quotes\x18\x01 \x03(\v29.alpaca.marketdata.v2.GetOptionQuotesResponse.QuotesEntryR\x06quotes\x126\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\bYWJjZGVmR\rnextPageToken\x1aa\n" +
	"\vQuotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.alpaca.marketdata.v2.OptionQuotesListR\x05value:\x028\x01\"\x90\x01\n" +
	"\x1cGetLatestOptionQuotesRequest\x12F\n" +
	"\asymbols\x18\x01 \x01(\tB,\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x15\n" +
	"\x13AAPL240119C00150000µ\x18\t\n" +
	"\asymbolsR\asymbols\x12(\n" +
	"\x04feed\x18\x02 \x01(\tB\x14\xba\xb5\x18\x06\n" +
	"\x04opraµ\x18\x06\n" +
	"\x04feedR\x04feed\"\xd6\x01\n" +
	"\x1dGetLatestOptionQuotesResponse\x12W\n" +
	"\x06quotes\x18\x01 \x03(\v2?.alpaca.marketdata.v2.GetLatestOptionQuotesResponse.QuotesEntryR\x06quotes\x1a\\\n" +
	"\vQuotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.alpaca.marketdata.v2.OptionQuoteR\x05value:\x028\x01B\xea\x01\n" +
	"\x18com.alpaca.marketdata.v2B\x11OptionQuotesProtoP\x01ZIgithub.com/sebastienmelki/alpaca-go/api/alpaca/marketdata/v2;marketdatav2\xa2\x02\x03AMX\xaa\x02\x14Alpaca.Marketdata.V2\xca\x02\x14Alpaca\\Marketdata\\V2\xe2\x02 Alpaca\\Marketdata\\V2\\GPBMetadata\xea\x02\x16Alpaca::Marketdata::V2b\x06proto3"

var (
	file_alpaca_marketdata_v2_option_quotes_proto_rawDescOnce sync.Once
	file_alpaca_marketdata_v2_option_quotes_proto_rawDescData []byte
)

func file_alpaca_marketdata_v2_option_quotes_proto_rawDescGZIP() []byte {
	file_alpaca_marketdata_v2_option_quotes_proto_rawDescOnce.Do(func() {
		file_alpaca_marketdata_v2_option_quotes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_option_quotes_proto_rawDesc), len(file_alpaca_marketdata_v2_option_quotes_proto_rawDesc)))
	})
	return file_alpaca_marketdata_v2_option_quotes_proto_rawDescData
}

var file_alpaca_marketdata_v2_option_quotes_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_alpaca_marketdata_v2_option_quotes_proto_goTypes = []any{
	(*OptionQuote)(nil),                   // 0: alpaca.marketdata.v2.OptionQuote
	(*GetOptionQuotesRequest)(nil),        // 1: alpaca.marketdata.v2.GetOptionQuotesRequest
	(*OptionQuotesList)(nil),              // 2: alpaca.marketdata.v2.OptionQuotesList
	(*GetOptionQuotesResponse)(nil),       // 3: alpaca.marketdata.v2.GetOptionQuotesResponse
	(*GetLatestOptionQuotesRequest)(nil),  // 4: alpaca.marketdata.v2.GetLatestOptionQuotesRequest
	(*GetLatestOptionQuotesResponse)(nil), // 5: alpaca.marketdata.v2.GetLatestOptionQuotesResponse
	nil,                                   // 6: alpaca.marketdata.v2.GetOptionQuotesResponse.QuotesEntry
	nil,                                   // 7: alpaca.marketdata.v2.GetLatestOptionQuotesResponse.QuotesEntry
}
var file_alpaca_marketdata_v2_option_quotes_proto_depIdxs = []int32{
	0, // 0: alpaca.marketdata.v2.OptionQuotesList.quotes:type_name -> alpaca.marketdata.v2.OptionQuote
	6, // 1: alpaca.marketdata.v2.GetOptionQuotesResponse.quotes:type_name -> alpaca.marketdata.v2.GetOptionQuotesResponse.QuotesEntry
	7, // 2: alpaca.marketdata.v2.GetLatestOptionQuotesResponse.quotes:type_name -> alpaca.marketdata.v2.GetLatestOptionQuotesResponse.QuotesEntry
	2, // 3: alpaca.marketdata.v2.GetOptionQuotesResponse.QuotesEntry.value:type_name -> alpaca.marketdata.v2.OptionQuotesList
	0, // 4: alpaca.marketdata.v2.GetLatestOptionQuotesResponse.QuotesEntry.value:type_name -> alpaca.marketdata.v2.OptionQuote
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_alpaca_marketdata_v2_option_quotes_proto_init() }
func file_alpaca_marketdata_v2_option_quotes_proto_init() {
	if File_alpaca_marketdata_v2_option_quotes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_option_quotes_proto_rawDesc), len(file_alpaca_marketdata_v2_option_quotes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_marketdata_v2_option_quotes_proto_goTypes,
		DependencyIndexes: file_alpaca_marketdata_v2_option_quotes_proto_depIdxs,
		MessageInfos:      file_alpaca_marketdata_v2_option_quotes_proto_msgTypes,
	}.Build()
	File_alpaca_marketdata_v2_option_quotes_proto = out.File
	file_alpaca_marketdata_v2_option_quotes_proto_goTypes = nil
	file_alpaca_marketdata_v2_option_quotes_proto_depIdxs = nil
}
