// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/marketdata/v2/screener.proto

package marketdatav2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MostActive represents a most active stock.
type MostActive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Symbol.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Trading volume.
	Volume int64 `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
	// Trade count.
	TradeCount    int64 `protobuf:"varint,3,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostActive) Reset() {
	*x = MostActive{}
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostActive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostActive) ProtoMessage() {}

func (x *MostActive) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostActive.ProtoReflect.Descriptor instead.
func (*MostActive) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_screener_proto_rawDescGZIP(), []int{0}
}

func (x *MostActive) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MostActive) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MostActive) GetTradeCount() int64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

// GetMostActivesRequest is the request to get most active stocks.
type GetMostActivesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of results to return (default 10, max 100).
	Top int32 `protobuf:"varint,1,opt,name=top,proto3" json:"top,omitempty"`
	// Ranking criteria (volume, trades).
	By            string `protobuf:"bytes,2,opt,name=by,proto3" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMostActivesRequest) Reset() {
	*x = GetMostActivesRequest{}
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMostActivesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostActivesRequest) ProtoMessage() {}

func (x *GetMostActivesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostActivesRequest.ProtoReflect.Descriptor instead.
func (*GetMostActivesRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_screener_proto_rawDescGZIP(), []int{1}
}

func (x *GetMostActivesRequest) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *GetMostActivesRequest) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

// GetMostActivesResponse is the response containing most active stocks.
type GetMostActivesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of most active stocks.
	MostActives []*MostActive `protobuf:"bytes,1,rep,name=most_actives,json=mostActives,proto3" json:"most_actives,omitempty"`
	// Timestamp when this data was last updated (RFC 3339).
	LastUpdated   string `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMostActivesResponse) Reset() {
	*x = GetMostActivesResponse{}
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMostActivesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMostActivesResponse) ProtoMessage() {}

func (x *GetMostActivesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMostActivesResponse.ProtoReflect.Descriptor instead.
func (*GetMostActivesResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_screener_proto_rawDescGZIP(), []int{2}
}

func (x *GetMostActivesResponse) GetMostActives() []*MostActive {
	if x != nil {
		return x.MostActives
	}
	return nil
}

func (x *GetMostActivesResponse) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

// Mover represents a top mover stock.
type Mover struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Symbol.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Percent change.
	PercentChange float64 `protobuf:"fixed64,2,opt,name=percent_change,json=percentChange,proto3" json:"percent_change,omitempty"`
	// Price change.
	Change float64 `protobuf:"fixed64,3,opt,name=change,proto3" json:"change,omitempty"`
	// Current price.
	Price         float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mover) Reset() {
	*x = Mover{}
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mover) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mover) ProtoMessage() {}

func (x *Mover) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mover.ProtoReflect.Descriptor instead.
func (*Mover) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_screener_proto_rawDescGZIP(), []int{3}
}

func (x *Mover) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Mover) GetPercentChange() float64 {
	if x != nil {
		return x.PercentChange
	}
	return 0
}

func (x *Mover) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *Mover) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// GetMoversRequest is the request to get top movers.
type GetMoversRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Market type (stocks, crypto).
	MarketType string `protobuf:"bytes,1,opt,name=market_type,json=marketType,proto3" json:"market_type,omitempty"`
	// Number of results to return (default 10, max 50).
	Top           int32 `protobuf:"varint,2,opt,name=top,proto3" json:"top,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoversRequest) Reset() {
	*x = GetMoversRequest{}
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoversRequest) ProtoMessage() {}

func (x *GetMoversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoversRequest.ProtoReflect.Descriptor instead.
func (*GetMoversRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_screener_proto_rawDescGZIP(), []int{4}
}

func (x *GetMoversRequest) GetMarketType() string {
	if x != nil {
		return x.MarketType
	}
	return ""
}

func (x *GetMoversRequest) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

// GetMoversResponse is the response containing top movers.
type GetMoversResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of top gainers.
	Gainers []*Mover `protobuf:"bytes,1,rep,name=gainers,proto3" json:"gainers,omitempty"`
	// List of top losers.
	Losers []*Mover `protobuf:"bytes,2,rep,name=losers,proto3" json:"losers,omitempty"`
	// Market type.
	MarketType string `protobuf:"bytes,3,opt,name=market_type,json=marketType,proto3" json:"market_type,omitempty"`
	// Timestamp when this data was last updated (RFC 3339).
	LastUpdated   string `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoversResponse) Reset() {
	*x = GetMoversResponse{}
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoversResponse) ProtoMessage() {}

func (x *GetMoversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_screener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoversResponse.ProtoReflect.Descriptor instead.
func (*GetMoversResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_screener_proto_rawDescGZIP(), []int{5}
}

func (x *GetMoversResponse) GetGainers() []*Mover {
	if x != nil {
		return x.Gainers
	}
	return nil
}

func (x *GetMoversResponse) GetLosers() []*Mover {
	if x != nil {
		return x.Losers
	}
	return nil
}

func (x *GetMoversResponse) GetMarketType() string {
	if x != nil {
		return x.MarketType
	}
	return ""
}

func (x *GetMoversResponse) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

var File_alpaca_marketdata_v2_screener_proto protoreflect.FileDescriptor

const file_alpaca_marketdata_v2_screener_proto_rawDesc = "" +
	"\n" +
	"#alpaca/marketdata/v2/screener.proto\x12\x14alpaca.marketdata.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"\x87\x01\n" +
	"\n" +
	"MostActive\x12\"\n" +
	"\x06symbol\x18\x01 \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x04AAPLR\x06symbol\x12'\n" +
	"\x06volume\x18\x02 \x01(\x03B\x0f\xba\xb5\x18\v\n" +
	"\t123456789R\x06volume\x12,\n" +
	"\vtrade_count\x18\x03 \x01(\x03B\v\xba\xb5\x18\a\n" +
	"\x0554321R\n" +
	"tradeCount\"k\n" +
	"\x15GetMostActivesRequest\x12,\n" +
	"\x03top\x18\x01 \x01(\x05B\x1a\xbaH\x06\x1a\x04\x18d(\x01\xba\xb5\x18\x04\n" +
	"\x0210µ\x18\x05\n" +
	"\x03topR\x03top\x12$\n" +
	"\x02by\x18\x02 \x01(\tB\x14\xba\xb5\x18\b\n" +
	"\x06volumeµ\x18\x04\n" +
	"\x02byR\x02by\"\x9c\x01\n" +
	"\x16GetMostActivesResponse\x12C\n" +
	"\fmost_actives\x18\x01 \x03(\v2 .alpaca.marketdata.v2.MostActiveR\vmostActives\x12=\n" +
	"\flast_updated\x18\x02 \x01(\tB\x1a\xba\xb5\x18\x16\n" +
	"\x142024-01-15T16:00:00ZR\vlastUpdated\"\xa6\x01\n" +
	"\x05Mover\x12\"\n" +
	"\x06symbol\x18\x01 \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x04AAPLR\x06symbol\x121\n" +
	"\x0epercent_change\x18\x02 \x01(\x01B\n" +
	"\xba\xb5\x18\x06\n" +
	"\x045.25R\rpercentChange\x12\"\n" +
	"\x06change\x18\x03 \x01(\x01B\n" +
	"\xba\xb5\x18\x06\n" +
	"\x047.50R\x06change\x12\"\n" +
	"\x05price\x18\x04 \x01(\x01B\f\xba\xb5\x18\b\n" +
	"\x06150.25R\x05price\"u\n" +
	"\x10GetMoversRequest\x123\n" +
	"\vmarket_type\x18\x01 \x01(\tB\x12\xbaH\x03\xc8\x01\x01\xba\xb5\x18\b\n" +
	"\x06stocksR\n" +
	"marketType\x12,\n" +
	"\x03top\x18\x02 \x01(\x05B\x1a\xbaH\x06\x1a\x04\x182(\x01\xba\xb5\x18\x04\n" +
	"\x0210µ\x18\x05\n" +
	"\x03topR\x03top\"\xed\x01\n" +
	"\x11GetMoversResponse\x125\n" +
	"\againers\x18\x01 \x03(\v2\x1b.alpaca.marketdata.v2.MoverR\againers\x123\n" +
	"\x06losers\x18\x02 \x03(\v2\x1b.alpaca.marketdata.v2.MoverR\x06losers\x12-\n" +
	"\vmarket_type\x18\x03 \x01(\tB\f\xba\xb5\x18\b\n" +
	"\x06stocksR\n" +
	"marketType\x12=\n" +
	"\flast_updated\x18\x04 \x01(\tB\x1a\xba\xb5\x18\x16\n" +
	"\x142024-01-15T16:00:00ZR\vlastUpdatedB\xe6\x01\n" +
	"\x18com.alpaca.marketdata.v2B\rScreenerProtoP\x01ZIgithub.com/sebastienmelki/alpaca-go/api/alpaca/marketdata/v2;marketdatav2\xa2\x02\x03AMX\xaa\x02\x14Alpaca.Marketdata.V2\xca\x02\x14Alpaca\\Marketdata\\V2\xe2\x02 Alpaca\\Marketdata\\V2\\GPBMetadata\xea\x02\x16Alpaca::Marketdata::V2b\x06proto3"

var (
	file_alpaca_marketdata_v2_screener_proto_rawDescOnce sync.Once
	file_alpaca_marketdata_v2_screener_proto_rawDescData []byte
)

func file_alpaca_marketdata_v2_screener_proto_rawDescGZIP() []byte {
	file_alpaca_marketdata_v2_screener_proto_rawDescOnce.Do(func() {
		file_alpaca_marketdata_v2_screener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_screener_proto_rawDesc), len(file_alpaca_marketdata_v2_screener_proto_rawDesc)))
	})
	return file_alpaca_marketdata_v2_screener_proto_rawDescData
}

var file_alpaca_marketdata_v2_screener_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_alpaca_marketdata_v2_screener_proto_goTypes = []any{
	(*MostActive)(nil),             // 0: alpaca.marketdata.v2.MostActive
	(*GetMostActivesRequest)(nil),  // 1: alpaca.marketdata.v2.GetMostActivesRequest
	(*GetMostActivesResponse)(nil), // 2: alpaca.marketdata.v2.GetMostActivesResponse
	(*Mover)(nil),                  // 3: alpaca.marketdata.v2.Mover
	(*GetMoversRequest)(nil),       // 4: alpaca.marketdata.v2.GetMoversRequest
	(*GetMoversResponse)(nil),      // 5: alpaca.marketdata.v2.GetMoversResponse
}
var file_alpaca_marketdata_v2_screener_proto_depIdxs = []int32{
	0, // 0: alpaca.marketdata.v2.GetMostActivesResponse.most_actives:type_name -> alpaca.marketdata.v2.MostActive
	3, // 1: alpaca.marketdata.v2.GetMoversResponse.gainers:type_name -> alpaca.marketdata.v2.Mover
	3, // 2: alpaca.marketdata.v2.GetMoversResponse.losers:type_name -> alpaca.marketdata.v2.Mover
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_alpaca_marketdata_v2_screener_proto_init() }
func file_alpaca_marketdata_v2_screener_proto_init() {
	if File_alpaca_marketdata_v2_screener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_screener_proto_rawDesc), len(file_alpaca_marketdata_v2_screener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_marketdata_v2_screener_proto_goTypes,
		DependencyIndexes: file_alpaca_marketdata_v2_screener_proto_depIdxs,
		MessageInfos:      file_alpaca_marketdata_v2_screener_proto_msgTypes,
	}.Build()
	File_alpaca_marketdata_v2_screener_proto = out.File
	file_alpaca_marketdata_v2_screener_proto_goTypes = nil
	file_alpaca_marketdata_v2_screener_proto_depIdxs = nil
}
