// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/marketdata/v2/stock_bars.proto

package marketdatav2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetStockBarsRequest is the request to get historical stock bars.
type GetStockBarsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Comma-separated list of symbols.
	Symbols string `protobuf:"bytes,1,opt,name=symbols,proto3" json:"symbols,omitempty"`
	// Bar timeframe (1Min, 5Min, 15Min, 30Min, 1Hour, 4Hour, 1Day, 1Week, 1Month).
	Timeframe string `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	// Start timestamp (RFC 3339 or YYYY-MM-DD).
	Start string `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	// End timestamp (RFC 3339 or YYYY-MM-DD).
	End string `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	// Maximum number of bars to return (1-10000, default 1000).
	Limit int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	// Adjustment type (raw, split, dividend, all).
	Adjustment string `protobuf:"bytes,6,opt,name=adjustment,proto3" json:"adjustment,omitempty"`
	// Data feed (iex, sip).
	Feed string `protobuf:"bytes,7,opt,name=feed,proto3" json:"feed,omitempty"`
	// Page token for pagination.
	PageToken string `protobuf:"bytes,8,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Sort order (asc, desc).
	Sort          string `protobuf:"bytes,9,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockBarsRequest) Reset() {
	*x = GetStockBarsRequest{}
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockBarsRequest) ProtoMessage() {}

func (x *GetStockBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockBarsRequest.ProtoReflect.Descriptor instead.
func (*GetStockBarsRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_bars_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockBarsRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

func (x *GetStockBarsRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *GetStockBarsRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetStockBarsRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetStockBarsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetStockBarsRequest) GetAdjustment() string {
	if x != nil {
		return x.Adjustment
	}
	return ""
}

func (x *GetStockBarsRequest) GetFeed() string {
	if x != nil {
		return x.Feed
	}
	return ""
}

func (x *GetStockBarsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetStockBarsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

// StockBarsMap is a map of symbol to bars.
type StockBarsMap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to list of bars.
	Bars          map[string]*StockBarsList `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockBarsMap) Reset() {
	*x = StockBarsMap{}
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockBarsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockBarsMap) ProtoMessage() {}

func (x *StockBarsMap) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockBarsMap.ProtoReflect.Descriptor instead.
func (*StockBarsMap) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_bars_proto_rawDescGZIP(), []int{1}
}

func (x *StockBarsMap) GetBars() map[string]*StockBarsList {
	if x != nil {
		return x.Bars
	}
	return nil
}

// StockBarsList is a list of bars for a single symbol.
type StockBarsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bars          []*Bar                 `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockBarsList) Reset() {
	*x = StockBarsList{}
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockBarsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockBarsList) ProtoMessage() {}

func (x *StockBarsList) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockBarsList.ProtoReflect.Descriptor instead.
func (*StockBarsList) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_bars_proto_rawDescGZIP(), []int{2}
}

func (x *StockBarsList) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

// GetStockBarsResponse is the response containing stock bars.
type GetStockBarsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to bars.
	Bars map[string]*StockBarsList `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Next page token.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockBarsResponse) Reset() {
	*x = GetStockBarsResponse{}
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockBarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockBarsResponse) ProtoMessage() {}

func (x *GetStockBarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockBarsResponse.ProtoReflect.Descriptor instead.
func (*GetStockBarsResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_bars_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockBarsResponse) GetBars() map[string]*StockBarsList {
	if x != nil {
		return x.Bars
	}
	return nil
}

func (x *GetStockBarsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetLatestStockBarsRequest is the request to get the latest stock bars.
type GetLatestStockBarsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Comma-separated list of symbols.
	Symbols string `protobuf:"bytes,1,opt,name=symbols,proto3" json:"symbols,omitempty"`
	// Data feed (iex, sip).
	Feed string `protobuf:"bytes,2,opt,name=feed,proto3" json:"feed,omitempty"`
	// Currency for the response prices.
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestStockBarsRequest) Reset() {
	*x = GetLatestStockBarsRequest{}
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestStockBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestStockBarsRequest) ProtoMessage() {}

func (x *GetLatestStockBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestStockBarsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestStockBarsRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_bars_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestStockBarsRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

func (x *GetLatestStockBarsRequest) GetFeed() string {
	if x != nil {
		return x.Feed
	}
	return ""
}

func (x *GetLatestStockBarsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// GetLatestStockBarsResponse is the response containing the latest stock bars.
type GetLatestStockBarsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to latest bar.
	Bars          map[string]*Bar `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestStockBarsResponse) Reset() {
	*x = GetLatestStockBarsResponse{}
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestStockBarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestStockBarsResponse) ProtoMessage() {}

func (x *GetLatestStockBarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_bars_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestStockBarsResponse.ProtoReflect.Descriptor instead.
func (*GetLatestStockBarsResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_bars_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestStockBarsResponse) GetBars() map[string]*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

var File_alpaca_marketdata_v2_stock_bars_proto protoreflect.FileDescriptor

const file_alpaca_marketdata_v2_stock_bars_proto_rawDesc = "" +
	"\n" +
	"%alpaca/marketdata/v2/stock_bars.proto\x12\x14alpaca.marketdata.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a!alpaca/marketdata/v2/common.proto\"\xfa\x03\n" +
	"\x13GetStockBarsRequest\x12A\n" +
	"\asymbols\x18\x01 \x01(\tB'\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x10\n" +
	"\x0eAAPL,TSLA,MSFTµ\x18\t\n" +
	"\asymbolsR\asymbols\x12=\n" +
	"\ttimeframe\x18\x02 \x01(\tB\x1f\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x06\n" +
	"\x041Dayµ\x18\v\n" +
	"\ttimeframeR\ttimeframe\x121\n" +
	"\x05start\x18\x03 \x01(\tB\x1b\xba\xb5\x18\f\n" +
	"\n" +
	"2024-01-01µ\x18\a\n" +
	"\x05startR\x05start\x12+\n" +
	"\x03end\x18\x04 \x01(\tB\x19\xba\xb5\x18\f\n" +
	"\n" +
	"2024-01-31µ\x18\x05\n" +
	"\x03endR\x03end\x125\n" +
	"\x05limit\x18\x05 \x01(\x05B\x1f\xbaH\a\x1a\x05\x18\x90N(\x01\xba\xb5\x18\x06\n" +
	"\x041000µ\x18\a\n" +
	"\x05limitR\x05limit\x129\n" +
	"\n" +
	"adjustment\x18\x06 \x01(\tB\x19\xba\xb5\x18\x05\n" +
	"\x03rawµ\x18\f\n" +
	"\n" +
	"adjustmentR\n" +
	"adjustment\x12'\n" +
	"\x04feed\x18\a \x01(\tB\x13\xba\xb5\x18\x05\n" +
	"\x03sipµ\x18\x06\n" +
	"\x04feedR\x04feed\x12=\n" +
	"\n" +
	"page_token\x18\b \x01(\tB\x1e\xba\xb5\x18\n" +
	"\n" +
	"\btoken123µ\x18\f\n" +
	"\n" +
	"page_tokenR\tpageToken\x12'\n" +
	"\x04sort\x18\t \x01(\tB\x13\xba\xb5\x18\x05\n" +
	"\x03ascµ\x18\x06\n" +
	"\x04sortR\x04sort\"\xae\x01\n" +
	"\fStockBarsMap\x12@\n" +
	"\x04bars\x18\x01 \x03(\v2,.alpaca.marketdata.v2.StockBarsMap.BarsEntryR\x04bars\x1a\\\n" +
	"\tBarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.alpaca.marketdata.v2.StockBarsListR\x05value:\x028\x01\">\n" +
	"\rStockBarsList\x12-\n" +
	"\x04bars\x18\x01 \x03(\v2\x19.alpaca.marketdata.v2.BarR\x04bars\"\xf6\x01\n" +
	"\x14GetStockBarsResponse\x12H\n" +
	"\x04bars\x18\x01 \x03(\v24.alpaca.marketdata.v2.GetStockBarsResponse.BarsEntryR\x04bars\x126\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\bYWJjZGVmR\rnextPageToken\x1a\\\n" +
	"\tBarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.alpaca.marketdata.v2.StockBarsListR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x19GetLatestStockBarsRequest\x12A\n" +
	"\asymbols\x18\x01 \x01(\tB'\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x10\n" +
	"\x0eAAPL,TSLA,MSFTµ\x18\t\n" +
	"\asymbolsR\asymbols\x12'\n" +
	"\x04feed\x18\x02 \x01(\tB\x13\xba\xb5\x18\x05\n" +
	"\x03sipµ\x18\x06\n" +
	"\x04feedR\x04feed\x123\n" +
	"\bcurrency\x18\x03 \x01(\tB\x17\xba\xb5\x18\x05\n" +
	"\x03USDµ\x18\n" +
	"\n" +
	"\bcurrencyR\bcurrency\"\xc0\x01\n" +
	"\x1aGetLatestStockBarsResponse\x12N\n" +
	"\x04bars\x18\x01 \x03(\v2:.alpaca.marketdata.v2.GetLatestStockBarsResponse.BarsEntryR\x04bars\x1aR\n" +
	"\tBarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.alpaca.marketdata.v2.BarR\x05value:\x028\x01B\xe7\x01\n" +
	"\x18com.alpaca.marketdata.v2B\x0eStockBarsProtoP\x01ZIgithub.com/sebastienmelki/alpaca-go/api/alpaca/marketdata/v2;marketdatav2\xa2\x02\x03AMX\xaa\x02\x14Alpaca.Marketdata.V2\xca\x02\x14Alpaca\\Marketdata\\V2\xe2\x02 Alpaca\\Marketdata\\V2\\GPBMetadata\xea\x02\x16Alpaca::Marketdata::V2b\x06proto3"

var (
	file_alpaca_marketdata_v2_stock_bars_proto_rawDescOnce sync.Once
	file_alpaca_marketdata_v2_stock_bars_proto_rawDescData []byte
)

func file_alpaca_marketdata_v2_stock_bars_proto_rawDescGZIP() []byte {
	file_alpaca_marketdata_v2_stock_bars_proto_rawDescOnce.Do(func() {
		file_alpaca_marketdata_v2_stock_bars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_stock_bars_proto_rawDesc), len(file_alpaca_marketdata_v2_stock_bars_proto_rawDesc)))
	})
	return file_alpaca_marketdata_v2_stock_bars_proto_rawDescData
}

var file_alpaca_marketdata_v2_stock_bars_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_alpaca_marketdata_v2_stock_bars_proto_goTypes = []any{
	(*GetStockBarsRequest)(nil),        // 0: alpaca.marketdata.v2.GetStockBarsRequest
	(*StockBarsMap)(nil),               // 1: alpaca.marketdata.v2.StockBarsMap
	(*StockBarsList)(nil),              // 2: alpaca.marketdata.v2.StockBarsList
	(*GetStockBarsResponse)(nil),       // 3: alpaca.marketdata.v2.GetStockBarsResponse
	(*GetLatestStockBarsRequest)(nil),  // 4: alpaca.marketdata.v2.GetLatestStockBarsRequest
	(*GetLatestStockBarsResponse)(nil), // 5: alpaca.marketdata.v2.GetLatestStockBarsResponse
	nil,                                // 6: alpaca.marketdata.v2.StockBarsMap.BarsEntry
	nil,                                // 7: alpaca.marketdata.v2.GetStockBarsResponse.BarsEntry
	nil,                                // 8: alpaca.marketdata.v2.GetLatestStockBarsResponse.BarsEntry
	(*Bar)(nil),                        // 9: alpaca.marketdata.v2.Bar
}
var file_alpaca_marketdata_v2_stock_bars_proto_depIdxs = []int32{
	6, // 0: alpaca.marketdata.v2.StockBarsMap.bars:type_name -> alpaca.marketdata.v2.StockBarsMap.BarsEntry
	9, // 1: alpaca.marketdata.v2.StockBarsList.bars:type_name -> alpaca.marketdata.v2.Bar
	7, // 2: alpaca.marketdata.v2.GetStockBarsResponse.bars:type_name -> alpaca.marketdata.v2.GetStockBarsResponse.BarsEntry
	8, // 3: alpaca.marketdata.v2.GetLatestStockBarsResponse.bars:type_name -> alpaca.marketdata.v2.GetLatestStockBarsResponse.BarsEntry
	2, // 4: alpaca.marketdata.v2.StockBarsMap.BarsEntry.value:type_name -> alpaca.marketdata.v2.StockBarsList
	2, // 5: alpaca.marketdata.v2.GetStockBarsResponse.BarsEntry.value:type_name -> alpaca.marketdata.v2.StockBarsList
	9, // 6: alpaca.marketdata.v2.GetLatestStockBarsResponse.BarsEntry.value:type_name -> alpaca.marketdata.v2.Bar
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_alpaca_marketdata_v2_stock_bars_proto_init() }
func file_alpaca_marketdata_v2_stock_bars_proto_init() {
	if File_alpaca_marketdata_v2_stock_bars_proto != nil {
		return
	}
	file_alpaca_marketdata_v2_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_stock_bars_proto_rawDesc), len(file_alpaca_marketdata_v2_stock_bars_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_marketdata_v2_stock_bars_proto_goTypes,
		DependencyIndexes: file_alpaca_marketdata_v2_stock_bars_proto_depIdxs,
		MessageInfos:      file_alpaca_marketdata_v2_stock_bars_proto_msgTypes,
	}.Build()
	File_alpaca_marketdata_v2_stock_bars_proto = out.File
	file_alpaca_marketdata_v2_stock_bars_proto_goTypes = nil
	file_alpaca_marketdata_v2_stock_bars_proto_depIdxs = nil
}
