// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/marketdata/v2/stock_auctions.proto

package marketdatav2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Auction represents an auction event.
type Auction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp (RFC 3339).
	T string `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	// Auction price.
	P float64 `protobuf:"fixed64,2,opt,name=p,proto3" json:"p,omitempty"`
	// Auction size.
	S int64 `protobuf:"varint,3,opt,name=s,proto3" json:"s,omitempty"`
	// Exchange code.
	X string `protobuf:"bytes,4,opt,name=x,proto3" json:"x,omitempty"`
	// Auction condition.
	C             string `protobuf:"bytes,5,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_auctions_proto_rawDescGZIP(), []int{0}
}

func (x *Auction) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

func (x *Auction) GetP() float64 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *Auction) GetS() int64 {
	if x != nil {
		return x.S
	}
	return 0
}

func (x *Auction) GetX() string {
	if x != nil {
		return x.X
	}
	return ""
}

func (x *Auction) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

// DailyAuctions represents opening and closing auctions for a day.
type DailyAuctions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date (YYYY-MM-DD).
	D string `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	// Opening auction.
	O []*Auction `protobuf:"bytes,2,rep,name=o,proto3" json:"o,omitempty"`
	// Closing auction.
	C             []*Auction `protobuf:"bytes,3,rep,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyAuctions) Reset() {
	*x = DailyAuctions{}
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyAuctions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyAuctions) ProtoMessage() {}

func (x *DailyAuctions) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyAuctions.ProtoReflect.Descriptor instead.
func (*DailyAuctions) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_auctions_proto_rawDescGZIP(), []int{1}
}

func (x *DailyAuctions) GetD() string {
	if x != nil {
		return x.D
	}
	return ""
}

func (x *DailyAuctions) GetO() []*Auction {
	if x != nil {
		return x.O
	}
	return nil
}

func (x *DailyAuctions) GetC() []*Auction {
	if x != nil {
		return x.C
	}
	return nil
}

// GetStockAuctionsRequest is the request to get stock auctions.
type GetStockAuctionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Comma-separated list of symbols.
	Symbols string `protobuf:"bytes,1,opt,name=symbols,proto3" json:"symbols,omitempty"`
	// Start date (YYYY-MM-DD).
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// End date (YYYY-MM-DD).
	End string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	// Maximum number of results (1-10000, default 1000).
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Page token for pagination.
	PageToken string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Sort order (asc, desc).
	Sort          string `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockAuctionsRequest) Reset() {
	*x = GetStockAuctionsRequest{}
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockAuctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockAuctionsRequest) ProtoMessage() {}

func (x *GetStockAuctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockAuctionsRequest.ProtoReflect.Descriptor instead.
func (*GetStockAuctionsRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_auctions_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockAuctionsRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

func (x *GetStockAuctionsRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetStockAuctionsRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetStockAuctionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetStockAuctionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetStockAuctionsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

// StockAuctionsList is a list of daily auctions for a single symbol.
type StockAuctionsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auctions      []*DailyAuctions       `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockAuctionsList) Reset() {
	*x = StockAuctionsList{}
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockAuctionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockAuctionsList) ProtoMessage() {}

func (x *StockAuctionsList) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockAuctionsList.ProtoReflect.Descriptor instead.
func (*StockAuctionsList) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_auctions_proto_rawDescGZIP(), []int{3}
}

func (x *StockAuctionsList) GetAuctions() []*DailyAuctions {
	if x != nil {
		return x.Auctions
	}
	return nil
}

// GetStockAuctionsResponse is the response containing stock auctions.
type GetStockAuctionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to auctions.
	Auctions map[string]*StockAuctionsList `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Next page token.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockAuctionsResponse) Reset() {
	*x = GetStockAuctionsResponse{}
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockAuctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockAuctionsResponse) ProtoMessage() {}

func (x *GetStockAuctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockAuctionsResponse.ProtoReflect.Descriptor instead.
func (*GetStockAuctionsResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_auctions_proto_rawDescGZIP(), []int{4}
}

func (x *GetStockAuctionsResponse) GetAuctions() map[string]*StockAuctionsList {
	if x != nil {
		return x.Auctions
	}
	return nil
}

func (x *GetStockAuctionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_alpaca_marketdata_v2_stock_auctions_proto protoreflect.FileDescriptor

const file_alpaca_marketdata_v2_stock_auctions_proto_rawDesc = "" +
	"\n" +
	")alpaca/marketdata/v2/stock_auctions.proto\x12\x14alpaca.marketdata.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"\x98\x01\n" +
	"\aAuction\x12(\n" +
	"\x01t\x18\x01 \x01(\tB\x1a\xba\xb5\x18\x16\n" +
	"\x142024-01-15T09:30:00ZR\x01t\x12\x1a\n" +
	"\x01p\x18\x02 \x01(\x01B\f\xba\xb5\x18\b\n" +
	"\x06150.25R\x01p\x12\x19\n" +
	"\x01s\x18\x03 \x01(\x03B\v\xba\xb5\x18\a\n" +
	"\x0510000R\x01s\x12\x15\n" +
	"\x01x\x18\x04 \x01(\tB\a\xba\xb5\x18\x03\n" +
	"\x01QR\x01x\x12\x15\n" +
	"\x01c\x18\x05 \x01(\tB\a\xba\xb5\x18\x03\n" +
	"\x01OR\x01c\"\x89\x01\n" +
	"\rDailyAuctions\x12\x1e\n" +
	"\x01d\x18\x01 \x01(\tB\x10\xba\xb5\x18\f\n" +
	"\n" +
	"2024-01-15R\x01d\x12+\n" +
	"\x01o\x18\x02 \x03(\v2\x1d.alpaca.marketdata.v2.AuctionR\x01o\x12+\n" +
	"\x01c\x18\x03 \x03(\v2\x1d.alpaca.marketdata.v2.AuctionR\x01c\"\xd6\x02\n" +
	"\x17GetStockAuctionsRequest\x12<\n" +
	"\asymbols\x18\x01 \x01(\tB\"\xbaH\x03\xc8\x01\x01\xba\xb5\x18\v\n" +
	"\tAAPL,TSLAµ\x18\t\n" +
	"\asymbolsR\asymbols\x121\n" +
	"\x05start\x18\x02 \x01(\tB\x1b\xba\xb5\x18\f\n" +
	"\n" +
	"2024-01-01µ\x18\a\n" +
	"\x05startR\x05start\x12+\n" +
	"\x03end\x18\x03 \x01(\tB\x19\xba\xb5\x18\f\n" +
	"\n" +
	"2024-01-31µ\x18\x05\n" +
	"\x03endR\x03end\x125\n" +
	"\x05limit\x18\x04 \x01(\x05B\x1f\xbaH\a\x1a\x05\x18\x90N(\x01\xba\xb5\x18\x06\n" +
	"\x041000µ\x18\a\n" +
	"\x05limitR\x05limit\x12=\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tB\x1e\xba\xb5\x18\n" +
	"\n" +
	"\btoken123µ\x18\f\n" +
	"\n" +
	"page_tokenR\tpageToken\x12'\n" +
	"\x04sort\x18\x06 \x01(\tB\x13\xba\xb5\x18\x05\n" +
	"\x03ascµ\x18\x06\n" +
	"\x04sortR\x04sort\"T\n" +
	"\x11StockAuctionsList\x12?\n" +
	"\bauctions\x18\x01 \x03(\v2#.alpaca.marketdata.v2.DailyAuctionsR\bauctions\"\x92\x02\n" +
	"\x18GetStockAuctionsResponse\x12X\n" +
	"\bauctions\x18\x01 \x03(\v2<.alpaca.marketdata.v2.GetStockAuctionsResponse.AuctionsEntryR\bauctions\x126\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\bYWJjZGVmR\rnextPageToken\x1ad\n" +
	"\rAuctionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.alpaca.marketdata.v2.StockAuctionsListR\x05value:\x028\x01B\xeb\x01\n" +
	"\x18com.alpaca.marketdata.v2B\x12StockAuctionsProtoP\x01ZIgithub.com/sebastienmelki/alpaca-go/api/alpaca/marketdata/v2;marketdatav2\xa2\x02\x03AMX\xaa\x02\x14Alpaca.Marketdata.V2\xca\x02\x14Alpaca\\Marketdata\\V2\xe2\x02 Alpaca\\Marketdata\\V2\\GPBMetadata\xea\x02\x16Alpaca::Marketdata::V2b\x06proto3"

var (
	file_alpaca_marketdata_v2_stock_auctions_proto_rawDescOnce sync.Once
	file_alpaca_marketdata_v2_stock_auctions_proto_rawDescData []byte
)

func file_alpaca_marketdata_v2_stock_auctions_proto_rawDescGZIP() []byte {
	file_alpaca_marketdata_v2_stock_auctions_proto_rawDescOnce.Do(func() {
		file_alpaca_marketdata_v2_stock_auctions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_stock_auctions_proto_rawDesc), len(file_alpaca_marketdata_v2_stock_auctions_proto_rawDesc)))
	})
	return file_alpaca_marketdata_v2_stock_auctions_proto_rawDescData
}

var file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_alpaca_marketdata_v2_stock_auctions_proto_goTypes = []any{
	(*Auction)(nil),                  // 0: alpaca.marketdata.v2.Auction
	(*DailyAuctions)(nil),            // 1: alpaca.marketdata.v2.DailyAuctions
	(*GetStockAuctionsRequest)(nil),  // 2: alpaca.marketdata.v2.GetStockAuctionsRequest
	(*StockAuctionsList)(nil),        // 3: alpaca.marketdata.v2.StockAuctionsList
	(*GetStockAuctionsResponse)(nil), // 4: alpaca.marketdata.v2.GetStockAuctionsResponse
	nil,                              // 5: alpaca.marketdata.v2.GetStockAuctionsResponse.AuctionsEntry
}
var file_alpaca_marketdata_v2_stock_auctions_proto_depIdxs = []int32{
	0, // 0: alpaca.marketdata.v2.DailyAuctions.o:type_name -> alpaca.marketdata.v2.Auction
	0, // 1: alpaca.marketdata.v2.DailyAuctions.c:type_name -> alpaca.marketdata.v2.Auction
	1, // 2: alpaca.marketdata.v2.StockAuctionsList.auctions:type_name -> alpaca.marketdata.v2.DailyAuctions
	5, // 3: alpaca.marketdata.v2.GetStockAuctionsResponse.auctions:type_name -> alpaca.marketdata.v2.GetStockAuctionsResponse.AuctionsEntry
	3, // 4: alpaca.marketdata.v2.GetStockAuctionsResponse.AuctionsEntry.value:type_name -> alpaca.marketdata.v2.StockAuctionsList
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_alpaca_marketdata_v2_stock_auctions_proto_init() }
func file_alpaca_marketdata_v2_stock_auctions_proto_init() {
	if File_alpaca_marketdata_v2_stock_auctions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_stock_auctions_proto_rawDesc), len(file_alpaca_marketdata_v2_stock_auctions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_marketdata_v2_stock_auctions_proto_goTypes,
		DependencyIndexes: file_alpaca_marketdata_v2_stock_auctions_proto_depIdxs,
		MessageInfos:      file_alpaca_marketdata_v2_stock_auctions_proto_msgTypes,
	}.Build()
	File_alpaca_marketdata_v2_stock_auctions_proto = out.File
	file_alpaca_marketdata_v2_stock_auctions_proto_goTypes = nil
	file_alpaca_marketdata_v2_stock_auctions_proto_depIdxs = nil
}
