// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/marketdata/v2/stock_snapshots.proto

package marketdatav2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetStockSnapshotsRequest is the request to get stock snapshots.
type GetStockSnapshotsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Comma-separated list of symbols.
	Symbols string `protobuf:"bytes,1,opt,name=symbols,proto3" json:"symbols,omitempty"`
	// Data feed (iex, sip).
	Feed string `protobuf:"bytes,2,opt,name=feed,proto3" json:"feed,omitempty"`
	// Currency for the response prices.
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockSnapshotsRequest) Reset() {
	*x = GetStockSnapshotsRequest{}
	mi := &file_alpaca_marketdata_v2_stock_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockSnapshotsRequest) ProtoMessage() {}

func (x *GetStockSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*GetStockSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockSnapshotsRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

func (x *GetStockSnapshotsRequest) GetFeed() string {
	if x != nil {
		return x.Feed
	}
	return ""
}

func (x *GetStockSnapshotsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// GetStockSnapshotsResponse is the response containing stock snapshots.
type GetStockSnapshotsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to snapshot.
	Snapshots     map[string]*Snapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockSnapshotsResponse) Reset() {
	*x = GetStockSnapshotsResponse{}
	mi := &file_alpaca_marketdata_v2_stock_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockSnapshotsResponse) ProtoMessage() {}

func (x *GetStockSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*GetStockSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockSnapshotsResponse) GetSnapshots() map[string]*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// GetStockSnapshotRequest is the request to get a single stock snapshot.
type GetStockSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Symbol (bound from path variable).
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Data feed (iex, sip).
	Feed string `protobuf:"bytes,2,opt,name=feed,proto3" json:"feed,omitempty"`
	// Currency for the response prices.
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockSnapshotRequest) Reset() {
	*x = GetStockSnapshotRequest{}
	mi := &file_alpaca_marketdata_v2_stock_snapshots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockSnapshotRequest) ProtoMessage() {}

func (x *GetStockSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_marketdata_v2_stock_snapshots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetStockSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_marketdata_v2_stock_snapshots_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockSnapshotRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetStockSnapshotRequest) GetFeed() string {
	if x != nil {
		return x.Feed
	}
	return ""
}

func (x *GetStockSnapshotRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_alpaca_marketdata_v2_stock_snapshots_proto protoreflect.FileDescriptor

const file_alpaca_marketdata_v2_stock_snapshots_proto_rawDesc = "" +
	"\n" +
	"*alpaca/marketdata/v2/stock_snapshots.proto\x12\x14alpaca.marketdata.v2\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a!alpaca/marketdata/v2/common.proto\"\xbb\x01\n" +
	"\x18GetStockSnapshotsRequest\x12A\n" +
	"\asymbols\x18\x01 \x01(\tB'\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x10\n" +
	"\x0eAAPL,TSLA,MSFTµ\x18\t\n" +
	"\asymbolsR\asymbols\x12'\n" +
	"\x04feed\x18\x02 \x01(\tB\x13\xba\xb5\x18\x05\n" +
	"\x03sipµ\x18\x06\n" +
	"\x04feedR\x04feed\x123\n" +
	"\bcurrency\x18\x03 \x01(\tB\x17\xba\xb5\x18\x05\n" +
	"\x03USDµ\x18\n" +
	"\n" +
	"\bcurrencyR\bcurrency\"\xd7\x01\n" +
	"\x19GetStockSnapshotsResponse\x12\\\n" +
	"\tsnapshots\x18\x01 \x03(\v2>.alpaca.marketdata.v2.GetStockSnapshotsResponse.SnapshotsEntryR\tsnapshots\x1a\\\n" +
	"\x0eSnapshotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.alpaca.marketdata.v2.SnapshotR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x17GetStockSnapshotRequest\x12(\n" +
	"\x06symbol\x18\x01 \x01(\tB\x10\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x06\n" +
	"\x04AAPLR\x06symbol\x12'\n" +
	"\x04feed\x18\x02 \x01(\tB\x13\xba\xb5\x18\x05\n" +
	"\x03sipµ\x18\x06\n" +
	"\x04feedR\x04feed\x123\n" +
	"\bcurrency\x18\x03 \x01(\tB\x17\xba\xb5\x18\x05\n" +
	"\x03USDµ\x18\n" +
	"\n" +
	"\bcurrencyR\bcurrencyB\xec\x01\n" +
	"\x18com.alpaca.marketdata.v2B\x13StockSnapshotsProtoP\x01ZIgithub.com/sebastienmelki/alpaca-go/api/alpaca/marketdata/v2;marketdatav2\xa2\x02\x03AMX\xaa\x02\x14Alpaca.Marketdata.V2\xca\x02\x14Alpaca\\Marketdata\\V2\xe2\x02 Alpaca\\Marketdata\\V2\\GPBMetadata\xea\x02\x16Alpaca::Marketdata::V2b\x06proto3"

var (
	file_alpaca_marketdata_v2_stock_snapshots_proto_rawDescOnce sync.Once
	file_alpaca_marketdata_v2_stock_snapshots_proto_rawDescData []byte
)

func file_alpaca_marketdata_v2_stock_snapshots_proto_rawDescGZIP() []byte {
	file_alpaca_marketdata_v2_stock_snapshots_proto_rawDescOnce.Do(func() {
		file_alpaca_marketdata_v2_stock_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_stock_snapshots_proto_rawDesc), len(file_alpaca_marketdata_v2_stock_snapshots_proto_rawDesc)))
	})
	return file_alpaca_marketdata_v2_stock_snapshots_proto_rawDescData
}

var file_alpaca_marketdata_v2_stock_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_alpaca_marketdata_v2_stock_snapshots_proto_goTypes = []any{
	(*GetStockSnapshotsRequest)(nil),  // 0: alpaca.marketdata.v2.GetStockSnapshotsRequest
	(*GetStockSnapshotsResponse)(nil), // 1: alpaca.marketdata.v2.GetStockSnapshotsResponse
	(*GetStockSnapshotRequest)(nil),   // 2: alpaca.marketdata.v2.GetStockSnapshotRequest
	nil,                               // 3: alpaca.marketdata.v2.GetStockSnapshotsResponse.SnapshotsEntry
	(*Snapshot)(nil),                  // 4: alpaca.marketdata.v2.Snapshot
}
var file_alpaca_marketdata_v2_stock_snapshots_proto_depIdxs = []int32{
	3, // 0: alpaca.marketdata.v2.GetStockSnapshotsResponse.snapshots:type_name -> alpaca.marketdata.v2.GetStockSnapshotsResponse.SnapshotsEntry
	4, // 1: alpaca.marketdata.v2.GetStockSnapshotsResponse.SnapshotsEntry.value:type_name -> alpaca.marketdata.v2.Snapshot
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alpaca_marketdata_v2_stock_snapshots_proto_init() }
func file_alpaca_marketdata_v2_stock_snapshots_proto_init() {
	if File_alpaca_marketdata_v2_stock_snapshots_proto != nil {
		return
	}
	file_alpaca_marketdata_v2_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_marketdata_v2_stock_snapshots_proto_rawDesc), len(file_alpaca_marketdata_v2_stock_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_marketdata_v2_stock_snapshots_proto_goTypes,
		DependencyIndexes: file_alpaca_marketdata_v2_stock_snapshots_proto_depIdxs,
		MessageInfos:      file_alpaca_marketdata_v2_stock_snapshots_proto_msgTypes,
	}.Build()
	File_alpaca_marketdata_v2_stock_snapshots_proto = out.File
	file_alpaca_marketdata_v2_stock_snapshots_proto_goTypes = nil
	file_alpaca_marketdata_v2_stock_snapshots_proto_depIdxs = nil
}
