// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/broker/v1/ach_relationship.proto

package brokerv1

import (
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ACHRelationshipStatus represents the status of an ACH relationship.
type ACHRelationshipStatus int32

const (
	ACHRelationshipStatus_ACH_RELATIONSHIP_STATUS_UNSPECIFIED      ACHRelationshipStatus = 0
	ACHRelationshipStatus_ACH_RELATIONSHIP_STATUS_QUEUED           ACHRelationshipStatus = 1
	ACHRelationshipStatus_ACH_RELATIONSHIP_STATUS_SENT_TO_CLEARING ACHRelationshipStatus = 2
	ACHRelationshipStatus_ACH_RELATIONSHIP_STATUS_APPROVED         ACHRelationshipStatus = 3
	ACHRelationshipStatus_ACH_RELATIONSHIP_STATUS_CANCELED         ACHRelationshipStatus = 4
)

// Enum value maps for ACHRelationshipStatus.
var (
	ACHRelationshipStatus_name = map[int32]string{
		0: "ACH_RELATIONSHIP_STATUS_UNSPECIFIED",
		1: "ACH_RELATIONSHIP_STATUS_QUEUED",
		2: "ACH_RELATIONSHIP_STATUS_SENT_TO_CLEARING",
		3: "ACH_RELATIONSHIP_STATUS_APPROVED",
		4: "ACH_RELATIONSHIP_STATUS_CANCELED",
	}
	ACHRelationshipStatus_value = map[string]int32{
		"ACH_RELATIONSHIP_STATUS_UNSPECIFIED":      0,
		"ACH_RELATIONSHIP_STATUS_QUEUED":           1,
		"ACH_RELATIONSHIP_STATUS_SENT_TO_CLEARING": 2,
		"ACH_RELATIONSHIP_STATUS_APPROVED":         3,
		"ACH_RELATIONSHIP_STATUS_CANCELED":         4,
	}
)

func (x ACHRelationshipStatus) Enum() *ACHRelationshipStatus {
	p := new(ACHRelationshipStatus)
	*p = x
	return p
}

func (x ACHRelationshipStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACHRelationshipStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_alpaca_broker_v1_ach_relationship_proto_enumTypes[0].Descriptor()
}

func (ACHRelationshipStatus) Type() protoreflect.EnumType {
	return &file_alpaca_broker_v1_ach_relationship_proto_enumTypes[0]
}

func (x ACHRelationshipStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACHRelationshipStatus.Descriptor instead.
func (ACHRelationshipStatus) EnumDescriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_ach_relationship_proto_rawDescGZIP(), []int{0}
}

// ACHRelationship represents a bank account connection for ACH transfers.
type ACHRelationship struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relationship ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Account ID (UUID).
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Creation timestamp (RFC 3339).
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last update timestamp (RFC 3339).
	UpdatedAt string `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Relationship status.
	Status ACHRelationshipStatus `protobuf:"varint,5,opt,name=status,proto3,enum=alpaca.broker.v1.ACHRelationshipStatus" json:"status,omitempty"`
	// Account owner name.
	AccountOwnerName string `protobuf:"bytes,6,opt,name=account_owner_name,json=accountOwnerName,proto3" json:"account_owner_name,omitempty"`
	// Bank account type (CHECKING, SAVINGS).
	BankAccountType string `protobuf:"bytes,7,opt,name=bank_account_type,json=bankAccountType,proto3" json:"bank_account_type,omitempty"`
	// Bank account number (masked).
	BankAccountNumber string `protobuf:"bytes,8,opt,name=bank_account_number,json=bankAccountNumber,proto3" json:"bank_account_number,omitempty"`
	// Bank routing number.
	BankRoutingNumber string `protobuf:"bytes,9,opt,name=bank_routing_number,json=bankRoutingNumber,proto3" json:"bank_routing_number,omitempty"`
	// Nickname for the relationship.
	Nickname string `protobuf:"bytes,10,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Processor token (if using Plaid).
	ProcessorToken string `protobuf:"bytes,11,opt,name=processor_token,json=processorToken,proto3" json:"processor_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ACHRelationship) Reset() {
	*x = ACHRelationship{}
	mi := &file_alpaca_broker_v1_ach_relationship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACHRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACHRelationship) ProtoMessage() {}

func (x *ACHRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_ach_relationship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACHRelationship.ProtoReflect.Descriptor instead.
func (*ACHRelationship) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_ach_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *ACHRelationship) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ACHRelationship) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ACHRelationship) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ACHRelationship) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ACHRelationship) GetStatus() ACHRelationshipStatus {
	if x != nil {
		return x.Status
	}
	return ACHRelationshipStatus_ACH_RELATIONSHIP_STATUS_UNSPECIFIED
}

func (x *ACHRelationship) GetAccountOwnerName() string {
	if x != nil {
		return x.AccountOwnerName
	}
	return ""
}

func (x *ACHRelationship) GetBankAccountType() string {
	if x != nil {
		return x.BankAccountType
	}
	return ""
}

func (x *ACHRelationship) GetBankAccountNumber() string {
	if x != nil {
		return x.BankAccountNumber
	}
	return ""
}

func (x *ACHRelationship) GetBankRoutingNumber() string {
	if x != nil {
		return x.BankRoutingNumber
	}
	return ""
}

func (x *ACHRelationship) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ACHRelationship) GetProcessorToken() string {
	if x != nil {
		return x.ProcessorToken
	}
	return ""
}

var File_alpaca_broker_v1_ach_relationship_proto protoreflect.FileDescriptor

const file_alpaca_broker_v1_ach_relationship_proto_rawDesc = "" +
	"\n" +
	"'alpaca/broker/v1/ach_relationship.proto\x12\x10alpaca.broker.v1\x1a\x1csebuf/http/annotations.proto\"\xac\x05\n" +
	"\x0fACHRelationship\x12:\n" +
	"\x02id\x18\x01 \x01(\tB*\xba\xb5\x18&\n" +
	"$f5fbd77f-7b7e-4b91-8e8a-aaaa00000001R\x02id\x12I\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB*\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tB\x1a\xba\xb5\x18\x16\n" +
	"\x142024-01-15T10:30:00ZR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tB\x1a\xba\xb5\x18\x16\n" +
	"\x142024-01-15T10:30:00ZR\tupdatedAt\x12H\n" +
	"\x06status\x18\x05 \x01(\x0e2'.alpaca.broker.v1.ACHRelationshipStatusB\a\xba\xb5\x18\x03\n" +
	"\x013R\x06status\x12<\n" +
	"\x12account_owner_name\x18\x06 \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\bJohn DoeR\x10accountOwnerName\x12:\n" +
	"\x11bank_account_type\x18\a \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\bCHECKINGR\x0fbankAccountType\x12?\n" +
	"\x13bank_account_number\x18\b \x01(\tB\x0f\xba\xb5\x18\v\n" +
	"\t*****6789R\x11bankAccountNumber\x12?\n" +
	"\x13bank_routing_number\x18\t \x01(\tB\x0f\xba\xb5\x18\v\n" +
	"\t121000358R\x11bankRoutingNumber\x12-\n" +
	"\bnickname\x18\n" +
	" \x01(\tB\x11\xba\xb5\x18\r\n" +
	"\vMy CheckingR\bnickname\x12'\n" +
	"\x0fprocessor_token\x18\v \x01(\tR\x0eprocessorToken*\xde\x01\n" +
	"\x15ACHRelationshipStatus\x12'\n" +
	"#ACH_RELATIONSHIP_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eACH_RELATIONSHIP_STATUS_QUEUED\x10\x01\x12,\n" +
	"(ACH_RELATIONSHIP_STATUS_SENT_TO_CLEARING\x10\x02\x12$\n" +
	" ACH_RELATIONSHIP_STATUS_APPROVED\x10\x03\x12$\n" +
	" ACH_RELATIONSHIP_STATUS_CANCELED\x10\x04B\xd1\x01\n" +
	"\x14com.alpaca.broker.v1B\x14AchRelationshipProtoP\x01ZAgithub.com/sebastienmelki/alpaca-go/api/alpaca/broker/v1;brokerv1\xa2\x02\x03ABX\xaa\x02\x10Alpaca.Broker.V1\xca\x02\x10Alpaca\\Broker\\V1\xe2\x02\x1cAlpaca\\Broker\\V1\\GPBMetadata\xea\x02\x12Alpaca::Broker::V1b\x06proto3"

var (
	file_alpaca_broker_v1_ach_relationship_proto_rawDescOnce sync.Once
	file_alpaca_broker_v1_ach_relationship_proto_rawDescData []byte
)

func file_alpaca_broker_v1_ach_relationship_proto_rawDescGZIP() []byte {
	file_alpaca_broker_v1_ach_relationship_proto_rawDescOnce.Do(func() {
		file_alpaca_broker_v1_ach_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_ach_relationship_proto_rawDesc), len(file_alpaca_broker_v1_ach_relationship_proto_rawDesc)))
	})
	return file_alpaca_broker_v1_ach_relationship_proto_rawDescData
}

var file_alpaca_broker_v1_ach_relationship_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alpaca_broker_v1_ach_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alpaca_broker_v1_ach_relationship_proto_goTypes = []any{
	(ACHRelationshipStatus)(0), // 0: alpaca.broker.v1.ACHRelationshipStatus
	(*ACHRelationship)(nil),    // 1: alpaca.broker.v1.ACHRelationship
}
var file_alpaca_broker_v1_ach_relationship_proto_depIdxs = []int32{
	0, // 0: alpaca.broker.v1.ACHRelationship.status:type_name -> alpaca.broker.v1.ACHRelationshipStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alpaca_broker_v1_ach_relationship_proto_init() }
func file_alpaca_broker_v1_ach_relationship_proto_init() {
	if File_alpaca_broker_v1_ach_relationship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_ach_relationship_proto_rawDesc), len(file_alpaca_broker_v1_ach_relationship_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_broker_v1_ach_relationship_proto_goTypes,
		DependencyIndexes: file_alpaca_broker_v1_ach_relationship_proto_depIdxs,
		EnumInfos:         file_alpaca_broker_v1_ach_relationship_proto_enumTypes,
		MessageInfos:      file_alpaca_broker_v1_ach_relationship_proto_msgTypes,
	}.Build()
	File_alpaca_broker_v1_ach_relationship_proto = out.File
	file_alpaca_broker_v1_ach_relationship_proto_goTypes = nil
	file_alpaca_broker_v1_ach_relationship_proto_depIdxs = nil
}
