// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/broker/v1/cancel_transfer.proto

package brokerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CancelTransferRequest is the request to cancel a transfer.
type CancelTransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account ID (bound from path variable).
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// The transfer ID (bound from path variable).
	TransferId    string `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransferRequest) Reset() {
	*x = CancelTransferRequest{}
	mi := &file_alpaca_broker_v1_cancel_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferRequest) ProtoMessage() {}

func (x *CancelTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_cancel_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferRequest.ProtoReflect.Descriptor instead.
func (*CancelTransferRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_cancel_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *CancelTransferRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CancelTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

// CancelTransferResponse is the response after canceling a transfer.
type CancelTransferResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the cancellation was successful.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransferResponse) Reset() {
	*x = CancelTransferResponse{}
	mi := &file_alpaca_broker_v1_cancel_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferResponse) ProtoMessage() {}

func (x *CancelTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_cancel_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferResponse.ProtoReflect.Descriptor instead.
func (*CancelTransferResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_cancel_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *CancelTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_alpaca_broker_v1_cancel_transfer_proto protoreflect.FileDescriptor

const file_alpaca_broker_v1_cancel_transfer_proto_rawDesc = "" +
	"\n" +
	"&alpaca/broker/v1/cancel_transfer.proto\x12\x10alpaca.broker.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"\xc5\x01\n" +
	"\x15CancelTransferRequest\x12T\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountId\x12V\n" +
	"\vtransfer_id\x18\x02 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$a1b2c3d4-e5f6-7890-abcd-ef1234567890R\n" +
	"transferId\">\n" +
	"\x16CancelTransferResponse\x12$\n" +
	"\asuccess\x18\x01 \x01(\bB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x04trueR\asuccessB\xd0\x01\n" +
	"\x14com.alpaca.broker.v1B\x13CancelTransferProtoP\x01ZAgithub.com/sebastienmelki/alpaca-go/api/alpaca/broker/v1;brokerv1\xa2\x02\x03ABX\xaa\x02\x10Alpaca.Broker.V1\xca\x02\x10Alpaca\\Broker\\V1\xe2\x02\x1cAlpaca\\Broker\\V1\\GPBMetadata\xea\x02\x12Alpaca::Broker::V1b\x06proto3"

var (
	file_alpaca_broker_v1_cancel_transfer_proto_rawDescOnce sync.Once
	file_alpaca_broker_v1_cancel_transfer_proto_rawDescData []byte
)

func file_alpaca_broker_v1_cancel_transfer_proto_rawDescGZIP() []byte {
	file_alpaca_broker_v1_cancel_transfer_proto_rawDescOnce.Do(func() {
		file_alpaca_broker_v1_cancel_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_cancel_transfer_proto_rawDesc), len(file_alpaca_broker_v1_cancel_transfer_proto_rawDesc)))
	})
	return file_alpaca_broker_v1_cancel_transfer_proto_rawDescData
}

var file_alpaca_broker_v1_cancel_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alpaca_broker_v1_cancel_transfer_proto_goTypes = []any{
	(*CancelTransferRequest)(nil),  // 0: alpaca.broker.v1.CancelTransferRequest
	(*CancelTransferResponse)(nil), // 1: alpaca.broker.v1.CancelTransferResponse
}
var file_alpaca_broker_v1_cancel_transfer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alpaca_broker_v1_cancel_transfer_proto_init() }
func file_alpaca_broker_v1_cancel_transfer_proto_init() {
	if File_alpaca_broker_v1_cancel_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_cancel_transfer_proto_rawDesc), len(file_alpaca_broker_v1_cancel_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_broker_v1_cancel_transfer_proto_goTypes,
		DependencyIndexes: file_alpaca_broker_v1_cancel_transfer_proto_depIdxs,
		MessageInfos:      file_alpaca_broker_v1_cancel_transfer_proto_msgTypes,
	}.Build()
	File_alpaca_broker_v1_cancel_transfer_proto = out.File
	file_alpaca_broker_v1_cancel_transfer_proto_goTypes = nil
	file_alpaca_broker_v1_cancel_transfer_proto_depIdxs = nil
}
