// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/broker/v1/create_account.proto

package brokerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateAccountRequest is the request to create a new broker account.
type CreateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contact information.
	Contact *Contact `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	// Identity information.
	Identity *Identity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// Disclosures.
	Disclosures *Disclosures `protobuf:"bytes,3,opt,name=disclosures,proto3" json:"disclosures,omitempty"`
	// Signed agreements.
	Agreements []*Agreement `protobuf:"bytes,4,rep,name=agreements,proto3" json:"agreements,omitempty"`
	// Optional trusted contact.
	TrustedContact *TrustedContact `protobuf:"bytes,5,opt,name=trusted_contact,json=trustedContact,proto3" json:"trusted_contact,omitempty"`
	// Account type (trading, custodial).
	AccountType string `protobuf:"bytes,6,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	// Whether to enable margin for assets.
	EnabledAssetsMargin bool `protobuf:"varint,7,opt,name=enabled_assets_margin,json=enabledAssetsMargin,proto3" json:"enabled_assets_margin,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_alpaca_broker_v1_create_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_create_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_create_account_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *CreateAccountRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *CreateAccountRequest) GetDisclosures() *Disclosures {
	if x != nil {
		return x.Disclosures
	}
	return nil
}

func (x *CreateAccountRequest) GetAgreements() []*Agreement {
	if x != nil {
		return x.Agreements
	}
	return nil
}

func (x *CreateAccountRequest) GetTrustedContact() *TrustedContact {
	if x != nil {
		return x.TrustedContact
	}
	return nil
}

func (x *CreateAccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateAccountRequest) GetEnabledAssetsMargin() bool {
	if x != nil {
		return x.EnabledAssetsMargin
	}
	return false
}

var File_alpaca_broker_v1_create_account_proto protoreflect.FileDescriptor

const file_alpaca_broker_v1_create_account_proto_rawDesc = "" +
	"\n" +
	"%alpaca/broker/v1/create_account.proto\x12\x10alpaca.broker.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a%alpaca/broker/v1/broker_account.proto\"\xe0\x03\n" +
	"\x14CreateAccountRequest\x12;\n" +
	"\acontact\x18\x01 \x01(\v2\x19.alpaca.broker.v1.ContactB\x06\xbaH\x03\xc8\x01\x01R\acontact\x12>\n" +
	"\bidentity\x18\x02 \x01(\v2\x1a.alpaca.broker.v1.IdentityB\x06\xbaH\x03\xc8\x01\x01R\bidentity\x12G\n" +
	"\vdisclosures\x18\x03 \x01(\v2\x1d.alpaca.broker.v1.DisclosuresB\x06\xbaH\x03\xc8\x01\x01R\vdisclosures\x12E\n" +
	"\n" +
	"agreements\x18\x04 \x03(\v2\x1b.alpaca.broker.v1.AgreementB\b\xbaH\x05\x92\x01\x02\b\x01R\n" +
	"agreements\x12I\n" +
	"\x0ftrusted_contact\x18\x05 \x01(\v2 .alpaca.broker.v1.TrustedContactR\x0etrustedContact\x120\n" +
	"\faccount_type\x18\x06 \x01(\tB\r\xba\xb5\x18\t\n" +
	"\atradingR\vaccountType\x12>\n" +
	"\x15enabled_assets_margin\x18\a \x01(\bB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x04trueR\x13enabledAssetsMarginB\xcf\x01\n" +
	"\x14com.alpaca.broker.v1B\x12CreateAccountProtoP\x01ZAgithub.com/sebastienmelki/alpaca-go/api/alpaca/broker/v1;brokerv1\xa2\x02\x03ABX\xaa\x02\x10Alpaca.Broker.V1\xca\x02\x10Alpaca\\Broker\\V1\xe2\x02\x1cAlpaca\\Broker\\V1\\GPBMetadata\xea\x02\x12Alpaca::Broker::V1b\x06proto3"

var (
	file_alpaca_broker_v1_create_account_proto_rawDescOnce sync.Once
	file_alpaca_broker_v1_create_account_proto_rawDescData []byte
)

func file_alpaca_broker_v1_create_account_proto_rawDescGZIP() []byte {
	file_alpaca_broker_v1_create_account_proto_rawDescOnce.Do(func() {
		file_alpaca_broker_v1_create_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_create_account_proto_rawDesc), len(file_alpaca_broker_v1_create_account_proto_rawDesc)))
	})
	return file_alpaca_broker_v1_create_account_proto_rawDescData
}

var file_alpaca_broker_v1_create_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alpaca_broker_v1_create_account_proto_goTypes = []any{
	(*CreateAccountRequest)(nil), // 0: alpaca.broker.v1.CreateAccountRequest
	(*Contact)(nil),              // 1: alpaca.broker.v1.Contact
	(*Identity)(nil),             // 2: alpaca.broker.v1.Identity
	(*Disclosures)(nil),          // 3: alpaca.broker.v1.Disclosures
	(*Agreement)(nil),            // 4: alpaca.broker.v1.Agreement
	(*TrustedContact)(nil),       // 5: alpaca.broker.v1.TrustedContact
}
var file_alpaca_broker_v1_create_account_proto_depIdxs = []int32{
	1, // 0: alpaca.broker.v1.CreateAccountRequest.contact:type_name -> alpaca.broker.v1.Contact
	2, // 1: alpaca.broker.v1.CreateAccountRequest.identity:type_name -> alpaca.broker.v1.Identity
	3, // 2: alpaca.broker.v1.CreateAccountRequest.disclosures:type_name -> alpaca.broker.v1.Disclosures
	4, // 3: alpaca.broker.v1.CreateAccountRequest.agreements:type_name -> alpaca.broker.v1.Agreement
	5, // 4: alpaca.broker.v1.CreateAccountRequest.trusted_contact:type_name -> alpaca.broker.v1.TrustedContact
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_alpaca_broker_v1_create_account_proto_init() }
func file_alpaca_broker_v1_create_account_proto_init() {
	if File_alpaca_broker_v1_create_account_proto != nil {
		return
	}
	file_alpaca_broker_v1_broker_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_create_account_proto_rawDesc), len(file_alpaca_broker_v1_create_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_broker_v1_create_account_proto_goTypes,
		DependencyIndexes: file_alpaca_broker_v1_create_account_proto_depIdxs,
		MessageInfos:      file_alpaca_broker_v1_create_account_proto_msgTypes,
	}.Build()
	File_alpaca_broker_v1_create_account_proto = out.File
	file_alpaca_broker_v1_create_account_proto_goTypes = nil
	file_alpaca_broker_v1_create_account_proto_depIdxs = nil
}
