// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/broker/v1/create_transfer.proto

package brokerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateTransferRequest is the request to create a transfer.
type CreateTransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account ID (bound from path variable).
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Transfer type (ach, wire).
	TransferType string `protobuf:"bytes,2,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	// ACH relationship ID (required for ACH transfers).
	RelationshipId string `protobuf:"bytes,3,opt,name=relationship_id,json=relationshipId,proto3" json:"relationship_id,omitempty"`
	// Bank ID (required for wire transfers).
	BankId string `protobuf:"bytes,4,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	// Transfer amount.
	Amount string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// Transfer direction (INCOMING, OUTGOING).
	Direction string `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	// Additional information.
	AdditionalInformation string `protobuf:"bytes,7,opt,name=additional_information,json=additionalInformation,proto3" json:"additional_information,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_alpaca_broker_v1_create_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_create_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_create_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransferRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateTransferRequest) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *CreateTransferRequest) GetRelationshipId() string {
	if x != nil {
		return x.RelationshipId
	}
	return ""
}

func (x *CreateTransferRequest) GetBankId() string {
	if x != nil {
		return x.BankId
	}
	return ""
}

func (x *CreateTransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreateTransferRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CreateTransferRequest) GetAdditionalInformation() string {
	if x != nil {
		return x.AdditionalInformation
	}
	return ""
}

var File_alpaca_broker_v1_create_transfer_proto protoreflect.FileDescriptor

const file_alpaca_broker_v1_create_transfer_proto_rawDesc = "" +
	"\n" +
	"&alpaca/broker/v1/create_transfer.proto\x12\x10alpaca.broker.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"\xa9\x03\n" +
	"\x15CreateTransferRequest\x12T\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountId\x124\n" +
	"\rtransfer_type\x18\x02 \x01(\tB\x0f\xbaH\x03\xc8\x01\x01\xba\xb5\x18\x05\n" +
	"\x03achR\ftransferType\x12S\n" +
	"\x0frelationship_id\x18\x03 \x01(\tB*\xba\xb5\x18&\n" +
	"$f5fbd77f-7b7e-4b91-8e8a-aaaa00000001R\x0erelationshipId\x12\x17\n" +
	"\abank_id\x18\x04 \x01(\tR\x06bankId\x12+\n" +
	"\x06amount\x18\x05 \x01(\tB\x13\xbaH\x03\xc8\x01\x01\xba\xb5\x18\t\n" +
	"\a1000.00R\x06amount\x122\n" +
	"\tdirection\x18\x06 \x01(\tB\x14\xbaH\x03\xc8\x01\x01\xba\xb5\x18\n" +
	"\n" +
	"\bINCOMINGR\tdirection\x125\n" +
	"\x16additional_information\x18\a \x01(\tR\x15additionalInformationB\xd0\x01\n" +
	"\x14com.alpaca.broker.v1B\x13CreateTransferProtoP\x01ZAgithub.com/sebastienmelki/alpaca-go/api/alpaca/broker/v1;brokerv1\xa2\x02\x03ABX\xaa\x02\x10Alpaca.Broker.V1\xca\x02\x10Alpaca\\Broker\\V1\xe2\x02\x1cAlpaca\\Broker\\V1\\GPBMetadata\xea\x02\x12Alpaca::Broker::V1b\x06proto3"

var (
	file_alpaca_broker_v1_create_transfer_proto_rawDescOnce sync.Once
	file_alpaca_broker_v1_create_transfer_proto_rawDescData []byte
)

func file_alpaca_broker_v1_create_transfer_proto_rawDescGZIP() []byte {
	file_alpaca_broker_v1_create_transfer_proto_rawDescOnce.Do(func() {
		file_alpaca_broker_v1_create_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_create_transfer_proto_rawDesc), len(file_alpaca_broker_v1_create_transfer_proto_rawDesc)))
	})
	return file_alpaca_broker_v1_create_transfer_proto_rawDescData
}

var file_alpaca_broker_v1_create_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alpaca_broker_v1_create_transfer_proto_goTypes = []any{
	(*CreateTransferRequest)(nil), // 0: alpaca.broker.v1.CreateTransferRequest
}
var file_alpaca_broker_v1_create_transfer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alpaca_broker_v1_create_transfer_proto_init() }
func file_alpaca_broker_v1_create_transfer_proto_init() {
	if File_alpaca_broker_v1_create_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_create_transfer_proto_rawDesc), len(file_alpaca_broker_v1_create_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_broker_v1_create_transfer_proto_goTypes,
		DependencyIndexes: file_alpaca_broker_v1_create_transfer_proto_depIdxs,
		MessageInfos:      file_alpaca_broker_v1_create_transfer_proto_msgTypes,
	}.Build()
	File_alpaca_broker_v1_create_transfer_proto = out.File
	file_alpaca_broker_v1_create_transfer_proto_goTypes = nil
	file_alpaca_broker_v1_create_transfer_proto_depIdxs = nil
}
