// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/broker/v1/delete_ach_relationship.proto

package brokerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeleteACHRelationshipRequest is the request to delete an ACH relationship.
type DeleteACHRelationshipRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account ID (bound from path variable).
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// The ACH relationship ID (bound from path variable).
	AchRelationshipId string `protobuf:"bytes,2,opt,name=ach_relationship_id,json=achRelationshipId,proto3" json:"ach_relationship_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteACHRelationshipRequest) Reset() {
	*x = DeleteACHRelationshipRequest{}
	mi := &file_alpaca_broker_v1_delete_ach_relationship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteACHRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteACHRelationshipRequest) ProtoMessage() {}

func (x *DeleteACHRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_delete_ach_relationship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteACHRelationshipRequest.ProtoReflect.Descriptor instead.
func (*DeleteACHRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_delete_ach_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteACHRelationshipRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeleteACHRelationshipRequest) GetAchRelationshipId() string {
	if x != nil {
		return x.AchRelationshipId
	}
	return ""
}

// DeleteACHRelationshipResponse is the response after deleting an ACH relationship.
type DeleteACHRelationshipResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deletion was successful.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteACHRelationshipResponse) Reset() {
	*x = DeleteACHRelationshipResponse{}
	mi := &file_alpaca_broker_v1_delete_ach_relationship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteACHRelationshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteACHRelationshipResponse) ProtoMessage() {}

func (x *DeleteACHRelationshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_delete_ach_relationship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteACHRelationshipResponse.ProtoReflect.Descriptor instead.
func (*DeleteACHRelationshipResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_delete_ach_relationship_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteACHRelationshipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_alpaca_broker_v1_delete_ach_relationship_proto protoreflect.FileDescriptor

const file_alpaca_broker_v1_delete_ach_relationship_proto_rawDesc = "" +
	"\n" +
	".alpaca/broker/v1/delete_ach_relationship.proto\x12\x10alpaca.broker.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"\xdb\x01\n" +
	"\x1cDeleteACHRelationshipRequest\x12T\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountId\x12e\n" +
	"\x13ach_relationship_id\x18\x02 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$f5fbd77f-7b7e-4b91-8e8a-aaaa00000001R\x11achRelationshipId\"E\n" +
	"\x1dDeleteACHRelationshipResponse\x12$\n" +
	"\asuccess\x18\x01 \x01(\bB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x04trueR\asuccessB\xd7\x01\n" +
	"\x14com.alpaca.broker.v1B\x1aDeleteAchRelationshipProtoP\x01ZAgithub.com/sebastienmelki/alpaca-go/api/alpaca/broker/v1;brokerv1\xa2\x02\x03ABX\xaa\x02\x10Alpaca.Broker.V1\xca\x02\x10Alpaca\\Broker\\V1\xe2\x02\x1cAlpaca\\Broker\\V1\\GPBMetadata\xea\x02\x12Alpaca::Broker::V1b\x06proto3"

var (
	file_alpaca_broker_v1_delete_ach_relationship_proto_rawDescOnce sync.Once
	file_alpaca_broker_v1_delete_ach_relationship_proto_rawDescData []byte
)

func file_alpaca_broker_v1_delete_ach_relationship_proto_rawDescGZIP() []byte {
	file_alpaca_broker_v1_delete_ach_relationship_proto_rawDescOnce.Do(func() {
		file_alpaca_broker_v1_delete_ach_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_delete_ach_relationship_proto_rawDesc), len(file_alpaca_broker_v1_delete_ach_relationship_proto_rawDesc)))
	})
	return file_alpaca_broker_v1_delete_ach_relationship_proto_rawDescData
}

var file_alpaca_broker_v1_delete_ach_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alpaca_broker_v1_delete_ach_relationship_proto_goTypes = []any{
	(*DeleteACHRelationshipRequest)(nil),  // 0: alpaca.broker.v1.DeleteACHRelationshipRequest
	(*DeleteACHRelationshipResponse)(nil), // 1: alpaca.broker.v1.DeleteACHRelationshipResponse
}
var file_alpaca_broker_v1_delete_ach_relationship_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alpaca_broker_v1_delete_ach_relationship_proto_init() }
func file_alpaca_broker_v1_delete_ach_relationship_proto_init() {
	if File_alpaca_broker_v1_delete_ach_relationship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_delete_ach_relationship_proto_rawDesc), len(file_alpaca_broker_v1_delete_ach_relationship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_broker_v1_delete_ach_relationship_proto_goTypes,
		DependencyIndexes: file_alpaca_broker_v1_delete_ach_relationship_proto_depIdxs,
		MessageInfos:      file_alpaca_broker_v1_delete_ach_relationship_proto_msgTypes,
	}.Build()
	File_alpaca_broker_v1_delete_ach_relationship_proto = out.File
	file_alpaca_broker_v1_delete_ach_relationship_proto_goTypes = nil
	file_alpaca_broker_v1_delete_ach_relationship_proto_depIdxs = nil
}
