// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/broker/v1/get_account.proto

package brokerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetBrokerAccountRequest is the request to get a broker account.
type GetBrokerAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account ID (bound from path variable).
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrokerAccountRequest) Reset() {
	*x = GetBrokerAccountRequest{}
	mi := &file_alpaca_broker_v1_get_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrokerAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrokerAccountRequest) ProtoMessage() {}

func (x *GetBrokerAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_get_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrokerAccountRequest.ProtoReflect.Descriptor instead.
func (*GetBrokerAccountRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_get_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetBrokerAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_alpaca_broker_v1_get_account_proto protoreflect.FileDescriptor

const file_alpaca_broker_v1_get_account_proto_rawDesc = "" +
	"\n" +
	"\"alpaca/broker/v1/get_account.proto\x12\x10alpaca.broker.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"o\n" +
	"\x17GetBrokerAccountRequest\x12T\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountIdB\xcc\x01\n" +
	"\x14com.alpaca.broker.v1B\x0fGetAccountProtoP\x01ZAgithub.com/sebastienmelki/alpaca-go/api/alpaca/broker/v1;brokerv1\xa2\x02\x03ABX\xaa\x02\x10Alpaca.Broker.V1\xca\x02\x10Alpaca\\Broker\\V1\xe2\x02\x1cAlpaca\\Broker\\V1\\GPBMetadata\xea\x02\x12Alpaca::Broker::V1b\x06proto3"

var (
	file_alpaca_broker_v1_get_account_proto_rawDescOnce sync.Once
	file_alpaca_broker_v1_get_account_proto_rawDescData []byte
)

func file_alpaca_broker_v1_get_account_proto_rawDescGZIP() []byte {
	file_alpaca_broker_v1_get_account_proto_rawDescOnce.Do(func() {
		file_alpaca_broker_v1_get_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_get_account_proto_rawDesc), len(file_alpaca_broker_v1_get_account_proto_rawDesc)))
	})
	return file_alpaca_broker_v1_get_account_proto_rawDescData
}

var file_alpaca_broker_v1_get_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alpaca_broker_v1_get_account_proto_goTypes = []any{
	(*GetBrokerAccountRequest)(nil), // 0: alpaca.broker.v1.GetBrokerAccountRequest
}
var file_alpaca_broker_v1_get_account_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alpaca_broker_v1_get_account_proto_init() }
func file_alpaca_broker_v1_get_account_proto_init() {
	if File_alpaca_broker_v1_get_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_get_account_proto_rawDesc), len(file_alpaca_broker_v1_get_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_broker_v1_get_account_proto_goTypes,
		DependencyIndexes: file_alpaca_broker_v1_get_account_proto_depIdxs,
		MessageInfos:      file_alpaca_broker_v1_get_account_proto_msgTypes,
	}.Build()
	File_alpaca_broker_v1_get_account_proto = out.File
	file_alpaca_broker_v1_get_account_proto_goTypes = nil
	file_alpaca_broker_v1_get_account_proto_depIdxs = nil
}
