// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/broker/v1/list_trading_orders.proto

package brokerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListTradingOrdersRequest is the request to list orders for a broker account.
type ListTradingOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account ID (bound from path variable).
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Filter by status (open, closed, all).
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Maximum number of orders to return.
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Cursor for pagination.
	After string `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
	// Filter by orders updated until this timestamp.
	Until string `protobuf:"bytes,5,opt,name=until,proto3" json:"until,omitempty"`
	// Sort direction (asc, desc).
	Direction string `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	// Whether to include nested leg orders.
	Nested bool `protobuf:"varint,7,opt,name=nested,proto3" json:"nested,omitempty"`
	// Filter by symbols (comma-separated).
	Symbols       string `protobuf:"bytes,8,opt,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradingOrdersRequest) Reset() {
	*x = ListTradingOrdersRequest{}
	mi := &file_alpaca_broker_v1_list_trading_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradingOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradingOrdersRequest) ProtoMessage() {}

func (x *ListTradingOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_list_trading_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradingOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListTradingOrdersRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_list_trading_orders_proto_rawDescGZIP(), []int{0}
}

func (x *ListTradingOrdersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListTradingOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTradingOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTradingOrdersRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ListTradingOrdersRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *ListTradingOrdersRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ListTradingOrdersRequest) GetNested() bool {
	if x != nil {
		return x.Nested
	}
	return false
}

func (x *ListTradingOrdersRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

// ListTradingOrdersResponse is the response containing trading orders.
type ListTradingOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of orders.
	Orders        []*BrokerOrder `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradingOrdersResponse) Reset() {
	*x = ListTradingOrdersResponse{}
	mi := &file_alpaca_broker_v1_list_trading_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradingOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradingOrdersResponse) ProtoMessage() {}

func (x *ListTradingOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_list_trading_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradingOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListTradingOrdersResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_list_trading_orders_proto_rawDescGZIP(), []int{1}
}

func (x *ListTradingOrdersResponse) GetOrders() []*BrokerOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_alpaca_broker_v1_list_trading_orders_proto protoreflect.FileDescriptor

const file_alpaca_broker_v1_list_trading_orders_proto_rawDesc = "" +
	"\n" +
	"*alpaca/broker/v1/list_trading_orders.proto\x12\x10alpaca.broker.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a$alpaca/broker/v1/trading_order.proto\"\x81\x04\n" +
	"\x18ListTradingOrdersRequest\x12T\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountId\x12.\n" +
	"\x06status\x18\x02 \x01(\tB\x16\xba\xb5\x18\x06\n" +
	"\x04openµ\x18\b\n" +
	"\x06statusR\x06status\x123\n" +
	"\x05limit\x18\x03 \x01(\x05B\x1d\xbaH\a\x1a\x05\x18\xf4\x03(\x01\xba\xb5\x18\x04\n" +
	"\x0250µ\x18\a\n" +
	"\x05limitR\x05limit\x12K\n" +
	"\x05after\x18\x04 \x01(\tB5\xba\xb5\x18&\n" +
	"$61e69015-8549-4bfd-b9c3-01e75843f47dµ\x18\a\n" +
	"\x05afterR\x05after\x12;\n" +
	"\x05until\x18\x05 \x01(\tB%\xba\xb5\x18\x16\n" +
	"\x142024-01-15T10:30:00Zµ\x18\a\n" +
	"\x05untilR\x05until\x127\n" +
	"\tdirection\x18\x06 \x01(\tB\x19\xba\xb5\x18\x06\n" +
	"\x04descµ\x18\v\n" +
	"\tdirectionR\tdirection\x12/\n" +
	"\x06nested\x18\a \x01(\bB\x17\xba\xb5\x18\a\n" +
	"\x05falseµ\x18\b\n" +
	"\x06nestedR\x06nested\x126\n" +
	"\asymbols\x18\b \x01(\tB\x1c\xba\xb5\x18\v\n" +
	"\tAAPL,TSLAµ\x18\t\n" +
	"\asymbolsR\asymbols\"R\n" +
	"\x19ListTradingOrdersResponse\x125\n" +
	"\x06orders\x18\x01 \x03(\v2\x1d.alpaca.broker.v1.BrokerOrderR\x06ordersB\xd3\x01\n" +
	"\x14com.alpaca.broker.v1B\x16ListTradingOrdersProtoP\x01ZAgithub.com/sebastienmelki/alpaca-go/api/alpaca/broker/v1;brokerv1\xa2\x02\x03ABX\xaa\x02\x10Alpaca.Broker.V1\xca\x02\x10Alpaca\\Broker\\V1\xe2\x02\x1cAlpaca\\Broker\\V1\\GPBMetadata\xea\x02\x12Alpaca::Broker::V1b\x06proto3"

var (
	file_alpaca_broker_v1_list_trading_orders_proto_rawDescOnce sync.Once
	file_alpaca_broker_v1_list_trading_orders_proto_rawDescData []byte
)

func file_alpaca_broker_v1_list_trading_orders_proto_rawDescGZIP() []byte {
	file_alpaca_broker_v1_list_trading_orders_proto_rawDescOnce.Do(func() {
		file_alpaca_broker_v1_list_trading_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_list_trading_orders_proto_rawDesc), len(file_alpaca_broker_v1_list_trading_orders_proto_rawDesc)))
	})
	return file_alpaca_broker_v1_list_trading_orders_proto_rawDescData
}

var file_alpaca_broker_v1_list_trading_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alpaca_broker_v1_list_trading_orders_proto_goTypes = []any{
	(*ListTradingOrdersRequest)(nil),  // 0: alpaca.broker.v1.ListTradingOrdersRequest
	(*ListTradingOrdersResponse)(nil), // 1: alpaca.broker.v1.ListTradingOrdersResponse
	(*BrokerOrder)(nil),               // 2: alpaca.broker.v1.BrokerOrder
}
var file_alpaca_broker_v1_list_trading_orders_proto_depIdxs = []int32{
	2, // 0: alpaca.broker.v1.ListTradingOrdersResponse.orders:type_name -> alpaca.broker.v1.BrokerOrder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alpaca_broker_v1_list_trading_orders_proto_init() }
func file_alpaca_broker_v1_list_trading_orders_proto_init() {
	if File_alpaca_broker_v1_list_trading_orders_proto != nil {
		return
	}
	file_alpaca_broker_v1_trading_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_list_trading_orders_proto_rawDesc), len(file_alpaca_broker_v1_list_trading_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_broker_v1_list_trading_orders_proto_goTypes,
		DependencyIndexes: file_alpaca_broker_v1_list_trading_orders_proto_depIdxs,
		MessageInfos:      file_alpaca_broker_v1_list_trading_orders_proto_msgTypes,
	}.Build()
	File_alpaca_broker_v1_list_trading_orders_proto = out.File
	file_alpaca_broker_v1_list_trading_orders_proto_goTypes = nil
	file_alpaca_broker_v1_list_trading_orders_proto_depIdxs = nil
}
