// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/broker/v1/update_account.proto

package brokerv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateBrokerAccountRequest is the request to update a broker account.
type UpdateBrokerAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account ID (bound from path variable).
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Updated contact information.
	Contact *Contact `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	// Updated identity information.
	Identity *Identity `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	// Updated disclosures.
	Disclosures *Disclosures `protobuf:"bytes,4,opt,name=disclosures,proto3" json:"disclosures,omitempty"`
	// Updated trusted contact.
	TrustedContact *TrustedContact `protobuf:"bytes,5,opt,name=trusted_contact,json=trustedContact,proto3" json:"trusted_contact,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateBrokerAccountRequest) Reset() {
	*x = UpdateBrokerAccountRequest{}
	mi := &file_alpaca_broker_v1_update_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBrokerAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBrokerAccountRequest) ProtoMessage() {}

func (x *UpdateBrokerAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_broker_v1_update_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBrokerAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateBrokerAccountRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_broker_v1_update_account_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateBrokerAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateBrokerAccountRequest) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *UpdateBrokerAccountRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *UpdateBrokerAccountRequest) GetDisclosures() *Disclosures {
	if x != nil {
		return x.Disclosures
	}
	return nil
}

func (x *UpdateBrokerAccountRequest) GetTrustedContact() *TrustedContact {
	if x != nil {
		return x.TrustedContact
	}
	return nil
}

var File_alpaca_broker_v1_update_account_proto protoreflect.FileDescriptor

const file_alpaca_broker_v1_update_account_proto_rawDesc = "" +
	"\n" +
	"%alpaca/broker/v1/update_account.proto\x12\x10alpaca.broker.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a%alpaca/broker/v1/broker_account.proto\"\xeb\x02\n" +
	"\x1aUpdateBrokerAccountRequest\x12T\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountId\x123\n" +
	"\acontact\x18\x02 \x01(\v2\x19.alpaca.broker.v1.ContactR\acontact\x126\n" +
	"\bidentity\x18\x03 \x01(\v2\x1a.alpaca.broker.v1.IdentityR\bidentity\x12?\n" +
	"\vdisclosures\x18\x04 \x01(\v2\x1d.alpaca.broker.v1.DisclosuresR\vdisclosures\x12I\n" +
	"\x0ftrusted_contact\x18\x05 \x01(\v2 .alpaca.broker.v1.TrustedContactR\x0etrustedContactB\xcf\x01\n" +
	"\x14com.alpaca.broker.v1B\x12UpdateAccountProtoP\x01ZAgithub.com/sebastienmelki/alpaca-go/api/alpaca/broker/v1;brokerv1\xa2\x02\x03ABX\xaa\x02\x10Alpaca.Broker.V1\xca\x02\x10Alpaca\\Broker\\V1\xe2\x02\x1cAlpaca\\Broker\\V1\\GPBMetadata\xea\x02\x12Alpaca::Broker::V1b\x06proto3"

var (
	file_alpaca_broker_v1_update_account_proto_rawDescOnce sync.Once
	file_alpaca_broker_v1_update_account_proto_rawDescData []byte
)

func file_alpaca_broker_v1_update_account_proto_rawDescGZIP() []byte {
	file_alpaca_broker_v1_update_account_proto_rawDescOnce.Do(func() {
		file_alpaca_broker_v1_update_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_update_account_proto_rawDesc), len(file_alpaca_broker_v1_update_account_proto_rawDesc)))
	})
	return file_alpaca_broker_v1_update_account_proto_rawDescData
}

var file_alpaca_broker_v1_update_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alpaca_broker_v1_update_account_proto_goTypes = []any{
	(*UpdateBrokerAccountRequest)(nil), // 0: alpaca.broker.v1.UpdateBrokerAccountRequest
	(*Contact)(nil),                    // 1: alpaca.broker.v1.Contact
	(*Identity)(nil),                   // 2: alpaca.broker.v1.Identity
	(*Disclosures)(nil),                // 3: alpaca.broker.v1.Disclosures
	(*TrustedContact)(nil),             // 4: alpaca.broker.v1.TrustedContact
}
var file_alpaca_broker_v1_update_account_proto_depIdxs = []int32{
	1, // 0: alpaca.broker.v1.UpdateBrokerAccountRequest.contact:type_name -> alpaca.broker.v1.Contact
	2, // 1: alpaca.broker.v1.UpdateBrokerAccountRequest.identity:type_name -> alpaca.broker.v1.Identity
	3, // 2: alpaca.broker.v1.UpdateBrokerAccountRequest.disclosures:type_name -> alpaca.broker.v1.Disclosures
	4, // 3: alpaca.broker.v1.UpdateBrokerAccountRequest.trusted_contact:type_name -> alpaca.broker.v1.TrustedContact
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_alpaca_broker_v1_update_account_proto_init() }
func file_alpaca_broker_v1_update_account_proto_init() {
	if File_alpaca_broker_v1_update_account_proto != nil {
		return
	}
	file_alpaca_broker_v1_broker_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_broker_v1_update_account_proto_rawDesc), len(file_alpaca_broker_v1_update_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_broker_v1_update_account_proto_goTypes,
		DependencyIndexes: file_alpaca_broker_v1_update_account_proto_depIdxs,
		MessageInfos:      file_alpaca_broker_v1_update_account_proto_msgTypes,
	}.Build()
	File_alpaca_broker_v1_update_account_proto = out.File
	file_alpaca_broker_v1_update_account_proto_goTypes = nil
	file_alpaca_broker_v1_update_account_proto_depIdxs = nil
}
