// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/core/v1/identifiers.proto

package corev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccountID is a unique identifier for an Alpaca trading account.
type AccountID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountID) Reset() {
	*x = AccountID{}
	mi := &file_alpaca_core_v1_identifiers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountID) ProtoMessage() {}

func (x *AccountID) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_core_v1_identifiers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountID.ProtoReflect.Descriptor instead.
func (*AccountID) Descriptor() ([]byte, []int) {
	return file_alpaca_core_v1_identifiers_proto_rawDescGZIP(), []int{0}
}

func (x *AccountID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// OrderID is a unique identifier for an order.
type OrderID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderID) Reset() {
	*x = OrderID{}
	mi := &file_alpaca_core_v1_identifiers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderID) ProtoMessage() {}

func (x *OrderID) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_core_v1_identifiers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderID.ProtoReflect.Descriptor instead.
func (*OrderID) Descriptor() ([]byte, []int) {
	return file_alpaca_core_v1_identifiers_proto_rawDescGZIP(), []int{1}
}

func (x *OrderID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// AssetID is a unique identifier for an asset.
type AssetID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetID) Reset() {
	*x = AssetID{}
	mi := &file_alpaca_core_v1_identifiers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetID) ProtoMessage() {}

func (x *AssetID) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_core_v1_identifiers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetID.ProtoReflect.Descriptor instead.
func (*AssetID) Descriptor() ([]byte, []int) {
	return file_alpaca_core_v1_identifiers_proto_rawDescGZIP(), []int{2}
}

func (x *AssetID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Symbol represents a trading symbol (e.g., AAPL, TSLA, BTC/USD).
type Symbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_alpaca_core_v1_identifiers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_core_v1_identifiers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_alpaca_core_v1_identifiers_proto_rawDescGZIP(), []int{3}
}

func (x *Symbol) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_alpaca_core_v1_identifiers_proto protoreflect.FileDescriptor

const file_alpaca_core_v1_identifiers_proto_rawDesc = "" +
	"\n" +
	" alpaca/core/v1/identifiers.proto\x12\x0ealpaca.core.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"X\n" +
	"\tAccountID\x12K\n" +
	"\x05value\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\x05value\"V\n" +
	"\aOrderID\x12K\n" +
	"\x05value\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$61e69015-8549-4bfd-b9c3-01e75843f47dR\x05value\"V\n" +
	"\aAssetID\x12K\n" +
	"\x05value\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$b0b6dd9d-8b9b-48a9-ba46-b9d54906e415R\x05value\"E\n" +
	"\x06Symbol\x12;\n" +
	"\x05value\x18\x01 \x01(\tB%\xbaH\t\xc8\x01\x01r\x04\x10\x01\x18\f\xba\xb5\x18\x15\n" +
	"\x04AAPL\n" +
	"\x04TSLA\n" +
	"\aBTC/USDR\x05valueB\xbf\x01\n" +
	"\x12com.alpaca.core.v1B\x10IdentifiersProtoP\x01Z=github.com/sebastienmelki/alpaca-go/api/alpaca/core/v1;corev1\xa2\x02\x03ACX\xaa\x02\x0eAlpaca.Core.V1\xca\x02\x0eAlpaca\\Core\\V1\xe2\x02\x1aAlpaca\\Core\\V1\\GPBMetadata\xea\x02\x10Alpaca::Core::V1b\x06proto3"

var (
	file_alpaca_core_v1_identifiers_proto_rawDescOnce sync.Once
	file_alpaca_core_v1_identifiers_proto_rawDescData []byte
)

func file_alpaca_core_v1_identifiers_proto_rawDescGZIP() []byte {
	file_alpaca_core_v1_identifiers_proto_rawDescOnce.Do(func() {
		file_alpaca_core_v1_identifiers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_core_v1_identifiers_proto_rawDesc), len(file_alpaca_core_v1_identifiers_proto_rawDesc)))
	})
	return file_alpaca_core_v1_identifiers_proto_rawDescData
}

var file_alpaca_core_v1_identifiers_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_alpaca_core_v1_identifiers_proto_goTypes = []any{
	(*AccountID)(nil), // 0: alpaca.core.v1.AccountID
	(*OrderID)(nil),   // 1: alpaca.core.v1.OrderID
	(*AssetID)(nil),   // 2: alpaca.core.v1.AssetID
	(*Symbol)(nil),    // 3: alpaca.core.v1.Symbol
}
var file_alpaca_core_v1_identifiers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alpaca_core_v1_identifiers_proto_init() }
func file_alpaca_core_v1_identifiers_proto_init() {
	if File_alpaca_core_v1_identifiers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_core_v1_identifiers_proto_rawDesc), len(file_alpaca_core_v1_identifiers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_core_v1_identifiers_proto_goTypes,
		DependencyIndexes: file_alpaca_core_v1_identifiers_proto_depIdxs,
		MessageInfos:      file_alpaca_core_v1_identifiers_proto_msgTypes,
	}.Build()
	File_alpaca_core_v1_identifiers_proto = out.File
	file_alpaca_core_v1_identifiers_proto_goTypes = nil
	file_alpaca_core_v1_identifiers_proto_depIdxs = nil
}
