// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/account.proto

package tradingv1

import (
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccountStatus represents the status of an account.
type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED       AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_ONBOARDING        AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_SUBMISSION_FAILED AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_SUBMITTED         AccountStatus = 3
	AccountStatus_ACCOUNT_STATUS_ACCOUNT_UPDATED   AccountStatus = 4
	AccountStatus_ACCOUNT_STATUS_APPROVAL_PENDING  AccountStatus = 5
	AccountStatus_ACCOUNT_STATUS_ACTIVE            AccountStatus = 6
	AccountStatus_ACCOUNT_STATUS_REJECTED          AccountStatus = 7
	AccountStatus_ACCOUNT_STATUS_DISABLED          AccountStatus = 8
	AccountStatus_ACCOUNT_STATUS_ACCOUNT_CLOSED    AccountStatus = 9
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_ONBOARDING",
		2: "ACCOUNT_STATUS_SUBMISSION_FAILED",
		3: "ACCOUNT_STATUS_SUBMITTED",
		4: "ACCOUNT_STATUS_ACCOUNT_UPDATED",
		5: "ACCOUNT_STATUS_APPROVAL_PENDING",
		6: "ACCOUNT_STATUS_ACTIVE",
		7: "ACCOUNT_STATUS_REJECTED",
		8: "ACCOUNT_STATUS_DISABLED",
		9: "ACCOUNT_STATUS_ACCOUNT_CLOSED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED":       0,
		"ACCOUNT_STATUS_ONBOARDING":        1,
		"ACCOUNT_STATUS_SUBMISSION_FAILED": 2,
		"ACCOUNT_STATUS_SUBMITTED":         3,
		"ACCOUNT_STATUS_ACCOUNT_UPDATED":   4,
		"ACCOUNT_STATUS_APPROVAL_PENDING":  5,
		"ACCOUNT_STATUS_ACTIVE":            6,
		"ACCOUNT_STATUS_REJECTED":          7,
		"ACCOUNT_STATUS_DISABLED":          8,
		"ACCOUNT_STATUS_ACCOUNT_CLOSED":    9,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_alpaca_trading_v1_account_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_alpaca_trading_v1_account_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_account_proto_rawDescGZIP(), []int{0}
}

// CryptoStatus represents the crypto trading status of an account.
type CryptoStatus int32

const (
	CryptoStatus_CRYPTO_STATUS_UNSPECIFIED CryptoStatus = 0
	CryptoStatus_CRYPTO_STATUS_INACTIVE    CryptoStatus = 1
	CryptoStatus_CRYPTO_STATUS_ACTIVE      CryptoStatus = 2
)

// Enum value maps for CryptoStatus.
var (
	CryptoStatus_name = map[int32]string{
		0: "CRYPTO_STATUS_UNSPECIFIED",
		1: "CRYPTO_STATUS_INACTIVE",
		2: "CRYPTO_STATUS_ACTIVE",
	}
	CryptoStatus_value = map[string]int32{
		"CRYPTO_STATUS_UNSPECIFIED": 0,
		"CRYPTO_STATUS_INACTIVE":    1,
		"CRYPTO_STATUS_ACTIVE":      2,
	}
)

func (x CryptoStatus) Enum() *CryptoStatus {
	p := new(CryptoStatus)
	*p = x
	return p
}

func (x CryptoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CryptoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_alpaca_trading_v1_account_proto_enumTypes[1].Descriptor()
}

func (CryptoStatus) Type() protoreflect.EnumType {
	return &file_alpaca_trading_v1_account_proto_enumTypes[1]
}

func (x CryptoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CryptoStatus.Descriptor instead.
func (CryptoStatus) EnumDescriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_account_proto_rawDescGZIP(), []int{1}
}

// Account represents an Alpaca trading account.
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Account number.
	AccountNumber string `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	// Account status.
	Status AccountStatus `protobuf:"varint,3,opt,name=status,proto3,enum=alpaca.trading.v1.AccountStatus" json:"status,omitempty"`
	// Crypto trading status.
	CryptoStatus CryptoStatus `protobuf:"varint,4,opt,name=crypto_status,json=cryptoStatus,proto3,enum=alpaca.trading.v1.CryptoStatus" json:"crypto_status,omitempty"`
	// Currency (USD).
	Currency string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	// Current available buying power (cash + margin).
	BuyingPower string `protobuf:"bytes,6,opt,name=buying_power,json=buyingPower,proto3" json:"buying_power,omitempty"`
	// Buying power for day trading (4x equity for pattern day traders).
	RegtBuyingPower string `protobuf:"bytes,7,opt,name=regt_buying_power,json=regtBuyingPower,proto3" json:"regt_buying_power,omitempty"`
	// Buying power for day trading (4x equity).
	DaytradingBuyingPower string `protobuf:"bytes,8,opt,name=daytrading_buying_power,json=daytradingBuyingPower,proto3" json:"daytrading_buying_power,omitempty"`
	// Effective buying power.
	EffectiveBuyingPower string `protobuf:"bytes,9,opt,name=effective_buying_power,json=effectiveBuyingPower,proto3" json:"effective_buying_power,omitempty"`
	// Non-marginable buying power.
	NonMarginableBuyingPower string `protobuf:"bytes,10,opt,name=non_marginable_buying_power,json=nonMarginableBuyingPower,proto3" json:"non_marginable_buying_power,omitempty"`
	// Beginning of day day trading buying power.
	BodDtbp string `protobuf:"bytes,11,opt,name=bod_dtbp,json=bodDtbp,proto3" json:"bod_dtbp,omitempty"`
	// Cash balance.
	Cash string `protobuf:"bytes,12,opt,name=cash,proto3" json:"cash,omitempty"`
	// Accrued fees.
	AccruedFees string `protobuf:"bytes,13,opt,name=accrued_fees,json=accruedFees,proto3" json:"accrued_fees,omitempty"`
	// Pending transfer amount.
	PendingTransferIn string `protobuf:"bytes,14,opt,name=pending_transfer_in,json=pendingTransferIn,proto3" json:"pending_transfer_in,omitempty"`
	// Total portfolio value.
	PortfolioValue string `protobuf:"bytes,15,opt,name=portfolio_value,json=portfolioValue,proto3" json:"portfolio_value,omitempty"`
	// Whether the account is a pattern day trader.
	PatternDayTrader bool `protobuf:"varint,16,opt,name=pattern_day_trader,json=patternDayTrader,proto3" json:"pattern_day_trader,omitempty"`
	// Whether trading is blocked.
	TradingBlocked bool `protobuf:"varint,17,opt,name=trading_blocked,json=tradingBlocked,proto3" json:"trading_blocked,omitempty"`
	// Whether transfers are blocked.
	TransfersBlocked bool `protobuf:"varint,18,opt,name=transfers_blocked,json=transfersBlocked,proto3" json:"transfers_blocked,omitempty"`
	// Whether the account is blocked.
	AccountBlocked bool `protobuf:"varint,19,opt,name=account_blocked,json=accountBlocked,proto3" json:"account_blocked,omitempty"`
	// Timestamp when the account was created (RFC 3339).
	CreatedAt string `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Whether trading is suspended by user.
	TradeSuspendedByUser bool `protobuf:"varint,21,opt,name=trade_suspended_by_user,json=tradeSuspendedByUser,proto3" json:"trade_suspended_by_user,omitempty"`
	// Margin multiplier.
	Multiplier string `protobuf:"bytes,22,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	// Whether shorting is enabled.
	ShortingEnabled bool `protobuf:"varint,23,opt,name=shorting_enabled,json=shortingEnabled,proto3" json:"shorting_enabled,omitempty"`
	// Total equity.
	Equity string `protobuf:"bytes,24,opt,name=equity,proto3" json:"equity,omitempty"`
	// Last equity value.
	LastEquity string `protobuf:"bytes,25,opt,name=last_equity,json=lastEquity,proto3" json:"last_equity,omitempty"`
	// Long market value.
	LongMarketValue string `protobuf:"bytes,26,opt,name=long_market_value,json=longMarketValue,proto3" json:"long_market_value,omitempty"`
	// Short market value.
	ShortMarketValue string `protobuf:"bytes,27,opt,name=short_market_value,json=shortMarketValue,proto3" json:"short_market_value,omitempty"`
	// Position market value.
	PositionMarketValue string `protobuf:"bytes,28,opt,name=position_market_value,json=positionMarketValue,proto3" json:"position_market_value,omitempty"`
	// Initial margin.
	InitialMargin string `protobuf:"bytes,29,opt,name=initial_margin,json=initialMargin,proto3" json:"initial_margin,omitempty"`
	// Maintenance margin.
	MaintenanceMargin string `protobuf:"bytes,30,opt,name=maintenance_margin,json=maintenanceMargin,proto3" json:"maintenance_margin,omitempty"`
	// Last maintenance margin.
	LastMaintenanceMargin string `protobuf:"bytes,31,opt,name=last_maintenance_margin,json=lastMaintenanceMargin,proto3" json:"last_maintenance_margin,omitempty"`
	// SMA (Special Memorandum Account).
	Sma string `protobuf:"bytes,32,opt,name=sma,proto3" json:"sma,omitempty"`
	// Day trade count.
	DaytradeCount int32 `protobuf:"varint,33,opt,name=daytrade_count,json=daytradeCount,proto3" json:"daytrade_count,omitempty"`
	// Options trading level (if options enabled).
	OptionsTradingLevel *int32 `protobuf:"varint,34,opt,name=options_trading_level,json=optionsTradingLevel,proto3,oneof" json:"options_trading_level,omitempty"`
	// Options approved level.
	OptionsApprovedLevel *int32 `protobuf:"varint,35,opt,name=options_approved_level,json=optionsApprovedLevel,proto3,oneof" json:"options_approved_level,omitempty"`
	// Options buying power.
	OptionsBuyingPower *string `protobuf:"bytes,36,opt,name=options_buying_power,json=optionsBuyingPower,proto3,oneof" json:"options_buying_power,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_alpaca_trading_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *Account) GetCryptoStatus() CryptoStatus {
	if x != nil {
		return x.CryptoStatus
	}
	return CryptoStatus_CRYPTO_STATUS_UNSPECIFIED
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetBuyingPower() string {
	if x != nil {
		return x.BuyingPower
	}
	return ""
}

func (x *Account) GetRegtBuyingPower() string {
	if x != nil {
		return x.RegtBuyingPower
	}
	return ""
}

func (x *Account) GetDaytradingBuyingPower() string {
	if x != nil {
		return x.DaytradingBuyingPower
	}
	return ""
}

func (x *Account) GetEffectiveBuyingPower() string {
	if x != nil {
		return x.EffectiveBuyingPower
	}
	return ""
}

func (x *Account) GetNonMarginableBuyingPower() string {
	if x != nil {
		return x.NonMarginableBuyingPower
	}
	return ""
}

func (x *Account) GetBodDtbp() string {
	if x != nil {
		return x.BodDtbp
	}
	return ""
}

func (x *Account) GetCash() string {
	if x != nil {
		return x.Cash
	}
	return ""
}

func (x *Account) GetAccruedFees() string {
	if x != nil {
		return x.AccruedFees
	}
	return ""
}

func (x *Account) GetPendingTransferIn() string {
	if x != nil {
		return x.PendingTransferIn
	}
	return ""
}

func (x *Account) GetPortfolioValue() string {
	if x != nil {
		return x.PortfolioValue
	}
	return ""
}

func (x *Account) GetPatternDayTrader() bool {
	if x != nil {
		return x.PatternDayTrader
	}
	return false
}

func (x *Account) GetTradingBlocked() bool {
	if x != nil {
		return x.TradingBlocked
	}
	return false
}

func (x *Account) GetTransfersBlocked() bool {
	if x != nil {
		return x.TransfersBlocked
	}
	return false
}

func (x *Account) GetAccountBlocked() bool {
	if x != nil {
		return x.AccountBlocked
	}
	return false
}

func (x *Account) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Account) GetTradeSuspendedByUser() bool {
	if x != nil {
		return x.TradeSuspendedByUser
	}
	return false
}

func (x *Account) GetMultiplier() string {
	if x != nil {
		return x.Multiplier
	}
	return ""
}

func (x *Account) GetShortingEnabled() bool {
	if x != nil {
		return x.ShortingEnabled
	}
	return false
}

func (x *Account) GetEquity() string {
	if x != nil {
		return x.Equity
	}
	return ""
}

func (x *Account) GetLastEquity() string {
	if x != nil {
		return x.LastEquity
	}
	return ""
}

func (x *Account) GetLongMarketValue() string {
	if x != nil {
		return x.LongMarketValue
	}
	return ""
}

func (x *Account) GetShortMarketValue() string {
	if x != nil {
		return x.ShortMarketValue
	}
	return ""
}

func (x *Account) GetPositionMarketValue() string {
	if x != nil {
		return x.PositionMarketValue
	}
	return ""
}

func (x *Account) GetInitialMargin() string {
	if x != nil {
		return x.InitialMargin
	}
	return ""
}

func (x *Account) GetMaintenanceMargin() string {
	if x != nil {
		return x.MaintenanceMargin
	}
	return ""
}

func (x *Account) GetLastMaintenanceMargin() string {
	if x != nil {
		return x.LastMaintenanceMargin
	}
	return ""
}

func (x *Account) GetSma() string {
	if x != nil {
		return x.Sma
	}
	return ""
}

func (x *Account) GetDaytradeCount() int32 {
	if x != nil {
		return x.DaytradeCount
	}
	return 0
}

func (x *Account) GetOptionsTradingLevel() int32 {
	if x != nil && x.OptionsTradingLevel != nil {
		return *x.OptionsTradingLevel
	}
	return 0
}

func (x *Account) GetOptionsApprovedLevel() int32 {
	if x != nil && x.OptionsApprovedLevel != nil {
		return *x.OptionsApprovedLevel
	}
	return 0
}

func (x *Account) GetOptionsBuyingPower() string {
	if x != nil && x.OptionsBuyingPower != nil {
		return *x.OptionsBuyingPower
	}
	return ""
}

var File_alpaca_trading_v1_account_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1falpaca/trading/v1/account.proto\x12\x11alpaca.trading.v1\x1a\x1csebuf/http/annotations.proto\"\xde\x10\n" +
	"\aAccount\x12:\n" +
	"\x02id\x18\x01 \x01(\tB*\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\x02id\x127\n" +
	"\x0eaccount_number\x18\x02 \x01(\tB\x10\xba\xb5\x18\f\n" +
	"\n" +
	"010203ABCDR\raccountNumber\x12A\n" +
	"\x06status\x18\x03 \x01(\x0e2 .alpaca.trading.v1.AccountStatusB\a\xba\xb5\x18\x03\n" +
	"\x016R\x06status\x12M\n" +
	"\rcrypto_status\x18\x04 \x01(\x0e2\x1f.alpaca.trading.v1.CryptoStatusB\a\xba\xb5\x18\x03\n" +
	"\x012R\fcryptoStatus\x12%\n" +
	"\bcurrency\x18\x05 \x01(\tB\t\xba\xb5\x18\x05\n" +
	"\x03USDR\bcurrency\x121\n" +
	"\fbuying_power\x18\x06 \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b50000.00R\vbuyingPower\x12:\n" +
	"\x11regt_buying_power\x18\a \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b50000.00R\x0fregtBuyingPower\x12G\n" +
	"\x17daytrading_buying_power\x18\b \x01(\tB\x0f\xba\xb5\x18\v\n" +
	"\t200000.00R\x15daytradingBuyingPower\x12D\n" +
	"\x16effective_buying_power\x18\t \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b50000.00R\x14effectiveBuyingPower\x12M\n" +
	"\x1bnon_marginable_buying_power\x18\n" +
	" \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b50000.00R\x18nonMarginableBuyingPower\x12*\n" +
	"\bbod_dtbp\x18\v \x01(\tB\x0f\xba\xb5\x18\v\n" +
	"\t200000.00R\abodDtbp\x12\"\n" +
	"\x04cash\x18\f \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b50000.00R\x04cash\x12-\n" +
	"\faccrued_fees\x18\r \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x040.00R\vaccruedFees\x12:\n" +
	"\x13pending_transfer_in\x18\x0e \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x040.00R\x11pendingTransferIn\x127\n" +
	"\x0fportfolio_value\x18\x0f \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b50000.00R\x0eportfolioValue\x129\n" +
	"\x12pattern_day_trader\x18\x10 \x01(\bB\v\xba\xb5\x18\a\n" +
	"\x05falseR\x10patternDayTrader\x124\n" +
	"\x0ftrading_blocked\x18\x11 \x01(\bB\v\xba\xb5\x18\a\n" +
	"\x05falseR\x0etradingBlocked\x128\n" +
	"\x11transfers_blocked\x18\x12 \x01(\bB\v\xba\xb5\x18\a\n" +
	"\x05falseR\x10transfersBlocked\x124\n" +
	"\x0faccount_blocked\x18\x13 \x01(\bB\v\xba\xb5\x18\a\n" +
	"\x05falseR\x0eaccountBlocked\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\tB\x1a\xba\xb5\x18\x16\n" +
	"\x142021-01-01T00:00:00ZR\tcreatedAt\x12B\n" +
	"\x17trade_suspended_by_user\x18\x15 \x01(\bB\v\xba\xb5\x18\a\n" +
	"\x05falseR\x14tradeSuspendedByUser\x12'\n" +
	"\n" +
	"multiplier\x18\x16 \x01(\tB\a\xba\xb5\x18\x03\n" +
	"\x014R\n" +
	"multiplier\x125\n" +
	"\x10shorting_enabled\x18\x17 \x01(\bB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x04trueR\x0fshortingEnabled\x12&\n" +
	"\x06equity\x18\x18 \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b50000.00R\x06equity\x12/\n" +
	"\vlast_equity\x18\x19 \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b50000.00R\n" +
	"lastEquity\x126\n" +
	"\x11long_market_value\x18\x1a \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x040.00R\x0flongMarketValue\x128\n" +
	"\x12short_market_value\x18\x1b \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x040.00R\x10shortMarketValue\x12>\n" +
	"\x15position_market_value\x18\x1c \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x040.00R\x13positionMarketValue\x121\n" +
	"\x0einitial_margin\x18\x1d \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x040.00R\rinitialMargin\x129\n" +
	"\x12maintenance_margin\x18\x1e \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x040.00R\x11maintenanceMargin\x12B\n" +
	"\x17last_maintenance_margin\x18\x1f \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x040.00R\x15lastMaintenanceMargin\x12\x1c\n" +
	"\x03sma\x18  \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x040.00R\x03sma\x12.\n" +
	"\x0edaytrade_count\x18! \x01(\x05B\a\xba\xb5\x18\x03\n" +
	"\x010R\rdaytradeCount\x12@\n" +
	"\x15options_trading_level\x18\" \x01(\x05B\a\xba\xb5\x18\x03\n" +
	"\x012H\x00R\x13optionsTradingLevel\x88\x01\x01\x12B\n" +
	"\x16options_approved_level\x18# \x01(\x05B\a\xba\xb5\x18\x03\n" +
	"\x012H\x01R\x14optionsApprovedLevel\x88\x01\x01\x12E\n" +
	"\x14options_buying_power\x18$ \x01(\tB\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b25000.00H\x02R\x12optionsBuyingPower\x88\x01\x01B\x18\n" +
	"\x16_options_trading_levelB\x19\n" +
	"\x17_options_approved_levelB\x17\n" +
	"\x15_options_buying_power*\xd3\x02\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ACCOUNT_STATUS_ONBOARDING\x10\x01\x12$\n" +
	" ACCOUNT_STATUS_SUBMISSION_FAILED\x10\x02\x12\x1c\n" +
	"\x18ACCOUNT_STATUS_SUBMITTED\x10\x03\x12\"\n" +
	"\x1eACCOUNT_STATUS_ACCOUNT_UPDATED\x10\x04\x12#\n" +
	"\x1fACCOUNT_STATUS_APPROVAL_PENDING\x10\x05\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x06\x12\x1b\n" +
	"\x17ACCOUNT_STATUS_REJECTED\x10\a\x12\x1b\n" +
	"\x17ACCOUNT_STATUS_DISABLED\x10\b\x12!\n" +
	"\x1dACCOUNT_STATUS_ACCOUNT_CLOSED\x10\t*c\n" +
	"\fCryptoStatus\x12\x1d\n" +
	"\x19CRYPTO_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CRYPTO_STATUS_INACTIVE\x10\x01\x12\x18\n" +
	"\x14CRYPTO_STATUS_ACTIVE\x10\x02B\xd0\x01\n" +
	"\x15com.alpaca.trading.v1B\fAccountProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var (
	file_alpaca_trading_v1_account_proto_rawDescOnce sync.Once
	file_alpaca_trading_v1_account_proto_rawDescData []byte
)

func file_alpaca_trading_v1_account_proto_rawDescGZIP() []byte {
	file_alpaca_trading_v1_account_proto_rawDescOnce.Do(func() {
		file_alpaca_trading_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_account_proto_rawDesc), len(file_alpaca_trading_v1_account_proto_rawDesc)))
	})
	return file_alpaca_trading_v1_account_proto_rawDescData
}

var file_alpaca_trading_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_alpaca_trading_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alpaca_trading_v1_account_proto_goTypes = []any{
	(AccountStatus)(0), // 0: alpaca.trading.v1.AccountStatus
	(CryptoStatus)(0),  // 1: alpaca.trading.v1.CryptoStatus
	(*Account)(nil),    // 2: alpaca.trading.v1.Account
}
var file_alpaca_trading_v1_account_proto_depIdxs = []int32{
	0, // 0: alpaca.trading.v1.Account.status:type_name -> alpaca.trading.v1.AccountStatus
	1, // 1: alpaca.trading.v1.Account.crypto_status:type_name -> alpaca.trading.v1.CryptoStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_account_proto_init() }
func file_alpaca_trading_v1_account_proto_init() {
	if File_alpaca_trading_v1_account_proto != nil {
		return
	}
	file_alpaca_trading_v1_account_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_account_proto_rawDesc), len(file_alpaca_trading_v1_account_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_trading_v1_account_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_account_proto_depIdxs,
		EnumInfos:         file_alpaca_trading_v1_account_proto_enumTypes,
		MessageInfos:      file_alpaca_trading_v1_account_proto_msgTypes,
	}.Build()
	File_alpaca_trading_v1_account_proto = out.File
	file_alpaca_trading_v1_account_proto_goTypes = nil
	file_alpaca_trading_v1_account_proto_depIdxs = nil
}
