// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/cancel_all_orders.proto

package tradingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CancelAllOrdersRequest is the request to cancel all open orders.
type CancelAllOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account ID (bound from path variable).
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllOrdersRequest) Reset() {
	*x = CancelAllOrdersRequest{}
	mi := &file_alpaca_trading_v1_cancel_all_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllOrdersRequest) ProtoMessage() {}

func (x *CancelAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_cancel_all_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*CancelAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_cancel_all_orders_proto_rawDescGZIP(), []int{0}
}

func (x *CancelAllOrdersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// CanceledOrder represents a canceled order in the response.
type CanceledOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The order ID that was canceled.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// HTTP status code for this cancellation.
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	// The order body if cancellation was successful.
	Body          *string `protobuf:"bytes,3,opt,name=body,proto3,oneof" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanceledOrder) Reset() {
	*x = CanceledOrder{}
	mi := &file_alpaca_trading_v1_cancel_all_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanceledOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanceledOrder) ProtoMessage() {}

func (x *CanceledOrder) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_cancel_all_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanceledOrder.ProtoReflect.Descriptor instead.
func (*CanceledOrder) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_cancel_all_orders_proto_rawDescGZIP(), []int{1}
}

func (x *CanceledOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CanceledOrder) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CanceledOrder) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

// CancelAllOrdersResponse is the response after canceling all orders.
type CancelAllOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of canceled orders.
	Orders        []*CanceledOrder `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllOrdersResponse) Reset() {
	*x = CancelAllOrdersResponse{}
	mi := &file_alpaca_trading_v1_cancel_all_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllOrdersResponse) ProtoMessage() {}

func (x *CancelAllOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_cancel_all_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllOrdersResponse.ProtoReflect.Descriptor instead.
func (*CancelAllOrdersResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_cancel_all_orders_proto_rawDescGZIP(), []int{2}
}

func (x *CancelAllOrdersResponse) GetOrders() []*CanceledOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_alpaca_trading_v1_cancel_all_orders_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_cancel_all_orders_proto_rawDesc = "" +
	"\n" +
	")alpaca/trading/v1/cancel_all_orders.proto\x12\x11alpaca.trading.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"n\n" +
	"\x16CancelAllOrdersRequest\x12T\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountId\"\x90\x01\n" +
	"\rCanceledOrder\x12:\n" +
	"\x02id\x18\x01 \x01(\tB*\xba\xb5\x18&\n" +
	"$61e69015-8549-4bfd-b9c3-01e75843f47dR\x02id\x12!\n" +
	"\x06status\x18\x02 \x01(\x05B\t\xba\xb5\x18\x05\n" +
	"\x03200R\x06status\x12\x17\n" +
	"\x04body\x18\x03 \x01(\tH\x00R\x04body\x88\x01\x01B\a\n" +
	"\x05_body\"S\n" +
	"\x17CancelAllOrdersResponse\x128\n" +
	"\x06orders\x18\x01 \x03(\v2 .alpaca.trading.v1.CanceledOrderR\x06ordersB\xd8\x01\n" +
	"\x15com.alpaca.trading.v1B\x14CancelAllOrdersProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var (
	file_alpaca_trading_v1_cancel_all_orders_proto_rawDescOnce sync.Once
	file_alpaca_trading_v1_cancel_all_orders_proto_rawDescData []byte
)

func file_alpaca_trading_v1_cancel_all_orders_proto_rawDescGZIP() []byte {
	file_alpaca_trading_v1_cancel_all_orders_proto_rawDescOnce.Do(func() {
		file_alpaca_trading_v1_cancel_all_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_cancel_all_orders_proto_rawDesc), len(file_alpaca_trading_v1_cancel_all_orders_proto_rawDesc)))
	})
	return file_alpaca_trading_v1_cancel_all_orders_proto_rawDescData
}

var file_alpaca_trading_v1_cancel_all_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_alpaca_trading_v1_cancel_all_orders_proto_goTypes = []any{
	(*CancelAllOrdersRequest)(nil),  // 0: alpaca.trading.v1.CancelAllOrdersRequest
	(*CanceledOrder)(nil),           // 1: alpaca.trading.v1.CanceledOrder
	(*CancelAllOrdersResponse)(nil), // 2: alpaca.trading.v1.CancelAllOrdersResponse
}
var file_alpaca_trading_v1_cancel_all_orders_proto_depIdxs = []int32{
	1, // 0: alpaca.trading.v1.CancelAllOrdersResponse.orders:type_name -> alpaca.trading.v1.CanceledOrder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_cancel_all_orders_proto_init() }
func file_alpaca_trading_v1_cancel_all_orders_proto_init() {
	if File_alpaca_trading_v1_cancel_all_orders_proto != nil {
		return
	}
	file_alpaca_trading_v1_cancel_all_orders_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_cancel_all_orders_proto_rawDesc), len(file_alpaca_trading_v1_cancel_all_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_trading_v1_cancel_all_orders_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_cancel_all_orders_proto_depIdxs,
		MessageInfos:      file_alpaca_trading_v1_cancel_all_orders_proto_msgTypes,
	}.Build()
	File_alpaca_trading_v1_cancel_all_orders_proto = out.File
	file_alpaca_trading_v1_cancel_all_orders_proto_goTypes = nil
	file_alpaca_trading_v1_cancel_all_orders_proto_depIdxs = nil
}
