// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/close_all_positions.proto

package tradingv1

import (
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CloseAllPositionsRequest is the request to close all open positions.
type CloseAllPositionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to cancel all open orders before closing positions.
	CancelOrders  bool `protobuf:"varint,1,opt,name=cancel_orders,json=cancelOrders,proto3" json:"cancel_orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAllPositionsRequest) Reset() {
	*x = CloseAllPositionsRequest{}
	mi := &file_alpaca_trading_v1_close_all_positions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAllPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAllPositionsRequest) ProtoMessage() {}

func (x *CloseAllPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_close_all_positions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAllPositionsRequest.ProtoReflect.Descriptor instead.
func (*CloseAllPositionsRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_close_all_positions_proto_rawDescGZIP(), []int{0}
}

func (x *CloseAllPositionsRequest) GetCancelOrders() bool {
	if x != nil {
		return x.CancelOrders
	}
	return false
}

// ClosedPosition represents the result of closing a single position.
type ClosedPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The symbol of the closed position.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// HTTP status code for this close operation.
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	// The closing order if successful.
	Order         *Order `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosedPosition) Reset() {
	*x = ClosedPosition{}
	mi := &file_alpaca_trading_v1_close_all_positions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosedPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosedPosition) ProtoMessage() {}

func (x *ClosedPosition) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_close_all_positions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosedPosition.ProtoReflect.Descriptor instead.
func (*ClosedPosition) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_close_all_positions_proto_rawDescGZIP(), []int{1}
}

func (x *ClosedPosition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ClosedPosition) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ClosedPosition) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// CloseAllPositionsResponse is the response after closing all positions.
type CloseAllPositionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of closed positions.
	Positions     []*ClosedPosition `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAllPositionsResponse) Reset() {
	*x = CloseAllPositionsResponse{}
	mi := &file_alpaca_trading_v1_close_all_positions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAllPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAllPositionsResponse) ProtoMessage() {}

func (x *CloseAllPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_close_all_positions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAllPositionsResponse.ProtoReflect.Descriptor instead.
func (*CloseAllPositionsResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_close_all_positions_proto_rawDescGZIP(), []int{2}
}

func (x *CloseAllPositionsResponse) GetPositions() []*ClosedPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

var File_alpaca_trading_v1_close_all_positions_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_close_all_positions_proto_rawDesc = "" +
	"\n" +
	"+alpaca/trading/v1/close_all_positions.proto\x12\x11alpaca.trading.v1\x1a\x1csebuf/http/annotations.proto\x1a\x1dalpaca/trading/v1/order.proto\"^\n" +
	"\x18CloseAllPositionsRequest\x12B\n" +
	"\rcancel_orders\x18\x01 \x01(\bB\x1d\xba\xb5\x18\x06\n" +
	"\x04trueµ\x18\x0f\n" +
	"\rcancel_ordersR\fcancelOrders\"\x87\x01\n" +
	"\x0eClosedPosition\x12\"\n" +
	"\x06symbol\x18\x01 \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x04AAPLR\x06symbol\x12!\n" +
	"\x06status\x18\x02 \x01(\x05B\t\xba\xb5\x18\x05\n" +
	"\x03200R\x06status\x12.\n" +
	"\x05order\x18\x03 \x01(\v2\x18.alpaca.trading.v1.OrderR\x05order\"\\\n" +
	"\x19CloseAllPositionsResponse\x12?\n" +
	"\tpositions\x18\x01 \x03(\v2!.alpaca.trading.v1.ClosedPositionR\tpositionsB\xda\x01\n" +
	"\x15com.alpaca.trading.v1B\x16CloseAllPositionsProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var (
	file_alpaca_trading_v1_close_all_positions_proto_rawDescOnce sync.Once
	file_alpaca_trading_v1_close_all_positions_proto_rawDescData []byte
)

func file_alpaca_trading_v1_close_all_positions_proto_rawDescGZIP() []byte {
	file_alpaca_trading_v1_close_all_positions_proto_rawDescOnce.Do(func() {
		file_alpaca_trading_v1_close_all_positions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_close_all_positions_proto_rawDesc), len(file_alpaca_trading_v1_close_all_positions_proto_rawDesc)))
	})
	return file_alpaca_trading_v1_close_all_positions_proto_rawDescData
}

var file_alpaca_trading_v1_close_all_positions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_alpaca_trading_v1_close_all_positions_proto_goTypes = []any{
	(*CloseAllPositionsRequest)(nil),  // 0: alpaca.trading.v1.CloseAllPositionsRequest
	(*ClosedPosition)(nil),            // 1: alpaca.trading.v1.ClosedPosition
	(*CloseAllPositionsResponse)(nil), // 2: alpaca.trading.v1.CloseAllPositionsResponse
	(*Order)(nil),                     // 3: alpaca.trading.v1.Order
}
var file_alpaca_trading_v1_close_all_positions_proto_depIdxs = []int32{
	3, // 0: alpaca.trading.v1.ClosedPosition.order:type_name -> alpaca.trading.v1.Order
	1, // 1: alpaca.trading.v1.CloseAllPositionsResponse.positions:type_name -> alpaca.trading.v1.ClosedPosition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_close_all_positions_proto_init() }
func file_alpaca_trading_v1_close_all_positions_proto_init() {
	if File_alpaca_trading_v1_close_all_positions_proto != nil {
		return
	}
	file_alpaca_trading_v1_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_close_all_positions_proto_rawDesc), len(file_alpaca_trading_v1_close_all_positions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_trading_v1_close_all_positions_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_close_all_positions_proto_depIdxs,
		MessageInfos:      file_alpaca_trading_v1_close_all_positions_proto_msgTypes,
	}.Build()
	File_alpaca_trading_v1_close_all_positions_proto = out.File
	file_alpaca_trading_v1_close_all_positions_proto_goTypes = nil
	file_alpaca_trading_v1_close_all_positions_proto_depIdxs = nil
}
