// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/get_order.proto

package tradingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetOrderRequest is the request to get an order by ID.
type GetOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account ID (bound from path variable).
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// The order ID (bound from path variable).
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Whether to include nested leg orders.
	Nested        bool `protobuf:"varint,3,opt,name=nested,proto3" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_alpaca_trading_v1_get_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_get_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_get_order_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderRequest) GetNested() bool {
	if x != nil {
		return x.Nested
	}
	return false
}

var File_alpaca_trading_v1_get_order_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_get_order_proto_rawDesc = "" +
	"\n" +
	"!alpaca/trading/v1/get_order.proto\x12\x11alpaca.trading.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\"\xea\x01\n" +
	"\x0fGetOrderRequest\x12T\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountId\x12P\n" +
	"\border_id\x18\x02 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$61e69015-8549-4bfd-b9c3-01e75843f47dR\aorderId\x12/\n" +
	"\x06nested\x18\x03 \x01(\bB\x17\xba\xb5\x18\a\n" +
	"\x05falseµ\x18\b\n" +
	"\x06nestedR\x06nestedB\xd1\x01\n" +
	"\x15com.alpaca.trading.v1B\rGetOrderProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var (
	file_alpaca_trading_v1_get_order_proto_rawDescOnce sync.Once
	file_alpaca_trading_v1_get_order_proto_rawDescData []byte
)

func file_alpaca_trading_v1_get_order_proto_rawDescGZIP() []byte {
	file_alpaca_trading_v1_get_order_proto_rawDescOnce.Do(func() {
		file_alpaca_trading_v1_get_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_get_order_proto_rawDesc), len(file_alpaca_trading_v1_get_order_proto_rawDesc)))
	})
	return file_alpaca_trading_v1_get_order_proto_rawDescData
}

var file_alpaca_trading_v1_get_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alpaca_trading_v1_get_order_proto_goTypes = []any{
	(*GetOrderRequest)(nil), // 0: alpaca.trading.v1.GetOrderRequest
}
var file_alpaca_trading_v1_get_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_get_order_proto_init() }
func file_alpaca_trading_v1_get_order_proto_init() {
	if File_alpaca_trading_v1_get_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_get_order_proto_rawDesc), len(file_alpaca_trading_v1_get_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_trading_v1_get_order_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_get_order_proto_depIdxs,
		MessageInfos:      file_alpaca_trading_v1_get_order_proto_msgTypes,
	}.Build()
	File_alpaca_trading_v1_get_order_proto = out.File
	file_alpaca_trading_v1_get_order_proto_goTypes = nil
	file_alpaca_trading_v1_get_order_proto_depIdxs = nil
}
