// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/list_positions.proto

package tradingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListPositionsRequest is the request to list all open positions.
type ListPositionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account ID (bound from path variable).
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsRequest) Reset() {
	*x = ListPositionsRequest{}
	mi := &file_alpaca_trading_v1_list_positions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsRequest) ProtoMessage() {}

func (x *ListPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_list_positions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsRequest.ProtoReflect.Descriptor instead.
func (*ListPositionsRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_list_positions_proto_rawDescGZIP(), []int{0}
}

func (x *ListPositionsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// ListPositionsResponse is the response containing all open positions.
type ListPositionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of open positions.
	Positions     []*Position `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsResponse) Reset() {
	*x = ListPositionsResponse{}
	mi := &file_alpaca_trading_v1_list_positions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsResponse) ProtoMessage() {}

func (x *ListPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_list_positions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsResponse.ProtoReflect.Descriptor instead.
func (*ListPositionsResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_list_positions_proto_rawDescGZIP(), []int{1}
}

func (x *ListPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

var File_alpaca_trading_v1_list_positions_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_list_positions_proto_rawDesc = "" +
	"\n" +
	"&alpaca/trading/v1/list_positions.proto\x12\x11alpaca.trading.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a alpaca/trading/v1/position.proto\"l\n" +
	"\x14ListPositionsRequest\x12T\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$904837e3-3b76-47ec-b432-046db621571bR\taccountId\"R\n" +
	"\x15ListPositionsResponse\x129\n" +
	"\tpositions\x18\x01 \x03(\v2\x1b.alpaca.trading.v1.PositionR\tpositionsB\xd6\x01\n" +
	"\x15com.alpaca.trading.v1B\x12ListPositionsProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var (
	file_alpaca_trading_v1_list_positions_proto_rawDescOnce sync.Once
	file_alpaca_trading_v1_list_positions_proto_rawDescData []byte
)

func file_alpaca_trading_v1_list_positions_proto_rawDescGZIP() []byte {
	file_alpaca_trading_v1_list_positions_proto_rawDescOnce.Do(func() {
		file_alpaca_trading_v1_list_positions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_list_positions_proto_rawDesc), len(file_alpaca_trading_v1_list_positions_proto_rawDesc)))
	})
	return file_alpaca_trading_v1_list_positions_proto_rawDescData
}

var file_alpaca_trading_v1_list_positions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alpaca_trading_v1_list_positions_proto_goTypes = []any{
	(*ListPositionsRequest)(nil),  // 0: alpaca.trading.v1.ListPositionsRequest
	(*ListPositionsResponse)(nil), // 1: alpaca.trading.v1.ListPositionsResponse
	(*Position)(nil),              // 2: alpaca.trading.v1.Position
}
var file_alpaca_trading_v1_list_positions_proto_depIdxs = []int32{
	2, // 0: alpaca.trading.v1.ListPositionsResponse.positions:type_name -> alpaca.trading.v1.Position
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_list_positions_proto_init() }
func file_alpaca_trading_v1_list_positions_proto_init() {
	if File_alpaca_trading_v1_list_positions_proto != nil {
		return
	}
	file_alpaca_trading_v1_position_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_list_positions_proto_rawDesc), len(file_alpaca_trading_v1_list_positions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_trading_v1_list_positions_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_list_positions_proto_depIdxs,
		MessageInfos:      file_alpaca_trading_v1_list_positions_proto_msgTypes,
	}.Build()
	File_alpaca_trading_v1_list_positions_proto = out.File
	file_alpaca_trading_v1_list_positions_proto_goTypes = nil
	file_alpaca_trading_v1_list_positions_proto_depIdxs = nil
}
