// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/list_watchlists.proto

package tradingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListWatchlistsRequest is the request to list watchlists.
type ListWatchlistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchlistsRequest) Reset() {
	*x = ListWatchlistsRequest{}
	mi := &file_alpaca_trading_v1_list_watchlists_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchlistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchlistsRequest) ProtoMessage() {}

func (x *ListWatchlistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_list_watchlists_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchlistsRequest.ProtoReflect.Descriptor instead.
func (*ListWatchlistsRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_list_watchlists_proto_rawDescGZIP(), []int{0}
}

// ListWatchlistsResponse is the response containing a list of watchlists.
type ListWatchlistsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of watchlists.
	Watchlists    []*Watchlist `protobuf:"bytes,1,rep,name=watchlists,proto3" json:"watchlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWatchlistsResponse) Reset() {
	*x = ListWatchlistsResponse{}
	mi := &file_alpaca_trading_v1_list_watchlists_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWatchlistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWatchlistsResponse) ProtoMessage() {}

func (x *ListWatchlistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_list_watchlists_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWatchlistsResponse.ProtoReflect.Descriptor instead.
func (*ListWatchlistsResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_list_watchlists_proto_rawDescGZIP(), []int{1}
}

func (x *ListWatchlistsResponse) GetWatchlists() []*Watchlist {
	if x != nil {
		return x.Watchlists
	}
	return nil
}

var File_alpaca_trading_v1_list_watchlists_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_list_watchlists_proto_rawDesc = "" +
	"\n" +
	"'alpaca/trading/v1/list_watchlists.proto\x12\x11alpaca.trading.v1\x1a!alpaca/trading/v1/watchlist.proto\"\x17\n" +
	"\x15ListWatchlistsRequest\"V\n" +
	"\x16ListWatchlistsResponse\x12<\n" +
	"\n" +
	"watchlists\x18\x01 \x03(\v2\x1c.alpaca.trading.v1.WatchlistR\n" +
	"watchlistsB\xd7\x01\n" +
	"\x15com.alpaca.trading.v1B\x13ListWatchlistsProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var (
	file_alpaca_trading_v1_list_watchlists_proto_rawDescOnce sync.Once
	file_alpaca_trading_v1_list_watchlists_proto_rawDescData []byte
)

func file_alpaca_trading_v1_list_watchlists_proto_rawDescGZIP() []byte {
	file_alpaca_trading_v1_list_watchlists_proto_rawDescOnce.Do(func() {
		file_alpaca_trading_v1_list_watchlists_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_list_watchlists_proto_rawDesc), len(file_alpaca_trading_v1_list_watchlists_proto_rawDesc)))
	})
	return file_alpaca_trading_v1_list_watchlists_proto_rawDescData
}

var file_alpaca_trading_v1_list_watchlists_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alpaca_trading_v1_list_watchlists_proto_goTypes = []any{
	(*ListWatchlistsRequest)(nil),  // 0: alpaca.trading.v1.ListWatchlistsRequest
	(*ListWatchlistsResponse)(nil), // 1: alpaca.trading.v1.ListWatchlistsResponse
	(*Watchlist)(nil),              // 2: alpaca.trading.v1.Watchlist
}
var file_alpaca_trading_v1_list_watchlists_proto_depIdxs = []int32{
	2, // 0: alpaca.trading.v1.ListWatchlistsResponse.watchlists:type_name -> alpaca.trading.v1.Watchlist
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_list_watchlists_proto_init() }
func file_alpaca_trading_v1_list_watchlists_proto_init() {
	if File_alpaca_trading_v1_list_watchlists_proto != nil {
		return
	}
	file_alpaca_trading_v1_watchlist_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_list_watchlists_proto_rawDesc), len(file_alpaca_trading_v1_list_watchlists_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_trading_v1_list_watchlists_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_list_watchlists_proto_depIdxs,
		MessageInfos:      file_alpaca_trading_v1_list_watchlists_proto_msgTypes,
	}.Build()
	File_alpaca_trading_v1_list_watchlists_proto = out.File
	file_alpaca_trading_v1_list_watchlists_proto_goTypes = nil
	file_alpaca_trading_v1_list_watchlists_proto_depIdxs = nil
}
