// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/list_orders.proto

package tradingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListOrdersRequest is the request to list orders.
type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by order status (open, closed, all).
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Maximum number of orders to return (default 50, max 500).
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Cursor for pagination (order ID to start after).
	After string `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	// Filter by orders updated before this timestamp.
	Until string `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`
	// Sort direction (asc or desc).
	Direction string `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	// Whether to include nested leg orders.
	Nested bool `protobuf:"varint,6,opt,name=nested,proto3" json:"nested,omitempty"`
	// Filter by symbols (comma-separated).
	Symbols string `protobuf:"bytes,7,opt,name=symbols,proto3" json:"symbols,omitempty"`
	// Filter by side (buy or sell).
	Side          string `protobuf:"bytes,8,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_alpaca_trading_v1_list_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_list_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_list_orders_proto_rawDescGZIP(), []int{0}
}

func (x *ListOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ListOrdersRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *ListOrdersRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ListOrdersRequest) GetNested() bool {
	if x != nil {
		return x.Nested
	}
	return false
}

func (x *ListOrdersRequest) GetSymbols() string {
	if x != nil {
		return x.Symbols
	}
	return ""
}

func (x *ListOrdersRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

// ListOrdersResponse is the response containing a list of orders.
type ListOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of orders.
	Orders        []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_alpaca_trading_v1_list_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_list_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_list_orders_proto_rawDescGZIP(), []int{1}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_alpaca_trading_v1_list_orders_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_list_orders_proto_rawDesc = "" +
	"\n" +
	"#alpaca/trading/v1/list_orders.proto\x12\x11alpaca.trading.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a\x1dalpaca/trading/v1/order.proto\"\xcd\x03\n" +
	"\x11ListOrdersRequest\x12.\n" +
	"\x06status\x18\x01 \x01(\tB\x16\xba\xb5\x18\x06\n" +
	"\x04openµ\x18\b\n" +
	"\x06statusR\x06status\x123\n" +
	"\x05limit\x18\x02 \x01(\x05B\x1d\xbaH\a\x1a\x05\x18\xf4\x03(\x01\xba\xb5\x18\x04\n" +
	"\x0250µ\x18\a\n" +
	"\x05limitR\x05limit\x12K\n" +
	"\x05after\x18\x03 \x01(\tB5\xba\xb5\x18&\n" +
	"$61e69015-8549-4bfd-b9c3-01e75843f47dµ\x18\a\n" +
	"\x05afterR\x05after\x12;\n" +
	"\x05until\x18\x04 \x01(\tB%\xba\xb5\x18\x16\n" +
	"\x142024-01-15T10:30:00Zµ\x18\a\n" +
	"\x05untilR\x05until\x127\n" +
	"\tdirection\x18\x05 \x01(\tB\x19\xba\xb5\x18\x06\n" +
	"\x04descµ\x18\v\n" +
	"\tdirectionR\tdirection\x12/\n" +
	"\x06nested\x18\x06 \x01(\bB\x17\xba\xb5\x18\a\n" +
	"\x05falseµ\x18\b\n" +
	"\x06nestedR\x06nested\x126\n" +
	"\asymbols\x18\a \x01(\tB\x1c\xba\xb5\x18\v\n" +
	"\tAAPL,TSLAµ\x18\t\n" +
	"\asymbolsR\asymbols\x12'\n" +
	"\x04side\x18\b \x01(\tB\x13\xba\xb5\x18\x05\n" +
	"\x03buyµ\x18\x06\n" +
	"\x04sideR\x04side\"F\n" +
	"\x12ListOrdersResponse\x120\n" +
	"\x06orders\x18\x01 \x03(\v2\x18.alpaca.trading.v1.OrderR\x06ordersB\xd3\x01\n" +
	"\x15com.alpaca.trading.v1B\x0fListOrdersProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var (
	file_alpaca_trading_v1_list_orders_proto_rawDescOnce sync.Once
	file_alpaca_trading_v1_list_orders_proto_rawDescData []byte
)

func file_alpaca_trading_v1_list_orders_proto_rawDescGZIP() []byte {
	file_alpaca_trading_v1_list_orders_proto_rawDescOnce.Do(func() {
		file_alpaca_trading_v1_list_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_list_orders_proto_rawDesc), len(file_alpaca_trading_v1_list_orders_proto_rawDesc)))
	})
	return file_alpaca_trading_v1_list_orders_proto_rawDescData
}

var file_alpaca_trading_v1_list_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alpaca_trading_v1_list_orders_proto_goTypes = []any{
	(*ListOrdersRequest)(nil),  // 0: alpaca.trading.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil), // 1: alpaca.trading.v1.ListOrdersResponse
	(*Order)(nil),              // 2: alpaca.trading.v1.Order
}
var file_alpaca_trading_v1_list_orders_proto_depIdxs = []int32{
	2, // 0: alpaca.trading.v1.ListOrdersResponse.orders:type_name -> alpaca.trading.v1.Order
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_list_orders_proto_init() }
func file_alpaca_trading_v1_list_orders_proto_init() {
	if File_alpaca_trading_v1_list_orders_proto != nil {
		return
	}
	file_alpaca_trading_v1_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_list_orders_proto_rawDesc), len(file_alpaca_trading_v1_list_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_trading_v1_list_orders_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_list_orders_proto_depIdxs,
		MessageInfos:      file_alpaca_trading_v1_list_orders_proto_msgTypes,
	}.Build()
	File_alpaca_trading_v1_list_orders_proto = out.File
	file_alpaca_trading_v1_list_orders_proto_goTypes = nil
	file_alpaca_trading_v1_list_orders_proto_depIdxs = nil
}
