// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/portfolio_history.proto

package tradingv1

import (
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PortfolioHistory represents the historical performance of a portfolio.
type PortfolioHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamps for each data point (Unix epoch in seconds).
	Timestamp []int64 `protobuf:"varint,1,rep,packed,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Portfolio equity values at each timestamp.
	Equity []float64 `protobuf:"fixed64,2,rep,packed,name=equity,proto3" json:"equity,omitempty"`
	// Profit/loss values at each timestamp.
	ProfitLoss []float64 `protobuf:"fixed64,3,rep,packed,name=profit_loss,json=profitLoss,proto3" json:"profit_loss,omitempty"`
	// Profit/loss percentage at each timestamp.
	ProfitLossPct []float64 `protobuf:"fixed64,4,rep,packed,name=profit_loss_pct,json=profitLossPct,proto3" json:"profit_loss_pct,omitempty"`
	// Base value (starting equity).
	BaseValue float64 `protobuf:"fixed64,5,opt,name=base_value,json=baseValue,proto3" json:"base_value,omitempty"`
	// Time frame (1Min, 5Min, 15Min, 1H, 1D).
	Timeframe     string `protobuf:"bytes,6,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioHistory) Reset() {
	*x = PortfolioHistory{}
	mi := &file_alpaca_trading_v1_portfolio_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioHistory) ProtoMessage() {}

func (x *PortfolioHistory) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_portfolio_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioHistory.ProtoReflect.Descriptor instead.
func (*PortfolioHistory) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_portfolio_history_proto_rawDescGZIP(), []int{0}
}

func (x *PortfolioHistory) GetTimestamp() []int64 {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PortfolioHistory) GetEquity() []float64 {
	if x != nil {
		return x.Equity
	}
	return nil
}

func (x *PortfolioHistory) GetProfitLoss() []float64 {
	if x != nil {
		return x.ProfitLoss
	}
	return nil
}

func (x *PortfolioHistory) GetProfitLossPct() []float64 {
	if x != nil {
		return x.ProfitLossPct
	}
	return nil
}

func (x *PortfolioHistory) GetBaseValue() float64 {
	if x != nil {
		return x.BaseValue
	}
	return 0
}

func (x *PortfolioHistory) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

// GetPortfolioHistoryRequest is the request to get portfolio history.
type GetPortfolioHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Period (1D, 1W, 1M, 3M, 1A, all, intraday).
	Period string `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	// Timeframe for data points (1Min, 5Min, 15Min, 1H, 1D).
	Timeframe string `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	// Intraday reporting mode (market_hours or extended_hours).
	IntradayReporting string `protobuf:"bytes,3,opt,name=intraday_reporting,json=intradayReporting,proto3" json:"intraday_reporting,omitempty"`
	// Start date/time (RFC-3339 or YYYY-MM-DD).
	Start string `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	// End date/time (RFC-3339 or YYYY-MM-DD).
	End string `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	// Whether to use PnL calculation instead of market value.
	PnlReset bool `protobuf:"varint,6,opt,name=pnl_reset,json=pnlReset,proto3" json:"pnl_reset,omitempty"`
	// Whether to include extended hours data.
	ExtendedHours bool `protobuf:"varint,7,opt,name=extended_hours,json=extendedHours,proto3" json:"extended_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioHistoryRequest) Reset() {
	*x = GetPortfolioHistoryRequest{}
	mi := &file_alpaca_trading_v1_portfolio_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioHistoryRequest) ProtoMessage() {}

func (x *GetPortfolioHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_portfolio_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioHistoryRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_portfolio_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetPortfolioHistoryRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetPortfolioHistoryRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *GetPortfolioHistoryRequest) GetIntradayReporting() string {
	if x != nil {
		return x.IntradayReporting
	}
	return ""
}

func (x *GetPortfolioHistoryRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *GetPortfolioHistoryRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *GetPortfolioHistoryRequest) GetPnlReset() bool {
	if x != nil {
		return x.PnlReset
	}
	return false
}

func (x *GetPortfolioHistoryRequest) GetExtendedHours() bool {
	if x != nil {
		return x.ExtendedHours
	}
	return false
}

var File_alpaca_trading_v1_portfolio_history_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_portfolio_history_proto_rawDesc = "" +
	"\n" +
	")alpaca/trading/v1/portfolio_history.proto\x12\x11alpaca.trading.v1\x1a\x1csebuf/http/annotations.proto\"\xe8\x01\n" +
	"\x10PortfolioHistory\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x03(\x03R\ttimestamp\x12\x16\n" +
	"\x06equity\x18\x02 \x03(\x01R\x06equity\x12\x1f\n" +
	"\vprofit_loss\x18\x03 \x03(\x01R\n" +
	"profitLoss\x12&\n" +
	"\x0fprofit_loss_pct\x18\x04 \x03(\x01R\rprofitLossPct\x12-\n" +
	"\n" +
	"base_value\x18\x05 \x01(\x01B\x0e\xba\xb5\x18\n" +
	"\n" +
	"\b50000.00R\tbaseValue\x12&\n" +
	"\ttimeframe\x18\x06 \x01(\tB\b\xba\xb5\x18\x04\n" +
	"\x021DR\ttimeframe\"\xbd\x03\n" +
	"\x1aGetPortfolioHistoryRequest\x12,\n" +
	"\x06period\x18\x01 \x01(\tB\x14\xba\xb5\x18\x04\n" +
	"\x021Mµ\x18\b\n" +
	"\x06periodR\x06period\x125\n" +
	"\ttimeframe\x18\x02 \x01(\tB\x17\xba\xb5\x18\x04\n" +
	"\x021Dµ\x18\v\n" +
	"\ttimeframeR\ttimeframe\x12Y\n" +
	"\x12intraday_reporting\x18\x03 \x01(\tB*\xba\xb5\x18\x0e\n" +
	"\fmarket_hoursµ\x18\x14\n" +
	"\x12intraday_reportingR\x11intradayReporting\x121\n" +
	"\x05start\x18\x04 \x01(\tB\x1b\xba\xb5\x18\f\n" +
	"\n" +
	"2024-01-01µ\x18\a\n" +
	"\x05startR\x05start\x12+\n" +
	"\x03end\x18\x05 \x01(\tB\x19\xba\xb5\x18\f\n" +
	"\n" +
	"2024-01-31µ\x18\x05\n" +
	"\x03endR\x03end\x127\n" +
	"\tpnl_reset\x18\x06 \x01(\bB\x1a\xba\xb5\x18\a\n" +
	"\x05falseµ\x18\v\n" +
	"\tpnl_resetR\bpnlReset\x12F\n" +
	"\x0eextended_hours\x18\a \x01(\bB\x1f\xba\xb5\x18\a\n" +
	"\x05falseµ\x18\x10\n" +
	"\x0eextended_hoursR\rextendedHoursB\xd9\x01\n" +
	"\x15com.alpaca.trading.v1B\x15PortfolioHistoryProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var (
	file_alpaca_trading_v1_portfolio_history_proto_rawDescOnce sync.Once
	file_alpaca_trading_v1_portfolio_history_proto_rawDescData []byte
)

func file_alpaca_trading_v1_portfolio_history_proto_rawDescGZIP() []byte {
	file_alpaca_trading_v1_portfolio_history_proto_rawDescOnce.Do(func() {
		file_alpaca_trading_v1_portfolio_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_portfolio_history_proto_rawDesc), len(file_alpaca_trading_v1_portfolio_history_proto_rawDesc)))
	})
	return file_alpaca_trading_v1_portfolio_history_proto_rawDescData
}

var file_alpaca_trading_v1_portfolio_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_alpaca_trading_v1_portfolio_history_proto_goTypes = []any{
	(*PortfolioHistory)(nil),           // 0: alpaca.trading.v1.PortfolioHistory
	(*GetPortfolioHistoryRequest)(nil), // 1: alpaca.trading.v1.GetPortfolioHistoryRequest
}
var file_alpaca_trading_v1_portfolio_history_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_portfolio_history_proto_init() }
func file_alpaca_trading_v1_portfolio_history_proto_init() {
	if File_alpaca_trading_v1_portfolio_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_portfolio_history_proto_rawDesc), len(file_alpaca_trading_v1_portfolio_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_trading_v1_portfolio_history_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_portfolio_history_proto_depIdxs,
		MessageInfos:      file_alpaca_trading_v1_portfolio_history_proto_msgTypes,
	}.Build()
	File_alpaca_trading_v1_portfolio_history_proto = out.File
	file_alpaca_trading_v1_portfolio_history_proto_goTypes = nil
	file_alpaca_trading_v1_portfolio_history_proto_depIdxs = nil
}
