// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/replace_order.proto

package tradingv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReplaceOrderRequest is the request to replace (modify) an existing order.
type ReplaceOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The order ID to replace (bound from path variable).
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// New quantity (optional, keeps original if not specified).
	Qty string `protobuf:"bytes,2,opt,name=qty,proto3" json:"qty,omitempty"`
	// New time in force (optional).
	TimeInForce TimeInForce `protobuf:"varint,3,opt,name=time_in_force,json=timeInForce,proto3,enum=alpaca.trading.v1.TimeInForce" json:"time_in_force,omitempty"`
	// New limit price (optional, for limit orders).
	LimitPrice string `protobuf:"bytes,4,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"`
	// New stop price (optional, for stop orders).
	StopPrice string `protobuf:"bytes,5,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	// New trail (optional, for trailing stop orders).
	Trail string `protobuf:"bytes,6,opt,name=trail,proto3" json:"trail,omitempty"`
	// New client order ID (optional).
	ClientOrderId string `protobuf:"bytes,7,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceOrderRequest) Reset() {
	*x = ReplaceOrderRequest{}
	mi := &file_alpaca_trading_v1_replace_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceOrderRequest) ProtoMessage() {}

func (x *ReplaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alpaca_trading_v1_replace_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceOrderRequest.ProtoReflect.Descriptor instead.
func (*ReplaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_alpaca_trading_v1_replace_order_proto_rawDescGZIP(), []int{0}
}

func (x *ReplaceOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReplaceOrderRequest) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *ReplaceOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *ReplaceOrderRequest) GetLimitPrice() string {
	if x != nil {
		return x.LimitPrice
	}
	return ""
}

func (x *ReplaceOrderRequest) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *ReplaceOrderRequest) GetTrail() string {
	if x != nil {
		return x.Trail
	}
	return ""
}

func (x *ReplaceOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

var File_alpaca_trading_v1_replace_order_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_replace_order_proto_rawDesc = "" +
	"\n" +
	"%alpaca/trading/v1/replace_order.proto\x12\x11alpaca.trading.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1csebuf/http/annotations.proto\x1a\x1dalpaca/trading/v1/order.proto\"\x9a\x03\n" +
	"\x13ReplaceOrderRequest\x12P\n" +
	"\border_id\x18\x01 \x01(\tB5\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01\xba\xb5\x18&\n" +
	"$61e69015-8549-4bfd-b9c3-01e75843f47dR\aorderId\x12\x1a\n" +
	"\x03qty\x18\x02 \x01(\tB\b\xba\xb5\x18\x04\n" +
	"\x0215R\x03qty\x12K\n" +
	"\rtime_in_force\x18\x03 \x01(\x0e2\x1e.alpaca.trading.v1.TimeInForceB\a\xba\xb5\x18\x03\n" +
	"\x011R\vtimeInForce\x12-\n" +
	"\vlimit_price\x18\x04 \x01(\tB\f\xba\xb5\x18\b\n" +
	"\x06152.00R\n" +
	"limitPrice\x12+\n" +
	"\n" +
	"stop_price\x18\x05 \x01(\tB\f\xba\xb5\x18\b\n" +
	"\x06148.00R\tstopPrice\x12 \n" +
	"\x05trail\x18\x06 \x01(\tB\n" +
	"\xba\xb5\x18\x06\n" +
	"\x045.00R\x05trail\x12J\n" +
	"\x0fclient_order_id\x18\a \x01(\tB\"\xbaH\x04r\x02\x180\xba\xb5\x18\x17\n" +
	"\x15my_replaced_order_123R\rclientOrderIdB\xd5\x01\n" +
	"\x15com.alpaca.trading.v1B\x11ReplaceOrderProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var (
	file_alpaca_trading_v1_replace_order_proto_rawDescOnce sync.Once
	file_alpaca_trading_v1_replace_order_proto_rawDescData []byte
)

func file_alpaca_trading_v1_replace_order_proto_rawDescGZIP() []byte {
	file_alpaca_trading_v1_replace_order_proto_rawDescOnce.Do(func() {
		file_alpaca_trading_v1_replace_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_replace_order_proto_rawDesc), len(file_alpaca_trading_v1_replace_order_proto_rawDesc)))
	})
	return file_alpaca_trading_v1_replace_order_proto_rawDescData
}

var file_alpaca_trading_v1_replace_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alpaca_trading_v1_replace_order_proto_goTypes = []any{
	(*ReplaceOrderRequest)(nil), // 0: alpaca.trading.v1.ReplaceOrderRequest
	(TimeInForce)(0),            // 1: alpaca.trading.v1.TimeInForce
}
var file_alpaca_trading_v1_replace_order_proto_depIdxs = []int32{
	1, // 0: alpaca.trading.v1.ReplaceOrderRequest.time_in_force:type_name -> alpaca.trading.v1.TimeInForce
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_replace_order_proto_init() }
func file_alpaca_trading_v1_replace_order_proto_init() {
	if File_alpaca_trading_v1_replace_order_proto != nil {
		return
	}
	file_alpaca_trading_v1_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_replace_order_proto_rawDesc), len(file_alpaca_trading_v1_replace_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alpaca_trading_v1_replace_order_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_replace_order_proto_depIdxs,
		MessageInfos:      file_alpaca_trading_v1_replace_order_proto_msgTypes,
	}.Build()
	File_alpaca_trading_v1_replace_order_proto = out.File
	file_alpaca_trading_v1_replace_order_proto_goTypes = nil
	file_alpaca_trading_v1_replace_order_proto_depIdxs = nil
}
