// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/service.proto

package tradingv1

import (
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_alpaca_trading_v1_service_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1falpaca/trading/v1/service.proto\x12\x11alpaca.trading.v1\x1a\x1csebuf/http/annotations.proto\x1a\x18sebuf/http/headers.proto\x1a\x1falpaca/trading/v1/account.proto\x1a#alpaca/trading/v1/get_account.proto\x1a\x1dalpaca/trading/v1/order.proto\x1a$alpaca/trading/v1/create_order.proto\x1a!alpaca/trading/v1/get_order.proto\x1a#alpaca/trading/v1/list_orders.proto\x1a$alpaca/trading/v1/cancel_order.proto\x1a)alpaca/trading/v1/cancel_all_orders.proto\x1a alpaca/trading/v1/position.proto\x1a&alpaca/trading/v1/list_positions.proto\x1a$alpaca/trading/v1/get_position.proto\x1a&alpaca/trading/v1/close_position.proto\x1a+alpaca/trading/v1/close_all_positions.proto2\xbf\v\n" +
	"\x0eTradingService\x12e\n" +
	"\n" +
	"GetAccount\x12$.alpaca.trading.v1.GetAccountRequest\x1a\x1a.alpaca.trading.v1.Account\"\x15\x9a\xb5\x18\x11\n" +
	"\r/{account_id}\x10\x01\x12l\n" +
	"\vCreateOrder\x12%.alpaca.trading.v1.CreateOrderRequest\x1a\x18.alpaca.trading.v1.Order\"\x1c\x9a\xb5\x18\x18\n" +
	"\x14/{account_id}/orders\x10\x02\x12w\n" +
	"\n" +
	"ListOrders\x12$.alpaca.trading.v1.ListOrdersRequest\x1a%.alpaca.trading.v1.ListOrdersResponse\"\x1c\x9a\xb5\x18\x18\n" +
	"\x14/{account_id}/orders\x10\x01\x12q\n" +
	"\bGetOrder\x12\".alpaca.trading.v1.GetOrderRequest\x1a\x18.alpaca.trading.v1.Order\"'\x9a\xb5\x18#\n" +
	"\x1f/{account_id}/orders/{order_id}\x10\x01\x12\x85\x01\n" +
	"\vCancelOrder\x12%.alpaca.trading.v1.CancelOrderRequest\x1a&.alpaca.trading.v1.CancelOrderResponse\"'\x9a\xb5\x18#\n" +
	"\x1f/{account_id}/orders/{order_id}\x10\x04\x12\x86\x01\n" +
	"\x0fCancelAllOrders\x12).alpaca.trading.v1.CancelAllOrdersRequest\x1a*.alpaca.trading.v1.CancelAllOrdersResponse\"\x1c\x9a\xb5\x18\x18\n" +
	"\x14/{account_id}/orders\x10\x04\x12\x83\x01\n" +
	"\rListPositions\x12'.alpaca.trading.v1.ListPositionsRequest\x1a(.alpaca.trading.v1.ListPositionsResponse\"\x1f\x9a\xb5\x18\x1b\n" +
	"\x17/{account_id}/positions\x10\x01\x12{\n" +
	"\vGetPosition\x12%.alpaca.trading.v1.GetPositionRequest\x1a\x1b.alpaca.trading.v1.Position\"(\x9a\xb5\x18$\n" +
	" /{account_id}/positions/{symbol}\x10\x01\x12|\n" +
	"\rClosePosition\x12'.alpaca.trading.v1.ClosePositionRequest\x1a\x18.alpaca.trading.v1.Order\"(\x9a\xb5\x18$\n" +
	" /{account_id}/positions/{symbol}\x10\x04\x12\x8f\x01\n" +
	"\x11CloseAllPositions\x12+.alpaca.trading.v1.CloseAllPositionsRequest\x1a,.alpaca.trading.v1.CloseAllPositionsResponse\"\x1f\x9a\xb5\x18\x1b\n" +
	"\x17/{account_id}/positions\x10\x04\x1a\xc7\x01\xa2\xb5\x18\x16\n" +
	"\x14/v1/trading/accounts\xaa\xb5\x18\xa8\x01\n" +
	"D\n" +
	"\x0fAPCA-API-KEY-ID\x12\x11Alpaca API key ID\x1a\x06string \x012\x14PKXXXXXXXXXXXXXXXXXX\n" +
	"`\n" +
	"\x13APCA-API-SECRET-KEY\x12\x15Alpaca API secret key\x1a\x06string \x012(XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB\xd0\x01\n" +
	"\x15com.alpaca.trading.v1B\fServiceProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var file_alpaca_trading_v1_service_proto_goTypes = []any{
	(*GetAccountRequest)(nil),         // 0: alpaca.trading.v1.GetAccountRequest
	(*CreateOrderRequest)(nil),        // 1: alpaca.trading.v1.CreateOrderRequest
	(*ListOrdersRequest)(nil),         // 2: alpaca.trading.v1.ListOrdersRequest
	(*GetOrderRequest)(nil),           // 3: alpaca.trading.v1.GetOrderRequest
	(*CancelOrderRequest)(nil),        // 4: alpaca.trading.v1.CancelOrderRequest
	(*CancelAllOrdersRequest)(nil),    // 5: alpaca.trading.v1.CancelAllOrdersRequest
	(*ListPositionsRequest)(nil),      // 6: alpaca.trading.v1.ListPositionsRequest
	(*GetPositionRequest)(nil),        // 7: alpaca.trading.v1.GetPositionRequest
	(*ClosePositionRequest)(nil),      // 8: alpaca.trading.v1.ClosePositionRequest
	(*CloseAllPositionsRequest)(nil),  // 9: alpaca.trading.v1.CloseAllPositionsRequest
	(*Account)(nil),                   // 10: alpaca.trading.v1.Account
	(*Order)(nil),                     // 11: alpaca.trading.v1.Order
	(*ListOrdersResponse)(nil),        // 12: alpaca.trading.v1.ListOrdersResponse
	(*CancelOrderResponse)(nil),       // 13: alpaca.trading.v1.CancelOrderResponse
	(*CancelAllOrdersResponse)(nil),   // 14: alpaca.trading.v1.CancelAllOrdersResponse
	(*ListPositionsResponse)(nil),     // 15: alpaca.trading.v1.ListPositionsResponse
	(*Position)(nil),                  // 16: alpaca.trading.v1.Position
	(*CloseAllPositionsResponse)(nil), // 17: alpaca.trading.v1.CloseAllPositionsResponse
}
var file_alpaca_trading_v1_service_proto_depIdxs = []int32{
	0,  // 0: alpaca.trading.v1.TradingService.GetAccount:input_type -> alpaca.trading.v1.GetAccountRequest
	1,  // 1: alpaca.trading.v1.TradingService.CreateOrder:input_type -> alpaca.trading.v1.CreateOrderRequest
	2,  // 2: alpaca.trading.v1.TradingService.ListOrders:input_type -> alpaca.trading.v1.ListOrdersRequest
	3,  // 3: alpaca.trading.v1.TradingService.GetOrder:input_type -> alpaca.trading.v1.GetOrderRequest
	4,  // 4: alpaca.trading.v1.TradingService.CancelOrder:input_type -> alpaca.trading.v1.CancelOrderRequest
	5,  // 5: alpaca.trading.v1.TradingService.CancelAllOrders:input_type -> alpaca.trading.v1.CancelAllOrdersRequest
	6,  // 6: alpaca.trading.v1.TradingService.ListPositions:input_type -> alpaca.trading.v1.ListPositionsRequest
	7,  // 7: alpaca.trading.v1.TradingService.GetPosition:input_type -> alpaca.trading.v1.GetPositionRequest
	8,  // 8: alpaca.trading.v1.TradingService.ClosePosition:input_type -> alpaca.trading.v1.ClosePositionRequest
	9,  // 9: alpaca.trading.v1.TradingService.CloseAllPositions:input_type -> alpaca.trading.v1.CloseAllPositionsRequest
	10, // 10: alpaca.trading.v1.TradingService.GetAccount:output_type -> alpaca.trading.v1.Account
	11, // 11: alpaca.trading.v1.TradingService.CreateOrder:output_type -> alpaca.trading.v1.Order
	12, // 12: alpaca.trading.v1.TradingService.ListOrders:output_type -> alpaca.trading.v1.ListOrdersResponse
	11, // 13: alpaca.trading.v1.TradingService.GetOrder:output_type -> alpaca.trading.v1.Order
	13, // 14: alpaca.trading.v1.TradingService.CancelOrder:output_type -> alpaca.trading.v1.CancelOrderResponse
	14, // 15: alpaca.trading.v1.TradingService.CancelAllOrders:output_type -> alpaca.trading.v1.CancelAllOrdersResponse
	15, // 16: alpaca.trading.v1.TradingService.ListPositions:output_type -> alpaca.trading.v1.ListPositionsResponse
	16, // 17: alpaca.trading.v1.TradingService.GetPosition:output_type -> alpaca.trading.v1.Position
	11, // 18: alpaca.trading.v1.TradingService.ClosePosition:output_type -> alpaca.trading.v1.Order
	17, // 19: alpaca.trading.v1.TradingService.CloseAllPositions:output_type -> alpaca.trading.v1.CloseAllPositionsResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_service_proto_init() }
func file_alpaca_trading_v1_service_proto_init() {
	if File_alpaca_trading_v1_service_proto != nil {
		return
	}
	file_alpaca_trading_v1_account_proto_init()
	file_alpaca_trading_v1_get_account_proto_init()
	file_alpaca_trading_v1_order_proto_init()
	file_alpaca_trading_v1_create_order_proto_init()
	file_alpaca_trading_v1_get_order_proto_init()
	file_alpaca_trading_v1_list_orders_proto_init()
	file_alpaca_trading_v1_cancel_order_proto_init()
	file_alpaca_trading_v1_cancel_all_orders_proto_init()
	file_alpaca_trading_v1_position_proto_init()
	file_alpaca_trading_v1_list_positions_proto_init()
	file_alpaca_trading_v1_get_position_proto_init()
	file_alpaca_trading_v1_close_position_proto_init()
	file_alpaca_trading_v1_close_all_positions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_service_proto_rawDesc), len(file_alpaca_trading_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alpaca_trading_v1_service_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_service_proto_depIdxs,
	}.Build()
	File_alpaca_trading_v1_service_proto = out.File
	file_alpaca_trading_v1_service_proto_goTypes = nil
	file_alpaca_trading_v1_service_proto_depIdxs = nil
}
