// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: alpaca/trading/v1/service.proto

package tradingv1

import (
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_alpaca_trading_v1_service_proto protoreflect.FileDescriptor

const file_alpaca_trading_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1falpaca/trading/v1/service.proto\x12\x11alpaca.trading.v1\x1a\x1csebuf/http/annotations.proto\x1a\x18sebuf/http/headers.proto\x1a\x1falpaca/trading/v1/account.proto\x1a#alpaca/trading/v1/get_account.proto\x1a\x1dalpaca/trading/v1/order.proto\x1a$alpaca/trading/v1/create_order.proto\x1a!alpaca/trading/v1/get_order.proto\x1a#alpaca/trading/v1/list_orders.proto\x1a$alpaca/trading/v1/cancel_order.proto\x1a)alpaca/trading/v1/cancel_all_orders.proto\x1a%alpaca/trading/v1/replace_order.proto\x1a.alpaca/trading/v1/get_order_by_client_id.proto\x1a alpaca/trading/v1/position.proto\x1a&alpaca/trading/v1/list_positions.proto\x1a$alpaca/trading/v1/get_position.proto\x1a&alpaca/trading/v1/close_position.proto\x1a+alpaca/trading/v1/close_all_positions.proto\x1a'alpaca/trading/v1/exercise_option.proto\x1a\x1dalpaca/trading/v1/asset.proto\x1a#alpaca/trading/v1/list_assets.proto\x1a!alpaca/trading/v1/get_asset.proto\x1a\x1dalpaca/trading/v1/clock.proto\x1a alpaca/trading/v1/calendar.proto\x1a!alpaca/trading/v1/watchlist.proto\x1a'alpaca/trading/v1/list_watchlists.proto\x1a(alpaca/trading/v1/create_watchlist.proto\x1a%alpaca/trading/v1/get_watchlist.proto\x1a(alpaca/trading/v1/update_watchlist.proto\x1a(alpaca/trading/v1/delete_watchlist.proto\x1a+alpaca/trading/v1/add_watchlist_asset.proto\x1a.alpaca/trading/v1/remove_watchlist_asset.proto\x1a.alpaca/trading/v1/account_configurations.proto\x1a)alpaca/trading/v1/portfolio_history.proto\x1a(alpaca/trading/v1/account_activity.proto2\x9a\x1e\n" +
	"\x0eTradingService\x12`\n" +
	"\n" +
	"GetAccount\x12$.alpaca.trading.v1.GetAccountRequest\x1a\x1a.alpaca.trading.v1.Account\"\x10\x9a\xb5\x18\f\n" +
	"\b/account\x10\x01\x12\x99\x01\n" +
	"\x18GetAccountConfigurations\x122.alpaca.trading.v1.GetAccountConfigurationsRequest\x1a(.alpaca.trading.v1.AccountConfigurations\"\x1f\x9a\xb5\x18\x1b\n" +
	"\x17/account/configurations\x10\x01\x12\x9f\x01\n" +
	"\x1bUpdateAccountConfigurations\x125.alpaca.trading.v1.UpdateAccountConfigurationsRequest\x1a(.alpaca.trading.v1.AccountConfigurations\"\x1f\x9a\xb5\x18\x1b\n" +
	"\x17/account/configurations\x10\x05\x12\x8d\x01\n" +
	"\x13GetPortfolioHistory\x12-.alpaca.trading.v1.GetPortfolioHistoryRequest\x1a#.alpaca.trading.v1.PortfolioHistory\"\"\x9a\xb5\x18\x1e\n" +
	"\x1a/account/portfolio/history\x10\x01\x12\x94\x01\n" +
	"\x14GetAccountActivities\x12..alpaca.trading.v1.GetAccountActivitiesRequest\x1a/.alpaca.trading.v1.GetAccountActivitiesResponse\"\x1b\x9a\xb5\x18\x17\n" +
	"\x13/account/activities\x10\x01\x12\xb0\x01\n" +
	"\x1aGetAccountActivitiesByType\x124.alpaca.trading.v1.GetAccountActivitiesByTypeRequest\x1a/.alpaca.trading.v1.GetAccountActivitiesResponse\"+\x9a\xb5\x18'\n" +
	"#/account/activities/{activity_type}\x10\x01\x12_\n" +
	"\vCreateOrder\x12%.alpaca.trading.v1.CreateOrderRequest\x1a\x18.alpaca.trading.v1.Order\"\x0f\x9a\xb5\x18\v\n" +
	"\a/orders\x10\x02\x12j\n" +
	"\n" +
	"ListOrders\x12$.alpaca.trading.v1.ListOrdersRequest\x1a%.alpaca.trading.v1.ListOrdersResponse\"\x0f\x9a\xb5\x18\v\n" +
	"\a/orders\x10\x01\x12d\n" +
	"\bGetOrder\x12\".alpaca.trading.v1.GetOrderRequest\x1a\x18.alpaca.trading.v1.Order\"\x1a\x9a\xb5\x18\x16\n" +
	"\x12/orders/{order_id}\x10\x01\x12\x80\x01\n" +
	"\x12GetOrderByClientId\x12,.alpaca.trading.v1.GetOrderByClientIdRequest\x1a\x18.alpaca.trading.v1.Order\"\"\x9a\xb5\x18\x1e\n" +
	"\x1a/orders:by_client_order_id\x10\x01\x12l\n" +
	"\fReplaceOrder\x12&.alpaca.trading.v1.ReplaceOrderRequest\x1a\x18.alpaca.trading.v1.Order\"\x1a\x9a\xb5\x18\x16\n" +
	"\x12/orders/{order_id}\x10\x05\x12x\n" +
	"\vCancelOrder\x12%.alpaca.trading.v1.CancelOrderRequest\x1a&.alpaca.trading.v1.CancelOrderResponse\"\x1a\x9a\xb5\x18\x16\n" +
	"\x12/orders/{order_id}\x10\x04\x12y\n" +
	"\x0fCancelAllOrders\x12).alpaca.trading.v1.CancelAllOrdersRequest\x1a*.alpaca.trading.v1.CancelAllOrdersResponse\"\x0f\x9a\xb5\x18\v\n" +
	"\a/orders\x10\x04\x12v\n" +
	"\rListPositions\x12'.alpaca.trading.v1.ListPositionsRequest\x1a(.alpaca.trading.v1.ListPositionsResponse\"\x12\x9a\xb5\x18\x0e\n" +
	"\n" +
	"/positions\x10\x01\x12n\n" +
	"\vGetPosition\x12%.alpaca.trading.v1.GetPositionRequest\x1a\x1b.alpaca.trading.v1.Position\"\x1b\x9a\xb5\x18\x17\n" +
	"\x13/positions/{symbol}\x10\x01\x12o\n" +
	"\rClosePosition\x12'.alpaca.trading.v1.ClosePositionRequest\x1a\x18.alpaca.trading.v1.Order\"\x1b\x9a\xb5\x18\x17\n" +
	"\x13/positions/{symbol}\x10\x04\x12\x82\x01\n" +
	"\x11CloseAllPositions\x12+.alpaca.trading.v1.CloseAllPositionsRequest\x1a,.alpaca.trading.v1.CloseAllPositionsResponse\"\x12\x9a\xb5\x18\x0e\n" +
	"\n" +
	"/positions\x10\x04\x12\x9a\x01\n" +
	"\x0eExerciseOption\x12(.alpaca.trading.v1.ExerciseOptionRequest\x1a).alpaca.trading.v1.ExerciseOptionResponse\"3\x9a\xb5\x18/\n" +
	"+/positions/{symbol_or_contract_id}/exercise\x10\x02\x12j\n" +
	"\n" +
	"ListAssets\x12$.alpaca.trading.v1.ListAssetsRequest\x1a%.alpaca.trading.v1.ListAssetsResponse\"\x0f\x9a\xb5\x18\v\n" +
	"\a/assets\x10\x01\x12h\n" +
	"\bGetAsset\x12\".alpaca.trading.v1.GetAssetRequest\x1a\x18.alpaca.trading.v1.Asset\"\x1e\x9a\xb5\x18\x1a\n" +
	"\x16/assets/{symbol_or_id}\x10\x01\x12X\n" +
	"\bGetClock\x12\".alpaca.trading.v1.GetClockRequest\x1a\x18.alpaca.trading.v1.Clock\"\x0e\x9a\xb5\x18\n" +
	"\n" +
	"\x06/clock\x10\x01\x12o\n" +
	"\vGetCalendar\x12%.alpaca.trading.v1.GetCalendarRequest\x1a&.alpaca.trading.v1.GetCalendarResponse\"\x11\x9a\xb5\x18\r\n" +
	"\t/calendar\x10\x01\x12z\n" +
	"\x0eListWatchlists\x12(.alpaca.trading.v1.ListWatchlistsRequest\x1a).alpaca.trading.v1.ListWatchlistsResponse\"\x13\x9a\xb5\x18\x0f\n" +
	"\v/watchlists\x10\x01\x12o\n" +
	"\x0fCreateWatchlist\x12).alpaca.trading.v1.CreateWatchlistRequest\x1a\x1c.alpaca.trading.v1.Watchlist\"\x13\x9a\xb5\x18\x0f\n" +
	"\v/watchlists\x10\x02\x12x\n" +
	"\fGetWatchlist\x12&.alpaca.trading.v1.GetWatchlistRequest\x1a\x1c.alpaca.trading.v1.Watchlist\"\"\x9a\xb5\x18\x1e\n" +
	"\x1a/watchlists/{watchlist_id}\x10\x01\x12~\n" +
	"\x0fUpdateWatchlist\x12).alpaca.trading.v1.UpdateWatchlistRequest\x1a\x1c.alpaca.trading.v1.Watchlist\"\"\x9a\xb5\x18\x1e\n" +
	"\x1a/watchlists/{watchlist_id}\x10\x03\x12\x8c\x01\n" +
	"\x0fDeleteWatchlist\x12).alpaca.trading.v1.DeleteWatchlistRequest\x1a*.alpaca.trading.v1.DeleteWatchlistResponse\"\"\x9a\xb5\x18\x1e\n" +
	"\x1a/watchlists/{watchlist_id}\x10\x04\x12\x82\x01\n" +
	"\x11AddWatchlistAsset\x12+.alpaca.trading.v1.AddWatchlistAssetRequest\x1a\x1c.alpaca.trading.v1.Watchlist\"\"\x9a\xb5\x18\x1e\n" +
	"\x1a/watchlists/{watchlist_id}\x10\x02\x12\xa4\x01\n" +
	"\x14RemoveWatchlistAsset\x12..alpaca.trading.v1.RemoveWatchlistAssetRequest\x1a/.alpaca.trading.v1.RemoveWatchlistAssetResponse\"+\x9a\xb5\x18'\n" +
	"#/watchlists/{watchlist_id}/{symbol}\x10\x04\x1a\xb6\x01\xa2\xb5\x18\x05\n" +
	"\x03/v2\xaa\xb5\x18\xa8\x01\n" +
	"D\n" +
	"\x0fAPCA-API-KEY-ID\x12\x11Alpaca API key ID\x1a\x06string \x012\x14PKXXXXXXXXXXXXXXXXXX\n" +
	"`\n" +
	"\x13APCA-API-SECRET-KEY\x12\x15Alpaca API secret key\x1a\x06string \x012(XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB\xd0\x01\n" +
	"\x15com.alpaca.trading.v1B\fServiceProtoP\x01ZCgithub.com/sebastienmelki/alpaca-go/api/alpaca/trading/v1;tradingv1\xa2\x02\x03ATX\xaa\x02\x11Alpaca.Trading.V1\xca\x02\x11Alpaca\\Trading\\V1\xe2\x02\x1dAlpaca\\Trading\\V1\\GPBMetadata\xea\x02\x13Alpaca::Trading::V1b\x06proto3"

var file_alpaca_trading_v1_service_proto_goTypes = []any{
	(*GetAccountRequest)(nil),                  // 0: alpaca.trading.v1.GetAccountRequest
	(*GetAccountConfigurationsRequest)(nil),    // 1: alpaca.trading.v1.GetAccountConfigurationsRequest
	(*UpdateAccountConfigurationsRequest)(nil), // 2: alpaca.trading.v1.UpdateAccountConfigurationsRequest
	(*GetPortfolioHistoryRequest)(nil),         // 3: alpaca.trading.v1.GetPortfolioHistoryRequest
	(*GetAccountActivitiesRequest)(nil),        // 4: alpaca.trading.v1.GetAccountActivitiesRequest
	(*GetAccountActivitiesByTypeRequest)(nil),  // 5: alpaca.trading.v1.GetAccountActivitiesByTypeRequest
	(*CreateOrderRequest)(nil),                 // 6: alpaca.trading.v1.CreateOrderRequest
	(*ListOrdersRequest)(nil),                  // 7: alpaca.trading.v1.ListOrdersRequest
	(*GetOrderRequest)(nil),                    // 8: alpaca.trading.v1.GetOrderRequest
	(*GetOrderByClientIdRequest)(nil),          // 9: alpaca.trading.v1.GetOrderByClientIdRequest
	(*ReplaceOrderRequest)(nil),                // 10: alpaca.trading.v1.ReplaceOrderRequest
	(*CancelOrderRequest)(nil),                 // 11: alpaca.trading.v1.CancelOrderRequest
	(*CancelAllOrdersRequest)(nil),             // 12: alpaca.trading.v1.CancelAllOrdersRequest
	(*ListPositionsRequest)(nil),               // 13: alpaca.trading.v1.ListPositionsRequest
	(*GetPositionRequest)(nil),                 // 14: alpaca.trading.v1.GetPositionRequest
	(*ClosePositionRequest)(nil),               // 15: alpaca.trading.v1.ClosePositionRequest
	(*CloseAllPositionsRequest)(nil),           // 16: alpaca.trading.v1.CloseAllPositionsRequest
	(*ExerciseOptionRequest)(nil),              // 17: alpaca.trading.v1.ExerciseOptionRequest
	(*ListAssetsRequest)(nil),                  // 18: alpaca.trading.v1.ListAssetsRequest
	(*GetAssetRequest)(nil),                    // 19: alpaca.trading.v1.GetAssetRequest
	(*GetClockRequest)(nil),                    // 20: alpaca.trading.v1.GetClockRequest
	(*GetCalendarRequest)(nil),                 // 21: alpaca.trading.v1.GetCalendarRequest
	(*ListWatchlistsRequest)(nil),              // 22: alpaca.trading.v1.ListWatchlistsRequest
	(*CreateWatchlistRequest)(nil),             // 23: alpaca.trading.v1.CreateWatchlistRequest
	(*GetWatchlistRequest)(nil),                // 24: alpaca.trading.v1.GetWatchlistRequest
	(*UpdateWatchlistRequest)(nil),             // 25: alpaca.trading.v1.UpdateWatchlistRequest
	(*DeleteWatchlistRequest)(nil),             // 26: alpaca.trading.v1.DeleteWatchlistRequest
	(*AddWatchlistAssetRequest)(nil),           // 27: alpaca.trading.v1.AddWatchlistAssetRequest
	(*RemoveWatchlistAssetRequest)(nil),        // 28: alpaca.trading.v1.RemoveWatchlistAssetRequest
	(*Account)(nil),                            // 29: alpaca.trading.v1.Account
	(*AccountConfigurations)(nil),              // 30: alpaca.trading.v1.AccountConfigurations
	(*PortfolioHistory)(nil),                   // 31: alpaca.trading.v1.PortfolioHistory
	(*GetAccountActivitiesResponse)(nil),       // 32: alpaca.trading.v1.GetAccountActivitiesResponse
	(*Order)(nil),                              // 33: alpaca.trading.v1.Order
	(*ListOrdersResponse)(nil),                 // 34: alpaca.trading.v1.ListOrdersResponse
	(*CancelOrderResponse)(nil),                // 35: alpaca.trading.v1.CancelOrderResponse
	(*CancelAllOrdersResponse)(nil),            // 36: alpaca.trading.v1.CancelAllOrdersResponse
	(*ListPositionsResponse)(nil),              // 37: alpaca.trading.v1.ListPositionsResponse
	(*Position)(nil),                           // 38: alpaca.trading.v1.Position
	(*CloseAllPositionsResponse)(nil),          // 39: alpaca.trading.v1.CloseAllPositionsResponse
	(*ExerciseOptionResponse)(nil),             // 40: alpaca.trading.v1.ExerciseOptionResponse
	(*ListAssetsResponse)(nil),                 // 41: alpaca.trading.v1.ListAssetsResponse
	(*Asset)(nil),                              // 42: alpaca.trading.v1.Asset
	(*Clock)(nil),                              // 43: alpaca.trading.v1.Clock
	(*GetCalendarResponse)(nil),                // 44: alpaca.trading.v1.GetCalendarResponse
	(*ListWatchlistsResponse)(nil),             // 45: alpaca.trading.v1.ListWatchlistsResponse
	(*Watchlist)(nil),                          // 46: alpaca.trading.v1.Watchlist
	(*DeleteWatchlistResponse)(nil),            // 47: alpaca.trading.v1.DeleteWatchlistResponse
	(*RemoveWatchlistAssetResponse)(nil),       // 48: alpaca.trading.v1.RemoveWatchlistAssetResponse
}
var file_alpaca_trading_v1_service_proto_depIdxs = []int32{
	0,  // 0: alpaca.trading.v1.TradingService.GetAccount:input_type -> alpaca.trading.v1.GetAccountRequest
	1,  // 1: alpaca.trading.v1.TradingService.GetAccountConfigurations:input_type -> alpaca.trading.v1.GetAccountConfigurationsRequest
	2,  // 2: alpaca.trading.v1.TradingService.UpdateAccountConfigurations:input_type -> alpaca.trading.v1.UpdateAccountConfigurationsRequest
	3,  // 3: alpaca.trading.v1.TradingService.GetPortfolioHistory:input_type -> alpaca.trading.v1.GetPortfolioHistoryRequest
	4,  // 4: alpaca.trading.v1.TradingService.GetAccountActivities:input_type -> alpaca.trading.v1.GetAccountActivitiesRequest
	5,  // 5: alpaca.trading.v1.TradingService.GetAccountActivitiesByType:input_type -> alpaca.trading.v1.GetAccountActivitiesByTypeRequest
	6,  // 6: alpaca.trading.v1.TradingService.CreateOrder:input_type -> alpaca.trading.v1.CreateOrderRequest
	7,  // 7: alpaca.trading.v1.TradingService.ListOrders:input_type -> alpaca.trading.v1.ListOrdersRequest
	8,  // 8: alpaca.trading.v1.TradingService.GetOrder:input_type -> alpaca.trading.v1.GetOrderRequest
	9,  // 9: alpaca.trading.v1.TradingService.GetOrderByClientId:input_type -> alpaca.trading.v1.GetOrderByClientIdRequest
	10, // 10: alpaca.trading.v1.TradingService.ReplaceOrder:input_type -> alpaca.trading.v1.ReplaceOrderRequest
	11, // 11: alpaca.trading.v1.TradingService.CancelOrder:input_type -> alpaca.trading.v1.CancelOrderRequest
	12, // 12: alpaca.trading.v1.TradingService.CancelAllOrders:input_type -> alpaca.trading.v1.CancelAllOrdersRequest
	13, // 13: alpaca.trading.v1.TradingService.ListPositions:input_type -> alpaca.trading.v1.ListPositionsRequest
	14, // 14: alpaca.trading.v1.TradingService.GetPosition:input_type -> alpaca.trading.v1.GetPositionRequest
	15, // 15: alpaca.trading.v1.TradingService.ClosePosition:input_type -> alpaca.trading.v1.ClosePositionRequest
	16, // 16: alpaca.trading.v1.TradingService.CloseAllPositions:input_type -> alpaca.trading.v1.CloseAllPositionsRequest
	17, // 17: alpaca.trading.v1.TradingService.ExerciseOption:input_type -> alpaca.trading.v1.ExerciseOptionRequest
	18, // 18: alpaca.trading.v1.TradingService.ListAssets:input_type -> alpaca.trading.v1.ListAssetsRequest
	19, // 19: alpaca.trading.v1.TradingService.GetAsset:input_type -> alpaca.trading.v1.GetAssetRequest
	20, // 20: alpaca.trading.v1.TradingService.GetClock:input_type -> alpaca.trading.v1.GetClockRequest
	21, // 21: alpaca.trading.v1.TradingService.GetCalendar:input_type -> alpaca.trading.v1.GetCalendarRequest
	22, // 22: alpaca.trading.v1.TradingService.ListWatchlists:input_type -> alpaca.trading.v1.ListWatchlistsRequest
	23, // 23: alpaca.trading.v1.TradingService.CreateWatchlist:input_type -> alpaca.trading.v1.CreateWatchlistRequest
	24, // 24: alpaca.trading.v1.TradingService.GetWatchlist:input_type -> alpaca.trading.v1.GetWatchlistRequest
	25, // 25: alpaca.trading.v1.TradingService.UpdateWatchlist:input_type -> alpaca.trading.v1.UpdateWatchlistRequest
	26, // 26: alpaca.trading.v1.TradingService.DeleteWatchlist:input_type -> alpaca.trading.v1.DeleteWatchlistRequest
	27, // 27: alpaca.trading.v1.TradingService.AddWatchlistAsset:input_type -> alpaca.trading.v1.AddWatchlistAssetRequest
	28, // 28: alpaca.trading.v1.TradingService.RemoveWatchlistAsset:input_type -> alpaca.trading.v1.RemoveWatchlistAssetRequest
	29, // 29: alpaca.trading.v1.TradingService.GetAccount:output_type -> alpaca.trading.v1.Account
	30, // 30: alpaca.trading.v1.TradingService.GetAccountConfigurations:output_type -> alpaca.trading.v1.AccountConfigurations
	30, // 31: alpaca.trading.v1.TradingService.UpdateAccountConfigurations:output_type -> alpaca.trading.v1.AccountConfigurations
	31, // 32: alpaca.trading.v1.TradingService.GetPortfolioHistory:output_type -> alpaca.trading.v1.PortfolioHistory
	32, // 33: alpaca.trading.v1.TradingService.GetAccountActivities:output_type -> alpaca.trading.v1.GetAccountActivitiesResponse
	32, // 34: alpaca.trading.v1.TradingService.GetAccountActivitiesByType:output_type -> alpaca.trading.v1.GetAccountActivitiesResponse
	33, // 35: alpaca.trading.v1.TradingService.CreateOrder:output_type -> alpaca.trading.v1.Order
	34, // 36: alpaca.trading.v1.TradingService.ListOrders:output_type -> alpaca.trading.v1.ListOrdersResponse
	33, // 37: alpaca.trading.v1.TradingService.GetOrder:output_type -> alpaca.trading.v1.Order
	33, // 38: alpaca.trading.v1.TradingService.GetOrderByClientId:output_type -> alpaca.trading.v1.Order
	33, // 39: alpaca.trading.v1.TradingService.ReplaceOrder:output_type -> alpaca.trading.v1.Order
	35, // 40: alpaca.trading.v1.TradingService.CancelOrder:output_type -> alpaca.trading.v1.CancelOrderResponse
	36, // 41: alpaca.trading.v1.TradingService.CancelAllOrders:output_type -> alpaca.trading.v1.CancelAllOrdersResponse
	37, // 42: alpaca.trading.v1.TradingService.ListPositions:output_type -> alpaca.trading.v1.ListPositionsResponse
	38, // 43: alpaca.trading.v1.TradingService.GetPosition:output_type -> alpaca.trading.v1.Position
	33, // 44: alpaca.trading.v1.TradingService.ClosePosition:output_type -> alpaca.trading.v1.Order
	39, // 45: alpaca.trading.v1.TradingService.CloseAllPositions:output_type -> alpaca.trading.v1.CloseAllPositionsResponse
	40, // 46: alpaca.trading.v1.TradingService.ExerciseOption:output_type -> alpaca.trading.v1.ExerciseOptionResponse
	41, // 47: alpaca.trading.v1.TradingService.ListAssets:output_type -> alpaca.trading.v1.ListAssetsResponse
	42, // 48: alpaca.trading.v1.TradingService.GetAsset:output_type -> alpaca.trading.v1.Asset
	43, // 49: alpaca.trading.v1.TradingService.GetClock:output_type -> alpaca.trading.v1.Clock
	44, // 50: alpaca.trading.v1.TradingService.GetCalendar:output_type -> alpaca.trading.v1.GetCalendarResponse
	45, // 51: alpaca.trading.v1.TradingService.ListWatchlists:output_type -> alpaca.trading.v1.ListWatchlistsResponse
	46, // 52: alpaca.trading.v1.TradingService.CreateWatchlist:output_type -> alpaca.trading.v1.Watchlist
	46, // 53: alpaca.trading.v1.TradingService.GetWatchlist:output_type -> alpaca.trading.v1.Watchlist
	46, // 54: alpaca.trading.v1.TradingService.UpdateWatchlist:output_type -> alpaca.trading.v1.Watchlist
	47, // 55: alpaca.trading.v1.TradingService.DeleteWatchlist:output_type -> alpaca.trading.v1.DeleteWatchlistResponse
	46, // 56: alpaca.trading.v1.TradingService.AddWatchlistAsset:output_type -> alpaca.trading.v1.Watchlist
	48, // 57: alpaca.trading.v1.TradingService.RemoveWatchlistAsset:output_type -> alpaca.trading.v1.RemoveWatchlistAssetResponse
	29, // [29:58] is the sub-list for method output_type
	0,  // [0:29] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_alpaca_trading_v1_service_proto_init() }
func file_alpaca_trading_v1_service_proto_init() {
	if File_alpaca_trading_v1_service_proto != nil {
		return
	}
	file_alpaca_trading_v1_account_proto_init()
	file_alpaca_trading_v1_get_account_proto_init()
	file_alpaca_trading_v1_order_proto_init()
	file_alpaca_trading_v1_create_order_proto_init()
	file_alpaca_trading_v1_get_order_proto_init()
	file_alpaca_trading_v1_list_orders_proto_init()
	file_alpaca_trading_v1_cancel_order_proto_init()
	file_alpaca_trading_v1_cancel_all_orders_proto_init()
	file_alpaca_trading_v1_replace_order_proto_init()
	file_alpaca_trading_v1_get_order_by_client_id_proto_init()
	file_alpaca_trading_v1_position_proto_init()
	file_alpaca_trading_v1_list_positions_proto_init()
	file_alpaca_trading_v1_get_position_proto_init()
	file_alpaca_trading_v1_close_position_proto_init()
	file_alpaca_trading_v1_close_all_positions_proto_init()
	file_alpaca_trading_v1_exercise_option_proto_init()
	file_alpaca_trading_v1_asset_proto_init()
	file_alpaca_trading_v1_list_assets_proto_init()
	file_alpaca_trading_v1_get_asset_proto_init()
	file_alpaca_trading_v1_clock_proto_init()
	file_alpaca_trading_v1_calendar_proto_init()
	file_alpaca_trading_v1_watchlist_proto_init()
	file_alpaca_trading_v1_list_watchlists_proto_init()
	file_alpaca_trading_v1_create_watchlist_proto_init()
	file_alpaca_trading_v1_get_watchlist_proto_init()
	file_alpaca_trading_v1_update_watchlist_proto_init()
	file_alpaca_trading_v1_delete_watchlist_proto_init()
	file_alpaca_trading_v1_add_watchlist_asset_proto_init()
	file_alpaca_trading_v1_remove_watchlist_asset_proto_init()
	file_alpaca_trading_v1_account_configurations_proto_init()
	file_alpaca_trading_v1_portfolio_history_proto_init()
	file_alpaca_trading_v1_account_activity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alpaca_trading_v1_service_proto_rawDesc), len(file_alpaca_trading_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alpaca_trading_v1_service_proto_goTypes,
		DependencyIndexes: file_alpaca_trading_v1_service_proto_depIdxs,
	}.Build()
	File_alpaca_trading_v1_service_proto = out.File
	file_alpaca_trading_v1_service_proto_goTypes = nil
	file_alpaca_trading_v1_service_proto_depIdxs = nil
}
