// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: alpaca/trading/v1/service.proto

package tradingv1

import (
	"context"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

// TradingServiceServer is the server API for TradingService service.
type TradingServiceServer interface {
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*Order, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*Order, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	CancelAllOrders(context.Context, *CancelAllOrdersRequest) (*CancelAllOrdersResponse, error)
	ListPositions(context.Context, *ListPositionsRequest) (*ListPositionsResponse, error)
	GetPosition(context.Context, *GetPositionRequest) (*Position, error)
	ClosePosition(context.Context, *ClosePositionRequest) (*Order, error)
	CloseAllPositions(context.Context, *CloseAllPositionsRequest) (*CloseAllPositionsResponse, error)
}

// RegisterTradingServiceServer registers the HTTP handlers for service TradingService to the given mux.
func RegisterTradingServiceServer(server TradingServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getTradingServiceHeaders()

	methodHeaders := getGetAccountHeaders()
	getAccountHandler := BindingMiddleware[GetAccountRequest](
		genericHandler(server.GetAccount, config.errorHandler), serviceHeaders, methodHeaders,
		getAccountPathParams, getAccountQueryParams,
		"GET", config.errorHandler,
	)

	config.mux.Handle("GET /v1/trading/accounts/{account_id}", getAccountHandler)

	methodHeaders = getCreateOrderHeaders()
	createOrderHandler := BindingMiddleware[CreateOrderRequest](
		genericHandler(server.CreateOrder, config.errorHandler), serviceHeaders, methodHeaders,
		createOrderPathParams, createOrderQueryParams,
		"POST", config.errorHandler,
	)

	config.mux.Handle("POST /v1/trading/accounts/{account_id}/orders", createOrderHandler)

	methodHeaders = getListOrdersHeaders()
	listOrdersHandler := BindingMiddleware[ListOrdersRequest](
		genericHandler(server.ListOrders, config.errorHandler), serviceHeaders, methodHeaders,
		listOrdersPathParams, listOrdersQueryParams,
		"GET", config.errorHandler,
	)

	config.mux.Handle("GET /v1/trading/accounts/{account_id}/orders", listOrdersHandler)

	methodHeaders = getGetOrderHeaders()
	getOrderHandler := BindingMiddleware[GetOrderRequest](
		genericHandler(server.GetOrder, config.errorHandler), serviceHeaders, methodHeaders,
		getOrderPathParams, getOrderQueryParams,
		"GET", config.errorHandler,
	)

	config.mux.Handle("GET /v1/trading/accounts/{account_id}/orders/{order_id}", getOrderHandler)

	methodHeaders = getCancelOrderHeaders()
	cancelOrderHandler := BindingMiddleware[CancelOrderRequest](
		genericHandler(server.CancelOrder, config.errorHandler), serviceHeaders, methodHeaders,
		cancelOrderPathParams, cancelOrderQueryParams,
		"DELETE", config.errorHandler,
	)

	config.mux.Handle("DELETE /v1/trading/accounts/{account_id}/orders/{order_id}", cancelOrderHandler)

	methodHeaders = getCancelAllOrdersHeaders()
	cancelAllOrdersHandler := BindingMiddleware[CancelAllOrdersRequest](
		genericHandler(server.CancelAllOrders, config.errorHandler), serviceHeaders, methodHeaders,
		cancelAllOrdersPathParams, cancelAllOrdersQueryParams,
		"DELETE", config.errorHandler,
	)

	config.mux.Handle("DELETE /v1/trading/accounts/{account_id}/orders", cancelAllOrdersHandler)

	methodHeaders = getListPositionsHeaders()
	listPositionsHandler := BindingMiddleware[ListPositionsRequest](
		genericHandler(server.ListPositions, config.errorHandler), serviceHeaders, methodHeaders,
		listPositionsPathParams, listPositionsQueryParams,
		"GET", config.errorHandler,
	)

	config.mux.Handle("GET /v1/trading/accounts/{account_id}/positions", listPositionsHandler)

	methodHeaders = getGetPositionHeaders()
	getPositionHandler := BindingMiddleware[GetPositionRequest](
		genericHandler(server.GetPosition, config.errorHandler), serviceHeaders, methodHeaders,
		getPositionPathParams, getPositionQueryParams,
		"GET", config.errorHandler,
	)

	config.mux.Handle("GET /v1/trading/accounts/{account_id}/positions/{symbol}", getPositionHandler)

	methodHeaders = getClosePositionHeaders()
	closePositionHandler := BindingMiddleware[ClosePositionRequest](
		genericHandler(server.ClosePosition, config.errorHandler), serviceHeaders, methodHeaders,
		closePositionPathParams, closePositionQueryParams,
		"DELETE", config.errorHandler,
	)

	config.mux.Handle("DELETE /v1/trading/accounts/{account_id}/positions/{symbol}", closePositionHandler)

	methodHeaders = getCloseAllPositionsHeaders()
	closeAllPositionsHandler := BindingMiddleware[CloseAllPositionsRequest](
		genericHandler(server.CloseAllPositions, config.errorHandler), serviceHeaders, methodHeaders,
		closeAllPositionsPathParams, closeAllPositionsQueryParams,
		"DELETE", config.errorHandler,
	)

	config.mux.Handle("DELETE /v1/trading/accounts/{account_id}/positions", closeAllPositionsHandler)

	return nil
}

// getTradingServiceHeaders returns the service-level required headers for TradingService
func getTradingServiceHeaders() []*sebufhttp.Header {
	return []*sebufhttp.Header{
		{
			Name:        "APCA-API-KEY-ID",
			Description: "Alpaca API key ID",
			Type:        "string",
			Required:    true,
			Format:      "",
			Example:     "PKXXXXXXXXXXXXXXXXXX",
			Deprecated:  false,
		},
		{
			Name:        "APCA-API-SECRET-KEY",
			Description: "Alpaca API secret key",
			Type:        "string",
			Required:    true,
			Format:      "",
			Example:     "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
			Deprecated:  false,
		},
	}
}

// getGetAccountHeaders returns the method-level required headers for GetAccount
func getGetAccountHeaders() []*sebufhttp.Header {
	return nil
}

// getCreateOrderHeaders returns the method-level required headers for CreateOrder
func getCreateOrderHeaders() []*sebufhttp.Header {
	return nil
}

// getListOrdersHeaders returns the method-level required headers for ListOrders
func getListOrdersHeaders() []*sebufhttp.Header {
	return nil
}

// getGetOrderHeaders returns the method-level required headers for GetOrder
func getGetOrderHeaders() []*sebufhttp.Header {
	return nil
}

// getCancelOrderHeaders returns the method-level required headers for CancelOrder
func getCancelOrderHeaders() []*sebufhttp.Header {
	return nil
}

// getCancelAllOrdersHeaders returns the method-level required headers for CancelAllOrders
func getCancelAllOrdersHeaders() []*sebufhttp.Header {
	return nil
}

// getListPositionsHeaders returns the method-level required headers for ListPositions
func getListPositionsHeaders() []*sebufhttp.Header {
	return nil
}

// getGetPositionHeaders returns the method-level required headers for GetPosition
func getGetPositionHeaders() []*sebufhttp.Header {
	return nil
}

// getClosePositionHeaders returns the method-level required headers for ClosePosition
func getClosePositionHeaders() []*sebufhttp.Header {
	return nil
}

// getCloseAllPositionsHeaders returns the method-level required headers for CloseAllPositions
func getCloseAllPositionsHeaders() []*sebufhttp.Header {
	return nil
}

// getAccountPathParams contains path parameter configuration for GetAccount
var getAccountPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
}

// getAccountQueryParams contains query parameter configuration for GetAccount
var getAccountQueryParams = []QueryParamConfig{}

// createOrderPathParams contains path parameter configuration for CreateOrder
var createOrderPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
}

// createOrderQueryParams contains query parameter configuration for CreateOrder
var createOrderQueryParams = []QueryParamConfig{}

// listOrdersPathParams contains path parameter configuration for ListOrders
var listOrdersPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
}

// listOrdersQueryParams contains query parameter configuration for ListOrders
var listOrdersQueryParams = []QueryParamConfig{
	{QueryName: "status", FieldName: "status", Required: false},
	{QueryName: "limit", FieldName: "limit", Required: false},
	{QueryName: "after", FieldName: "after", Required: false},
	{QueryName: "until", FieldName: "until", Required: false},
	{QueryName: "direction", FieldName: "direction", Required: false},
	{QueryName: "nested", FieldName: "nested", Required: false},
	{QueryName: "symbols", FieldName: "symbols", Required: false},
	{QueryName: "side", FieldName: "side", Required: false},
}

// getOrderPathParams contains path parameter configuration for GetOrder
var getOrderPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
	{URLParam: "order_id", FieldName: "order_id"},
}

// getOrderQueryParams contains query parameter configuration for GetOrder
var getOrderQueryParams = []QueryParamConfig{
	{QueryName: "nested", FieldName: "nested", Required: false},
}

// cancelOrderPathParams contains path parameter configuration for CancelOrder
var cancelOrderPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
	{URLParam: "order_id", FieldName: "order_id"},
}

// cancelOrderQueryParams contains query parameter configuration for CancelOrder
var cancelOrderQueryParams = []QueryParamConfig{}

// cancelAllOrdersPathParams contains path parameter configuration for CancelAllOrders
var cancelAllOrdersPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
}

// cancelAllOrdersQueryParams contains query parameter configuration for CancelAllOrders
var cancelAllOrdersQueryParams = []QueryParamConfig{}

// listPositionsPathParams contains path parameter configuration for ListPositions
var listPositionsPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
}

// listPositionsQueryParams contains query parameter configuration for ListPositions
var listPositionsQueryParams = []QueryParamConfig{}

// getPositionPathParams contains path parameter configuration for GetPosition
var getPositionPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
	{URLParam: "symbol", FieldName: "symbol"},
}

// getPositionQueryParams contains query parameter configuration for GetPosition
var getPositionQueryParams = []QueryParamConfig{}

// closePositionPathParams contains path parameter configuration for ClosePosition
var closePositionPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
	{URLParam: "symbol", FieldName: "symbol"},
}

// closePositionQueryParams contains query parameter configuration for ClosePosition
var closePositionQueryParams = []QueryParamConfig{
	{QueryName: "qty", FieldName: "qty", Required: false},
	{QueryName: "percentage", FieldName: "percentage", Required: false},
}

// closeAllPositionsPathParams contains path parameter configuration for CloseAllPositions
var closeAllPositionsPathParams = []PathParamConfig{
	{URLParam: "account_id", FieldName: "account_id"},
}

// closeAllPositionsQueryParams contains query parameter configuration for CloseAllPositions
var closeAllPositionsQueryParams = []QueryParamConfig{
	{QueryName: "cancel_orders", FieldName: "cancel_orders", Required: false},
}
